### ISSUE TITLE
VideoPlayer: drop FipPage #12776 causes flickering in Hyperion

### ISSUE THREAD

**Issue by iLLiac4** [xbmc/xbmc#15153]
After spending a lot of time tracking down the changeses that could cause flickering in hyperion this was found as a possible cause for flickering. User @hasenbolle has also create a debug addon that captures the screenshots and every few seconds strange screenshot is taken that causes flickering.

This was introduced in 2017 september.
All the needed details are in this post:
https://forum.kodi.tv/showthread.php?tid=338046

I hope some developer can comment this behaviour.

TNX

**Comment by fightforlife** [comment]
Also interested!

**Comment by hasenbolle** [comment]
Build #910 of 2017 introduced the flickering of the leds. Hyperion uses the RenderCapture() method to generate the colors for the leds. But the RenderCapture() method return faulty images, which causes hyperion to generate wrong colors. Many images which are generated are black. So hyperion will turn of the leds which looks like the leds are flickering.

Debug log and more information is attached in this post:
https://forum.kodi.tv/showthread.php?tid=298462&pid=2799309#pid2799309

**Comment by sophof** [comment]
I have the same issue, but maybe can add some extra info as well. I have tried both boblight and hyperion and they both suffer identically. I've checked their code on github and they both use the call "xbmc.RenderCapture()".

**Comment by FernetMenta** [comment]
I think it can be fixed by passing renderbuffer index to CBaseRenderer::RenderCapture

**Comment by iLLiac4** [comment]
Hi. Do you mean in https://github.com/hyperion-project/hyperion.kodi/blob/master/resources/lib/state.py ?

# create the capture object
        self.__capture = xbmc.RenderCapture()
        self.__capture.capture(self.__settings.capture_width, self.__settings.capture_height)

to

# create the capture object
        self.__capture = CBaseRenderer::RenderCapture()
        self.__capture.capture(self.__settings.capture_width, self.__settings.capture_height)

**Comment by iLLiac4** [comment]
Have tried to change that in addon and now addon throws an error. Have tasted it on  latest nightly from milhouse.

2019-05-12 06:59:20.825 T:139867605632768   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.SyntaxError'>
                                            Error Contents: invalid syntax (state.py, line 68)
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/script.service.hyperion/addon.py", line 36, in <module>
                                                from state import DisconnectedState
                                              File "/storage/.kodi/addons/script.service.hyperion/resources/lib/state.py", line 68
                                                self.__capture = CBaseRenderer::RenderCapture()
                                                                              ^
                                            SyntaxError: invalid syntax
                                            -->End of Python script error report<--

**Comment by hasenbolle** [comment]
> I think it can be fixed by passing renderbuffer index to CBaseRenderer::RenderCapture

Is this something i can fix in the addon? Right now the addon is using this method https://codedocs.xyz/xbmc/xbmc/class_x_b_m_c_addon_1_1xbmc_1_1_render_capture.html.

**Comment by iLLiac4** [comment]
Hi. Did someone succseed to fit this as FernetMenta sugested? I have tried but did not work :(

**Comment by AlexKid007** [comment]
@iLLiac4 
I also tried a bit. Your syntax is not correct like the log said. It must be CBaseRender.RenderCapture(). With this I get no error but the RenderManager wait for a buffer and protobuf do not send anything to hyperion. The CBaseRenderer do not have an method capture so the next line doesn't work. I have commented it out and get the mentioned warning. So I think to use CBaseRender the hole add-on must be rewritten.

**Comment by fightforlife** [comment]
@FernetMenta  Can you give us a hint regarding your comment:

> I think it can be fixed by passing renderbuffer index to CBaseRenderer::RenderCapture

Most likely it is an easy fix and the plugin is just using a wrong/old method to capture?

https://github.com/hyperion-project/hyperion.kodi/blob/f9a25c464fada0fe0f57319775de1a73bcaeb08d/script.service.hyperion/resources/lib/monitor.py#L115

**Comment by fightforlife** [comment]
Chances are that this will be fixed in v21 Beta 3. 
My local build with the following PR does not have any black dropouts!
https://github.com/xbmc/xbmc/pull/24439
