### ISSUE TITLE
v18.0/linux x64: crash on exit in freetype-2.9.1

### ISSUE THREAD

**Issue by mlauss** [xbmc/xbmc#15592]
### Describe the bug
When I exit kodi v18.0 release, it causes a crash inside freetype.

face->internal  is NULL for some unknown reason.

## Expected Behavior
no crash during shutdown.

### To Reproduce

1.  Have Linux x86-64, freetype-2.9.1 and kodi-v18 release installed.
2. shut kodi down via menu
3. watch it crash.

### Debuglog

The debuglog can be found here:
```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f4a62ef3e9b in FT_Done_Face (face=0x3847cf0) at /tmp-ram/portage/media-libs/freetype-2.9.1-r4/work/freetype-2.9.1/src/base/ftobjs.c:2732
2732          face->internal->refcount--;
[Current thread is 1 (Thread 0x7f4a5eb3d880 (LWP 583))]
(gdb) bt
#0  0x00007f4a62ef3e9b in FT_Done_Face (face=0x3847cf0) at /tmp-ram/portage/media-libs/freetype-2.9.1-r4/work/freetype-2.9.1/src/base/ftobjs.c:2732
#1  0x0000000000ef24ad in CFreeTypeLibrary::ReleaseFont (face=<optimized out>) at /tmp-ram/portage/media-tv/kodi-9999/work/kodi-9999/xbmc/guilib/GUIFontTTF.cpp:136
#2  CGUIFontTTFBase::Clear (this=this@entry=0x386c050) at /tmp-ram/portage/media-tv/kodi-9999/work/kodi-9999/xbmc/guilib/GUIFontTTF.cpp:230
#3  0x0000000000ef25a0 in CGUIFontTTFBase::~CGUIFontTTFBase (this=0x386c050, __in_chrg=<optimized out>)
    at /tmp-ram/portage/media-tv/kodi-9999/work/kodi-9999/xbmc/guilib/GUIFontTTF.cpp:181
#4  0x0000000000f53c89 in CGUIFontTTFGL::~CGUIFontTTFGL (this=0x386c050, __in_chrg=<optimized out>)
    at /tmp-ram/portage/media-tv/kodi-9999/work/kodi-9999/xbmc/guilib/GUIFontTTFGL.cpp:45
#5  0x0000000000eeb679 in CGUIFont::~CGUIFont (this=0x3ab40a0, __in_chrg=<optimized out>)
    at /tmp-ram/portage/media-tv/kodi-9999/work/kodi-9999/xbmc/guilib/GUIFont.cpp:72
#6  0x0000000000eeb6a9 in CGUIFont::~CGUIFont (this=0x3ab40a0, __in_chrg=<optimized out>)
    at /tmp-ram/portage/media-tv/kodi-9999/work/kodi-9999/xbmc/guilib/GUIFont.cpp:69
#7  0x0000000000eeecd7 in GUIFontManager::Clear (this=this@entry=0x31e1090) at /tmp-ram/portage/media-tv/kodi-9999/work/kodi-9999/xbmc/guilib/GUIFontManager.cpp:334
#8  0x0000000000eeedc3 in GUIFontManager::~GUIFontManager (this=0x31e1090, __in_chrg=<optimized out>)
    at /tmp-ram/portage/media-tv/kodi-9999/work/kodi-9999/xbmc/guilib/GUIFontManager.cpp:43
#9  0x0000000000eeeee9 in GUIFontManager::~GUIFontManager (this=0x31e1090, __in_chrg=<optimized out>)
    at /tmp-ram/portage/media-tv/kodi-9999/work/kodi-9999/xbmc/guilib/GUIFontManager.cpp:41
#10 0x0000000000ae6287 in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release (this=0x31c7d50)
    at /usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/include/g++-v8/bits/shared_ptr_base.h:148
#11 std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release (this=0x31c7d50) at /usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/include/g++-v8/bits/shared_ptr_base.h:148
#12 std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count (this=<optimized out>, __in_chrg=<optimized out>)
    at /usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/include/g++-v8/bits/shared_ptr_base.h:728
#13 std::__shared_ptr<GUIFontManager, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr (this=<optimized out>, __in_chrg=<optimized out>)
    at /usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/include/g++-v8/bits/shared_ptr_base.h:1167
#14 std::shared_ptr<GUIFontManager>::~shared_ptr (this=<optimized out>, __in_chrg=<optimized out>)
    at /usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/include/g++-v8/bits/shared_ptr.h:103
#15 0x00007f4a62603a9c in ?? () from /lib64/libc.so.6
#16 0x00007f4a62603bda in exit () from /lib64/libc.so.6
#17 0x00007f4a62862cb5 in _XDefaultIOError () from /lib64/libX11.so.6
#18 0x00007f4a62863bde in _XIOError () from /lib64/libX11.so.6
#19 0x00007f4a62865e73 in _XEventsQueued () from /lib64/libX11.so.6
#20 0x00007f4a628782e7 in XPending () from /lib64/libX11.so.6
#21 0x0000000000b1f446 in CWinEventsX11::MessagePump (this=0x326f250) at /tmp-ram/portage/media-tv/kodi-9999/work/kodi-9999/xbmc/windowing/X11/WinEventsX11.cpp:288
#22 0x0000000000d49392 in CWinSystemBase::DriveRenderLoop (this=0x3330170)
    at /tmp-ram/portage/media-tv/kodi-9999/work/kodi-9999/xbmc/threads/platform/RecursiveMutex.h:36
#23 0x00000000010c1734 in CApplication::FrameMove (this=0x31def30, processEvents=<optimized out>, processGUI=<optimized out>)
    at /tmp-ram/portage/media-tv/kodi-9999/work/kodi-9999/xbmc/Application.cpp:2407
#24 0x00000000011453e0 in CXBApplicationEx::Run (this=0x31def30, params=...) at /tmp-ram/portage/media-tv/kodi-9999/work/kodi-9999/xbmc/XBApplicationEx.cpp:68
#25 0x0000000000e39f0e in XBMC_Run (renderGUI=renderGUI@entry=true, params=...) at /tmp-ram/portage/media-tv/kodi-9999/work/kodi-9999/xbmc/utils/GlobalsHandling.h:160
#26 0x0000000000976377 in main (argc=2, argv=0x7ffcf92fc178) at /tmp-ram/portage/media-tv/kodi-9999/work/kodi-9999/xbmc/platform/posix/main.cpp:93
```

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [X] Linux

 - Operating system version/name:
 - Kodi version: 18.0 / Leia

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by mlauss** [comment]
I patched freetype to work around this.  I'm still leaning towards this being a kodi bug, because I have not yet seen this crash in other applications or KDE.
