### ISSUE TITLE
Python 3 Version of Kodi: failure to import module decimal

### ISSUE THREAD

**Issue by tuxpoldo** [xbmc/xbmc#15708]
## Bug report
This report applies to the test version for Python 3 Addon developers.
Kodi (18.2-RC1 Git:20190305-0274493910). Platform: OS X x86 64-bit
### Describe the bug
When importing the module `ijson`, an import exception is thrown.
It seems that the python 3 version included in the latest test version of Kodi still has a problem with some of the standard modules: importing the module `ijson` fails since it tries to import the module `decimal` that imports the module `contextvars` that tries to import some symbols from `_contextvars`

## Expected Behavior
Loading the Python standard module `decimal` should work.

## Actual Behavior
Loading the Python standard module `decimal` will throw an exception.

### To Reproduce

````
import decimal
````

or 

````
import contextvars
from _contextvars import Context
````

in your plugin.

### Debuglog

The debuglog can be found here:
````
2019-03-09 18:18:11.487 T:123145461612544   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                            - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                           Error Type: <class 'ModuleNotFoundError'>
                                           Error Contents: No module named '_contextvars'
                                           Traceback (most recent call last):
                                             File "/Users/leo/Applications/Kodi 19.app/Contents/Libraries/lib/python3.7/decimal.py", line 3, in <module>
                                               from _decimal import *
                                           ModuleNotFoundError: No module named '_decimal'

                                           During handling of the above exception, another exception occurred:

                                           Traceback (most recent call last):
                                             File "/Users/leo/Library/Application Support/Kodi/addons/plugin.video.mediathekview/service.py", line 29, in <module>
                                               from resources.lib.service import MediathekViewService
                                             File "/Users/leo/Library/Application Support/Kodi/addons/plugin.video.mediathekview/resources/lib/service.py", line 17, in <module>
                                               from resources.lib.updater import MediathekViewUpdater
                                             File "/Users/leo/Library/Application Support/Kodi/addons/plugin.video.mediathekview/resources/lib/updater.py", line 23, in <module>
                                               import ijson
                                             File "/Users/leo/Library/Application Support/Kodi/addons/script.module.ijson/lib/ijson/__init__.py", line 16, in <module>
                                               from ijson.common import JSONError, IncompleteJSONError, ObjectBuilder
                                             File "/Users/leo/Library/Application Support/Kodi/addons/script.module.ijson/lib/ijson/common.py", line 4, in <module>
                                               import decimal
                                             File "/Users/leo/Applications/Kodi 19.app/Contents/Libraries/lib/python3.7/decimal.py", line 8, in <module>
                                               from _pydecimal import *
                                             File "/Users/leo/Applications/Kodi 19.app/Contents/Libraries/lib/python3.7/_pydecimal.py", line 436, in <module>
                                               import contextvars
                                             File "/Users/leo/Applications/Kodi 19.app/Contents/Libraries/lib/python3.7/contextvars.py", line 1, in <module>
                                               from _contextvars import Context, ContextVar, Token, copy_context
                                           ModuleNotFoundError: No module named '_contextvars'
                                           -->End of Python script error report<--
````

### Your Environment
Used Operating system:

 - [X] OSX

 - Operating system version/name: macOS Mojave Version 10.14.3
 - Kodi version: Kodi (18.2-RC1 Git:20190305-0274493910). Platform: OS X x86 64-bit

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by fuzzard** [comment]
Tested working in current master
