### ISSUE TITLE
Kodi PR16116 test build crashes when loading add-on with unicode character in Windows user profile path

### ISSUE THREAD

**Issue by mediaminister** [xbmc/xbmc#16577]
### Describe the bug
Here is a clear and concise description of what the problem is:

When loading a Kodi add-on in Kodi PR16116 test build on a Windows system that has a unicode character in the Windows user profile path, Kodi crashes.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

When loading a Kodi add-on in Kodi PR16116 test build on a Windows system that has a unicode character in the Windows user profile path, the add-on should load and run just fine.

## Actual Behavior

Kodi crashes.

### To Reproduce

1. Download and install Kodi PR16116 test build from http://mirrors.kodi.tv/test-builds/windows/win64/KodiSetup-20190902-bd080bb9-PR16116-merge-x64.exe
2. Open Kodi  and install an add-on, for instance Soundcloud
3. When the add-on is installed and loaded, Kodi crashes

### Debuglog

The debuglog can be found here:

[kodi.log](https://github.com/xbmc/xbmc/files/3583716/kodi.log)

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10 x64
 - Kodi version: 19.0-ALPHA1 Git:20190902-bd080bb96c (https://github.com/xbmc/xbmc/pull/16116)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by Rechi** [comment]
@mediaminister please test https://mirrors.kodi.tv/test-builds/windows/win64/KodiSetup-20190901-2be1f886-windows-python3-utf8-x64.exe and report back.

**Comment by mediaminister** [comment]
Thanks for the quick response, this Kodi version doesn't crash anymore. I can use unicode characters in Windows user profile paths now, so I consider this issue as fixed.

As I expected, I now get errors from add-ons, which I will report to the relevant add-on developers.
I still can't play DRM protected streams, but I think this is a InputStream Adaptive bug:
```
2019-09-07 11:44:12.196 T:18446744073709551614   ERROR: AddOnLog: InputStream Adaptive: No decrypter found for encrypted stream
```
For your information, here is a full debug log from your test version 19.0-ALPHA1 Git:20190901-2be1f886cd
[kodi.log](https://github.com/xbmc/xbmc/files/3586480/kodi.log)

**Comment by Rechi** [comment]
Please confirm it's now also working with the most recent python3 test-build at https://mirrors.kodi.tv/test-builds/windows/win64/, 20190907-e0bfcd95-PR16116.

**Comment by mediaminister** [comment]
I can confirm Kodi 19.0-ALPHA1 Git:20190907-e0bfcd95b4 doesn't crash anymore: [20190907-e0bfcd95b4.log](https://github.com/xbmc/xbmc/files/3586777/20190907-e0bfcd95b4.log)

But the problem with InputStream Adaptive persists, it can't find ssd_wv.dll because `dlopen` fails on the unicode path.
```
2019-09-07 18:11:39.037 T:18446744073709551614   DEBUG: AddOnLog: InputStream Adaptive: "C:\Users\Vrömékí\AppData\Roaming\Kodi\addons\inputstream.adaptive\ssd_wv.dll": Kan opgegeven module niet vinden.
```

I did the same test with the same `C:\Users\Vrömékí\` Windows profile on standard Kodi 18.4 and ssd_wv.dll just loaded fine:
```
2019-09-07 18:16:48.648 T:10100   DEBUG: AddOnLog: InputStream Adaptive: Found decrypter: C:\Users\Vrömékí\AppData\Roaming\Kodi\addons\inputstream.adaptive\ssd_wv.dll
```
Full debug log from Kodi 18.4 Windows x64: 
[kodi18.4.log](https://github.com/xbmc/xbmc/files/3586784/kodi18.4.log)

@peak3d Can you take a look at this?

**Comment by peak3d** [comment]
@mediaminister  Seems to be related to: https://github.com/dlfcn-win32/dlfcn-win32/pull/50

**Comment by mediaminister** [comment]
@peak3d Thanks, I'll try to compile a version that works.

**Comment by mediaminister** [comment]
@Rechi There is a problem with BeautifulSoup4 in Kodi 19.0-ALPHA1 Git:20190907-e0bfcd95b4: the Python 2 version of BeautifulSoup4 is being used.
I tried to set the dependency of the add-on to the Python 3 version 4.6.3 (http://mirrors.kodi.tv/addons/migration/script.module.beautifulsoup4/script.module.beautifulsoup4-4.6.3.zip)
But I get:
```
2019-09-08 14:07:46.554 T:18446744073709551614   DEBUG: CAddonInstallJob[plugin.video.vrt.nu]: requires script.module.beautifulsoup4 version 4.6.3 which is not available
2019-09-08 14:07:46.554 T:18446744073709551614   ERROR: CAddonInstallJob[plugin.video.vrt.nu]: The dependency on script.module.beautifulsoup4 version 4.6.3 could not be satisfied.
```
Obviously, we need the BeautifulSoup4 Python 3 version because now add-ons using BeautifulSoup4 get this error:
```
2019-09-06 11:08:03.916 T:18446744073709551614   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'ModuleNotFoundError'>
                                            Error Contents: No module named 'htmlentitydefs'
                                            Traceback (most recent call last):
                                              File "C:\Kodi\Leia-Python3\portable_data\addons\weather.ozweather\default.py", line 35, in <module>
                                                from weatherzone import *
                                              File "C:\Kodi\Leia-Python3\portable_data\addons\weather.ozweather\resources\lib\weatherzone.py", line 20, in <module>
                                                from bs4 import BeautifulSoup
                                              File "C:\Kodi\Leia-Python3\portable_data\addons\script.module.beautifulsoup4\lib\bs4\__init__.py", line 36, in <module>
                                                from .builder import builder_registry, ParserRejectedMarkup
                                              File "C:\Kodi\Leia-Python3\portable_data\addons\script.module.beautifulsoup4\lib\bs4\builder\__init__.py", line 7, in <module>
                                                from bs4.element import (
                                              File "C:\Kodi\Leia-Python3\portable_data\addons\script.module.beautifulsoup4\lib\bs4\element.py", line 13, in <module>
                                                from bs4.dammit import EntitySubstitution
                                              File "C:\Kodi\Leia-Python3\portable_data\addons\script.module.beautifulsoup4\lib\bs4\dammit.py", line 14, in <module>
                                                from htmlentitydefs import codepoint2name
                                            ModuleNotFoundError: No module named 'htmlentitydefs'
                                            -->End of Python script error report<--

```

Luckily, I can workaround this bug by installing [script.module.beautifulsoup4-4.6.3.zip](http://mirrors.kodi.tv/addons/migration/script.module.beautifulsoup4/script.module.beautifulsoup4-4.6.3.zip) manually from zip.

**Comment by peak3d** [comment]
@mediaminister there is a patch now for dlfcn_win32 in inputstream.adaptive master branch

**Comment by mediaminister** [comment]
@peak3d Thanks, I'll test.
