### ISSUE TITLE
headless Ubuntu 18.04: "ERROR: Unable to create GUI. Exiting", then core dump

### ISSUE THREAD

**Issue by sanderjo** [xbmc/xbmc#16648]
### Describe the bug
Starting kodi on Ubuntu Server (no X) leads to:
```
sander@brixit:~$ kodi
ERROR: Unable to create GUI. Exiting
double free or corruption (out)
Aborted (core dumped)
Crash report available at /home/sander/kodi_crashlog-20190921_102252.log
sander@brixit:~$ 
```

## Expected Behavior

I would expect kodi to run or give an error message, but not a core dump

## Actual Behavior

```
sander@brixit:~$ kodi
ERROR: Unable to create GUI. Exiting
double free or corruption (out)
Aborted (core dumped)
Crash report available at /home/sander/kodi_crashlog-20190921_102252.log
```

## Possible Fix

This is a headless Ubuntu ... so maybe installing X will help.

### To Reproduce

1. Install Ubuntu Server
2. Install kodi
3. start kodi

### Debuglog

The debuglog can be found here:

```
################# LOG FILE ##################

10:21:58.284 T:140272553381824  NOTICE: special://profile/ is mapped to: special://masterprofile/
10:21:58.284 T:140272553381824  NOTICE: -----------------------------------------------------------------------
10:21:58.284 T:140272553381824  NOTICE: Starting Kodi from Debian (17.6 Debian package version: 2:17.6+dfsg1-1ubuntu1). Platform: Linux x86 64-bit
10:21:58.284 T:140272553381824  NOTICE: Using Release Kodi from Debian x64 build
10:21:58.284 T:140272553381824  NOTICE: Kodi from Debian compiled from 2:17.6+dfsg1-1ubuntu1 by GCC 6.4.0 for Linux x86 64-bit version 4.15.15 (265999)
10:21:58.284 T:140272553381824  NOTICE: Running on Ubuntu 18.04.3 LTS, kernel: Linux x86 64-bit version 4.15.0-58-generic
10:21:58.284 T:140272553381824  NOTICE: FFmpeg version/source: 3.4.6-0ubuntu0.18.04.1
10:21:58.284 T:140272553381824  NOTICE: Host CPU: Intel(R) Celeron(R) J4105 CPU @ 1.50GHz, 4 cores available
10:21:58.284 T:140272553381824  NOTICE: special://xbmc/ is mapped to: /usr/share/kodi
10:21:58.284 T:140272553381824  NOTICE: special://xbmcbin/ is mapped to: /usr/lib/x86_64-linux-gnu/kodi
10:21:58.284 T:140272553381824  NOTICE: special://xbmcbinaddons/ is mapped to: /usr/lib/x86_64-linux-gnu/kodi/addons
10:21:58.284 T:140272553381824  NOTICE: special://masterprofile/ is mapped to: /home/sander/.kodi/userdata
10:21:58.284 T:140272553381824  NOTICE: special://envhome/ is mapped to: /home/sander
10:21:58.284 T:140272553381824  NOTICE: special://home/ is mapped to: /home/sander/.kodi
10:21:58.284 T:140272553381824  NOTICE: special://temp/ is mapped to: /home/sander/.kodi/temp
10:21:58.284 T:140272553381824  NOTICE: special://logpath/ is mapped to: /home/sander/.kodi/temp
10:21:58.284 T:140272553381824  NOTICE: The executable running is: /usr/lib/x86_64-linux-gnu/kodi/kodi.bin
10:21:58.284 T:140272553381824  NOTICE: Local hostname: brixit
10:21:58.284 T:140272553381824  NOTICE: Log File is located: /home/sander/.kodi/temp//kodi.log
10:21:58.284 T:140272553381824  NOTICE: -----------------------------------------------------------------------
10:21:58.293 T:140272553381824   ERROR: DBus: Error org.freedesktop.DBus.Error.ServiceUnknown - The name org.freedesktop.UPower was not provided by any .service files
10:21:58.333 T:140272553381824  NOTICE: load settings...
10:21:58.353 T:140272553381824   ERROR: PulseAudio: Failed to connect context
10:21:58.353 T:140272553381824  NOTICE: PulseAudio might not be running. Context was not created.
10:21:58.359 T:140272553381824  NOTICE: No Devices found - retry: 4
10:21:59.868 T:140272553381824   ERROR: PulseAudio: Failed to connect context
10:21:59.868 T:140272553381824  NOTICE: PulseAudio might not be running. Context was not created.
10:21:59.876 T:140272553381824  NOTICE: No Devices found - retry: 3
10:22:01.380 T:140272553381824   ERROR: PulseAudio: Failed to connect context
10:22:01.380 T:140272553381824  NOTICE: PulseAudio might not be running. Context was not created.
10:22:01.387 T:140272553381824  NOTICE: No Devices found - retry: 2
10:22:02.897 T:140272553381824   ERROR: PulseAudio: Failed to connect context
10:22:02.897 T:140272553381824  NOTICE: PulseAudio might not be running. Context was not created.
10:22:02.906 T:140272553381824  NOTICE: No Devices found - retry: 1
10:22:04.415 T:140272553381824   ERROR: PulseAudio: Failed to connect context
10:22:04.415 T:140272553381824  NOTICE: PulseAudio might not be running. Context was not created.
10:22:04.425 T:140272553381824  NOTICE: Found 0 Lists of Devices
10:22:04.429 T:140272553381824   ERROR: PulseAudio: Failed to connect context
10:22:04.429 T:140272553381824  NOTICE: PulseAudio might not be running. Context was not created.
10:22:04.434 T:140272553381824  NOTICE: No Devices found - retry: 4
10:22:05.941 T:140272553381824   ERROR: PulseAudio: Failed to connect context
10:22:05.941 T:140272553381824  NOTICE: PulseAudio might not be running. Context was not created.
10:22:05.949 T:140272553381824  NOTICE: No Devices found - retry: 3
10:22:07.459 T:140272553381824   ERROR: PulseAudio: Failed to connect context
10:22:07.459 T:140272553381824  NOTICE: PulseAudio might not be running. Context was not created.
10:22:07.467 T:140272553381824  NOTICE: No Devices found - retry: 2
10:22:08.976 T:140272553381824   ERROR: PulseAudio: Failed to connect context
10:22:08.976 T:140272553381824  NOTICE: PulseAudio might not be running. Context was not created.
10:22:08.986 T:140272553381824  NOTICE: No Devices found - retry: 1
10:22:10.496 T:140272553381824   ERROR: PulseAudio: Failed to connect context
10:22:10.496 T:140272553381824  NOTICE: PulseAudio might not be running. Context was not created.
10:22:10.504 T:140272553381824  NOTICE: Found 0 Lists of Devices
10:22:10.508 T:140272553381824  NOTICE: No settings file to load (special://xbmc/system/advancedsettings.xml)
10:22:10.508 T:140272553381824  NOTICE: No settings file to load (special://masterprofile/advancedsettings.xml)
10:22:10.508 T:140272553381824  NOTICE: Default Video Player: VideoPlayer
10:22:10.508 T:140272553381824  NOTICE: Default Audio Player: paplayer
10:22:10.508 T:140272553381824  NOTICE: Disabled debug logging due to GUI setting. Level 0.
10:22:10.508 T:140272553381824  NOTICE: Log level changed to "LOG_LEVEL_NORMAL"
10:22:10.508 T:140272553381824  NOTICE: Loading player core factory settings from special://xbmc/system/playercorefactory.xml.
10:22:10.508 T:140272553381824  NOTICE: Loaded playercorefactory configuration
10:22:10.509 T:140272553381824  NOTICE: Loading player core factory settings from special://masterprofile/playercorefactory.xml.
10:22:10.509 T:140272553381824  NOTICE: special://masterprofile/playercorefactory.xml does not exist. Skipping.
08:22:10.514 T:140272553381824  NOTICE: Running database version Addons27
08:22:10.560 T:140272553381824  NOTICE: ADDONS: Using repository repository.xbmc.org
08:22:10.568 T:140271006246656   ERROR: PulseAudio: Failed to connect context
08:22:10.568 T:140271006246656  NOTICE: PulseAudio might not be running. Context was not created.
08:22:10.575 T:140271006246656  NOTICE: No Devices found - retry: 4
08:22:12.086 T:140271006246656   ERROR: PulseAudio: Failed to connect context
08:22:12.086 T:140271006246656  NOTICE: PulseAudio might not be running. Context was not created.
08:22:12.094 T:140271006246656  NOTICE: No Devices found - retry: 3
08:22:13.604 T:140271006246656   ERROR: PulseAudio: Failed to connect context
08:22:13.604 T:140271006246656  NOTICE: PulseAudio might not be running. Context was not created.
08:22:13.613 T:140271006246656  NOTICE: No Devices found - retry: 2
08:22:15.122 T:140271006246656   ERROR: PulseAudio: Failed to connect context
08:22:15.122 T:140271006246656  NOTICE: PulseAudio might not be running. Context was not created.
08:22:15.131 T:140271006246656  NOTICE: No Devices found - retry: 1
08:22:16.641 T:140271006246656   ERROR: PulseAudio: Failed to connect context
08:22:16.641 T:140271006246656  NOTICE: PulseAudio might not be running. Context was not created.
08:22:16.651 T:140271006246656  NOTICE: Found 0 Lists of Devices
08:22:16.654 T:140271006246656 WARNING: ActiveAE::Configure - sink returned large buffer of 249 ms, reducing to 100 ms
08:22:16.666 T:140272553381824   ERROR: X11 Error: No Display found
08:22:16.666 T:140272553381824   FATAL: CApplication::Create: Unable to init windowing system


############### END LOG FILE ################

```

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic
```
 - Kodi version:

```
$ kodi --version
17.6 Debian package version: 2:17.6+dfsg1-1ubuntu1 Media Center Kodi from Debian
Copyright (C) 2005-2013 Team Kodi from Debian - http://kodi.tv
```

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by sanderjo** [comment]
Full /home/sander/kodi_crashlog-20190921_102252.log
```
############## Kodi CRASH LOG ###############

################ SYSTEM INFO ################
 Date: Sat Sep 21 10:22:52 CEST 2019
 Kodi Options: 
 Arch: x86_64
 Kernel: Linux 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019
 Release: Ubuntu 18.04.3 LTS (Bionic Beaver)
############## END SYSTEM INFO ##############

############### STACK TRACE #################
=====>  Core file: /home/sander/core (2019-09-21 10:22:52.225173121 +0200)
        =========================================
[New LWP 4640]
[New LWP 4707]
[New LWP 4641]
[New LWP 4643]
[New LWP 4708]
[New LWP 4740]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/lib/x86_64-linux-gnu/kodi/kodi.bin'.
Program terminated with signal SIGABRT, Aborted.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
[Current thread is 1 (Thread 0x7f93bfb74fc0 (LWP 4640))]

Thread 6 (Thread 0x7f93627fc700 (LWP 4740)):
#0  0x00007f93b63589d0 in __GI___nanosleep (requested_time=requested_time@entry=0x7f93627fb550, remaining=remaining@entry=0x0) at ../sysdeps/unix/sysv/linux/nanosleep.c:28
#1  0x00007f93b638b877 in usleep (useconds=<optimized out>) at ../sysdeps/posix/usleep.c:32
#2  0x000055e7ac6c308f in CAESinkNULL::Process() ()
#3  0x000055e7acfaef3f in CThread::Action() ()
#4  0x000055e7acfaf1ff in CThread::staticThread(void*) ()
#5  0x00007f93be72e6db in start_thread (arg=0x7f93627fc700) at pthread_create.c:463
#6  0x00007f93b639588f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 5 (Thread 0x7f9362ffd700 (LWP 4708)):
#0  0x00007f93be734f85 in futex_abstimed_wait_cancelable (private=<optimized out>, abstime=0x7f9362ffc250, expected=0, futex_word=0x55e7ae5d14e0) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
#1  __pthread_cond_wait_common (abstime=0x7f9362ffc250, mutex=0x55e7ae5d14f8, cond=0x55e7ae5d14b8) at pthread_cond_wait.c:539
#2  __pthread_cond_timedwait (cond=0x55e7ae5d14b8, mutex=0x55e7ae5d14f8, abstime=0x7f9362ffc250) at pthread_cond_wait.c:667
#3  0x000055e7acfaee4d in CThread::Sleep(unsigned int) ()
#4  0x000055e7ac68e6fc in ActiveAE::CActiveAESink::OutputSamples(ActiveAE::CSampleBuffer*) ()
#5  0x000055e7ac68fd42 in ActiveAE::CActiveAESink::StateMachine(int, Actor::Protocol*, Actor::Message*) ()
#6  0x000055e7ac6908e7 in ActiveAE::CActiveAESink::Process() ()
#7  0x000055e7acfaef3f in CThread::Action() ()
#8  0x000055e7acfaf1ff in CThread::staticThread(void*) ()
#9  0x00007f93be72e6db in start_thread (arg=0x7f9362ffd700) at pthread_create.c:463
#10 0x00007f93b639588f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 4 (Thread 0x7f9394ea0700 (LWP 4643)):
#0  0x00007f93b6388bf9 in __GI___poll (fds=0x55e7ae5d7bf0, nfds=2, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x000055e7acc95f91 in CFDEventMonitor::Process() ()
#2  0x000055e7acfaef3f in CThread::Action() ()
#3  0x000055e7acfaf1ff in CThread::staticThread(void*) ()
#4  0x00007f93be72e6db in start_thread (arg=0x7f9394ea0700) at pthread_create.c:463
#5  0x00007f93b639588f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 3 (Thread 0x7f93956a1700 (LWP 4641)):
#0  0x00007f93be7349f3 in futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x55e7ae5c5d50) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
#1  __pthread_cond_wait_common (abstime=0x0, mutex=0x55e7ae5c5d68, cond=0x55e7ae5c5d28) at pthread_cond_wait.c:502
#2  __pthread_cond_wait (cond=0x55e7ae5c5d28, mutex=0x55e7ae5c5d68) at pthread_cond_wait.c:655
#3  0x000055e7ac85f229 in ANNOUNCEMENT::CAnnouncementManager::Process() ()
#4  0x000055e7acfaef3f in CThread::Action() ()
#5  0x000055e7acfaf1ff in CThread::staticThread(void*) ()
#6  0x00007f93be72e6db in start_thread (arg=0x7f93956a1700) at pthread_create.c:463
#7  0x00007f93b639588f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 2 (Thread 0x7f93637fe700 (LWP 4707)):
#0  0x00007f93be734f85 in futex_abstimed_wait_cancelable (private=<optimized out>, abstime=0x7f93637fd590, expected=0, futex_word=0x55e7ae5d10dc) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
#1  __pthread_cond_wait_common (abstime=0x7f93637fd590, mutex=0x55e7ae5d10f0, cond=0x55e7ae5d10b0) at pthread_cond_wait.c:539
#2  __pthread_cond_timedwait (cond=0x55e7ae5d10b0, mutex=0x55e7ae5d10f0, abstime=0x7f93637fd590) at pthread_cond_wait.c:667
#3  0x000055e7ac68bf17 in ActiveAE::CActiveAE::Process() ()
#4  0x000055e7acfaef3f in CThread::Action() ()
#5  0x000055e7acfaf1ff in CThread::staticThread(void*) ()
#6  0x00007f93be72e6db in start_thread (arg=0x7f93637fe700) at pthread_create.c:463
#7  0x00007f93b639588f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 1 (Thread 0x7f93bfb74fc0 (LWP 4640)):
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007f93b62b4801 in __GI_abort () at abort.c:79
#2  0x00007f93b62fd897 in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7f93b642ab9a "%s\n") at ../sysdeps/posix/libc_fatal.c:181
#3  0x00007f93b630490a in malloc_printerr (str=str@entry=0x7f93b642c870 "double free or corruption (out)") at malloc.c:5350
#4  0x00007f93b630be75 in _int_free (have_lock=0, p=0x55e7ae8992c0, av=0x7f93b665fc40 <main_arena>) at malloc.c:4278
#5  __GI___libc_free (mem=0x55e7ae8992d0) at malloc.c:3124
#6  0x000055e7acd34b59 in std::_Rb_tree<int, std::pair<int const, RssSet>, std::_Select1st<std::pair<int const, RssSet> >, std::less<int>, std::allocator<std::pair<int const, RssSet> > >::_M_erase(std::_Rb_tree_node<std::pair<int const, RssSet> >*) ()
#7  0x000055e7acd33f89 in CRssManager::Clear() ()
#8  0x000055e7aca80d81 in CSettingsManager::OnSettingsUnloaded() ()
#9  0x000055e7aca81a53 in CSettingsManager::Unload() ()
#10 0x000055e7aca84bbe in CSettingsManager::Clear() ()
#11 0x000055e7ac3d5dc1 in CSettings::Uninitialize() ()
#12 0x000055e7ac3d680f in CSettings::~CSettings() ()
#13 0x00007f93b62b7041 in __run_exit_handlers (status=-1, listp=0x7f93b665f718 <__exit_funcs>, run_list_atexit=run_list_atexit@entry=true, run_dtors=run_dtors@entry=true) at exit.c:108
#14 0x00007f93b62b713a in __GI_exit (status=<optimized out>) at exit.c:139
#15 0x00007f93b6295b9e in __libc_start_main (main=0x55e7ac3521b0 <main>, argc=1, argv=0x7ffce25987f8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffce25987e8) at ../csu/libc-start.c:344
#16 0x000055e7ac3b835a in _start ()
############# END STACK TRACE ###############

################# LOG FILE ##################

10:21:58.284 T:140272553381824  NOTICE: special://profile/ is mapped to: special://masterprofile/
10:21:58.284 T:140272553381824  NOTICE: -----------------------------------------------------------------------
10:21:58.284 T:140272553381824  NOTICE: Starting Kodi from Debian (17.6 Debian package version: 2:17.6+dfsg1-1ubuntu1). Platform: Linux x86 64-bit
10:21:58.284 T:140272553381824  NOTICE: Using Release Kodi from Debian x64 build
10:21:58.284 T:140272553381824  NOTICE: Kodi from Debian compiled from 2:17.6+dfsg1-1ubuntu1 by GCC 6.4.0 for Linux x86 64-bit version 4.15.15 (265999)
10:21:58.284 T:140272553381824  NOTICE: Running on Ubuntu 18.04.3 LTS, kernel: Linux x86 64-bit version 4.15.0-58-generic
10:21:58.284 T:140272553381824  NOTICE: FFmpeg version/source: 3.4.6-0ubuntu0.18.04.1
10:21:58.284 T:140272553381824  NOTICE: Host CPU: Intel(R) Celeron(R) J4105 CPU @ 1.50GHz, 4 cores available
10:21:58.284 T:140272553381824  NOTICE: special://xbmc/ is mapped to: /usr/share/kodi
10:21:58.284 T:140272553381824  NOTICE: special://xbmcbin/ is mapped to: /usr/lib/x86_64-linux-gnu/kodi
10:21:58.284 T:140272553381824  NOTICE: special://xbmcbinaddons/ is mapped to: /usr/lib/x86_64-linux-gnu/kodi/addons
10:21:58.284 T:140272553381824  NOTICE: special://masterprofile/ is mapped to: /home/sander/.kodi/userdata
10:21:58.284 T:140272553381824  NOTICE: special://envhome/ is mapped to: /home/sander
10:21:58.284 T:140272553381824  NOTICE: special://home/ is mapped to: /home/sander/.kodi
10:21:58.284 T:140272553381824  NOTICE: special://temp/ is mapped to: /home/sander/.kodi/temp
10:21:58.284 T:140272553381824  NOTICE: special://logpath/ is mapped to: /home/sander/.kodi/temp
10:21:58.284 T:140272553381824  NOTICE: The executable running is: /usr/lib/x86_64-linux-gnu/kodi/kodi.bin
10:21:58.284 T:140272553381824  NOTICE: Local hostname: brixit
10:21:58.284 T:140272553381824  NOTICE: Log File is located: /home/sander/.kodi/temp//kodi.log
10:21:58.284 T:140272553381824  NOTICE: -----------------------------------------------------------------------
10:21:58.293 T:140272553381824   ERROR: DBus: Error org.freedesktop.DBus.Error.ServiceUnknown - The name org.freedesktop.UPower was not provided by any .service files
10:21:58.333 T:140272553381824  NOTICE: load settings...
10:21:58.353 T:140272553381824   ERROR: PulseAudio: Failed to connect context
10:21:58.353 T:140272553381824  NOTICE: PulseAudio might not be running. Context was not created.
10:21:58.359 T:140272553381824  NOTICE: No Devices found - retry: 4
10:21:59.868 T:140272553381824   ERROR: PulseAudio: Failed to connect context
10:21:59.868 T:140272553381824  NOTICE: PulseAudio might not be running. Context was not created.
10:21:59.876 T:140272553381824  NOTICE: No Devices found - retry: 3
10:22:01.380 T:140272553381824   ERROR: PulseAudio: Failed to connect context
10:22:01.380 T:140272553381824  NOTICE: PulseAudio might not be running. Context was not created.
10:22:01.387 T:140272553381824  NOTICE: No Devices found - retry: 2
10:22:02.897 T:140272553381824   ERROR: PulseAudio: Failed to connect context
10:22:02.897 T:140272553381824  NOTICE: PulseAudio might not be running. Context was not created.
10:22:02.906 T:140272553381824  NOTICE: No Devices found - retry: 1
10:22:04.415 T:140272553381824   ERROR: PulseAudio: Failed to connect context
10:22:04.415 T:140272553381824  NOTICE: PulseAudio might not be running. Context was not created.
10:22:04.425 T:140272553381824  NOTICE: Found 0 Lists of Devices
10:22:04.429 T:140272553381824   ERROR: PulseAudio: Failed to connect context
10:22:04.429 T:140272553381824  NOTICE: PulseAudio might not be running. Context was not created.
10:22:04.434 T:140272553381824  NOTICE: No Devices found - retry: 4
10:22:05.941 T:140272553381824   ERROR: PulseAudio: Failed to connect context
10:22:05.941 T:140272553381824  NOTICE: PulseAudio might not be running. Context was not created.
10:22:05.949 T:140272553381824  NOTICE: No Devices found - retry: 3
10:22:07.459 T:140272553381824   ERROR: PulseAudio: Failed to connect context
10:22:07.459 T:140272553381824  NOTICE: PulseAudio might not be running. Context was not created.
10:22:07.467 T:140272553381824  NOTICE: No Devices found - retry: 2
10:22:08.976 T:140272553381824   ERROR: PulseAudio: Failed to connect context
10:22:08.976 T:140272553381824  NOTICE: PulseAudio might not be running. Context was not created.
10:22:08.986 T:140272553381824  NOTICE: No Devices found - retry: 1
10:22:10.496 T:140272553381824   ERROR: PulseAudio: Failed to connect context
10:22:10.496 T:140272553381824  NOTICE: PulseAudio might not be running. Context was not created.
10:22:10.504 T:140272553381824  NOTICE: Found 0 Lists of Devices
10:22:10.508 T:140272553381824  NOTICE: No settings file to load (special://xbmc/system/advancedsettings.xml)
10:22:10.508 T:140272553381824  NOTICE: No settings file to load (special://masterprofile/advancedsettings.xml)
10:22:10.508 T:140272553381824  NOTICE: Default Video Player: VideoPlayer
10:22:10.508 T:140272553381824  NOTICE: Default Audio Player: paplayer
10:22:10.508 T:140272553381824  NOTICE: Disabled debug logging due to GUI setting. Level 0.
10:22:10.508 T:140272553381824  NOTICE: Log level changed to "LOG_LEVEL_NORMAL"
10:22:10.508 T:140272553381824  NOTICE: Loading player core factory settings from special://xbmc/system/playercorefactory.xml.
10:22:10.508 T:140272553381824  NOTICE: Loaded playercorefactory configuration
10:22:10.509 T:140272553381824  NOTICE: Loading player core factory settings from special://masterprofile/playercorefactory.xml.
10:22:10.509 T:140272553381824  NOTICE: special://masterprofile/playercorefactory.xml does not exist. Skipping.
08:22:10.514 T:140272553381824  NOTICE: Running database version Addons27
08:22:10.560 T:140272553381824  NOTICE: ADDONS: Using repository repository.xbmc.org
08:22:10.568 T:140271006246656   ERROR: PulseAudio: Failed to connect context
08:22:10.568 T:140271006246656  NOTICE: PulseAudio might not be running. Context was not created.
08:22:10.575 T:140271006246656  NOTICE: No Devices found - retry: 4
08:22:12.086 T:140271006246656   ERROR: PulseAudio: Failed to connect context
08:22:12.086 T:140271006246656  NOTICE: PulseAudio might not be running. Context was not created.
08:22:12.094 T:140271006246656  NOTICE: No Devices found - retry: 3
08:22:13.604 T:140271006246656   ERROR: PulseAudio: Failed to connect context
08:22:13.604 T:140271006246656  NOTICE: PulseAudio might not be running. Context was not created.
08:22:13.613 T:140271006246656  NOTICE: No Devices found - retry: 2
08:22:15.122 T:140271006246656   ERROR: PulseAudio: Failed to connect context
08:22:15.122 T:140271006246656  NOTICE: PulseAudio might not be running. Context was not created.
08:22:15.131 T:140271006246656  NOTICE: No Devices found - retry: 1
08:22:16.641 T:140271006246656   ERROR: PulseAudio: Failed to connect context
08:22:16.641 T:140271006246656  NOTICE: PulseAudio might not be running. Context was not created.
08:22:16.651 T:140271006246656  NOTICE: Found 0 Lists of Devices
08:22:16.654 T:140271006246656 WARNING: ActiveAE::Configure - sink returned large buffer of 249 ms, reducing to 100 ms
08:22:16.666 T:140272553381824   ERROR: X11 Error: No Display found
08:22:16.666 T:140272553381824   FATAL: CApplication::Create: Unable to init windowing system


############### END LOG FILE ################

############ END Kodi CRASH LOG #############

```

**Comment by fritsch** [comment]
Not a bug, please properly configure your X-Server. If you run on wayland, install the kodi wayland package instead

```
08:22:16.666 T:140272553381824   ERROR: X11 Error: No Display found
08:22:16.666 T:140272553381824   FATAL: CApplication::Create: Unable to init windowing system
```
