### ISSUE TITLE
Emby Helper Error on a RPI4 using Buster

### ISSUE THREAD

**Issue by freebs65** [xbmc/xbmc#17071]
### Describe the bug
Here is a clear and concise description of what the problem is:

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:
2019-12-23 09:20:02.768 T:1985974480   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.RuntimeError'>
                                            Error Contents: implement_array_function method already has a docstring
                                            Traceback (most recent call last):
                                              File "/home/xbmc/.kodi/addons/script.embuary.helper/plugin.py", line 16, in <module>
                                                from resources.lib.plugin_content import *
                                              File "/home/xbmc/.kodi/addons/script.embuary.helper/resources/lib/plugin_content.py", line 11, in <module>
                                                from resources.lib.image import *
                                              File "/home/xbmc/.kodi/addons/script.embuary.helper/resources/lib/image.py", line 12, in <module>
                                                from PIL import ImageFilter,Image,ImageOps
                                              File "/usr/lib/python2.7/dist-packages/PIL/ImageFilter.py", line 23, in <module>
                                                import numpy
                                              File "/usr/lib/python2.7/dist-packages/numpy/__init__.py", line 142, in <module>
                                                from . import core
                                              File "/usr/lib/python2.7/dist-packages/numpy/core/__init__.py", line 40, in <module>
                                                from . import multiarray
                                              File "/usr/lib/python2.7/dist-packages/numpy/core/multiarray.py", line 12, in <module>
                                                from . import overrides
                                              File "/usr/lib/python2.7/dist-packages/numpy/core/overrides.py", line 46, in <module>
                                                """)
                                            RuntimeError: implement_array_function method already has a docstring
                                            -->End of Python script error report<--
2019-12-23 09:20:03.018 T:2566770896  NOTICE: EMBY.entrypoint.service -> [ onNotification/plugin.video.emby/UserDataChanged ]
2019-12-23 09:20:03.023 T:2566770896  NOTICE: EMBY.entrypoint.service -> [ UserDataChanged ] {u'UserId': u'c1f5da8c23934012835b5e2bfe5e1625', u'UserDataList': [{u'ItemId': u'168304', u'IsFavorite': False, u'Played': True, u'PlayedPercentage': 46.1815044534537, u'LastPlayedDate': u'2019-12-23T14:18:16.0000000+00:00', u'PlaybackPositionTicks': 1030000000, u'PlayCount': 16}, {u'ItemId': u'168269', u'PlayCount': 0, u'PlaybackPositionTicks': 0, u'IsFavorite': False, u'Played': False}]}
2019-12-23 09:20:03.024 T:2566770896  NOTICE: EMBY.library -> ---[ userdata:2 ]
2019-12-23 09:20:03.026 T:1994367184   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.RuntimeError'>
                                            Error Contents: implement_array_function method already has a docstring
                                            Traceback (most recent call last):
                                              File "/home/xbmc/.kodi/addons/script.embuary.helper/plugin.py", line 16, in <module>
                                                from resources.lib.plugin_content import *
                                              File "/home/xbmc/.kodi/addons/script.embuary.helper/resources/lib/plugin_content.py", line 11, in <module>
                                                from resources.lib.image import *
                                              File "/home/xbmc/.kodi/addons/script.embuary.helper/resources/lib/image.py", line 12, in <module>
                                                from PIL import ImageFilter,Image,ImageOps
                                              File "/usr/lib/python2.7/dist-packages/PIL/ImageFilter.py", line 23, in <module>
                                                import numpy
                                              File "/usr/lib/python2.7/dist-packages/numpy/__init__.py", line 142, in <module>
                                                from . import core
                                              File "/usr/lib/python2.7/dist-packages/numpy/core/__init__.py", line 40, in <module>
                                                from . import multiarray
                                              File "/usr/lib/python2.7/dist-packages/numpy/core/multiarray.py", line 12, in <module>
                                                from . import overrides
                                              File "/usr/lib/python2.7/dist-packages/numpy/core/overrides.py", line 46, in <module>
                                                """)
                                            RuntimeError: implement_array_function method already has a docstring
                                            -->End of Python script error report<--

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [x ] Raspberry-Pi4
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:Debian Buster
 - Kodi version:18.4

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by KarellenX** [comment]
Incomplete report

**Comment by freebs65** [comment]
such BS..

**Comment by KarellenX** [comment]
What are we supposed to look at in your report? 

You seriously could not even provide a brief description on what the problem is??

If you have a problem with an add-on, then contact the author of the add-on.
