### ISSUE TITLE
Python- AttributeError: 'datetime.timedelta' object has no attribute 'tzinfo'

### ISSUE THREAD

**Issue by KarellenX** [xbmc/xbmc#17311]
### Describe the bug
This issue has been discussed extensively in # scraping and # python Slack channels and is well known by @Razzeee and @Paxxi 

Razzeee has created a Python scraper for TVDB. I undertook testing of the scraper but I was constantly plagued with bad and failed scrapes, Python errors and Kodi crashing back to desktop.

The addons installed for the testing phase are the following...
https://github.com/xbmc/metadata.tvdb.com.python
https://github.com/xbmc/script.module.tvdbsimple
https://github.com/Razzeee/script.module.arrow
https://github.com/Razzeee/script.module.dateutil
https://github.com/Razzeee/script.module.six

The developers should be able to diagnose the issue better than I, but it seems the issue is caused by the following
`AttributeError: 'datetime.timedelta' object has no attribute 'tzinfo'`

The issue has also been reported on the forum here...
https://forum.kodi.tv/showthread.php?tid=350319

Razzeee has also reported the issue to the arrow developer here...
https://github.com/crsmithdev/arrow/issues/738

## Expected Behavior
To scrape tv shows accurately without errors, malformed data and crashing.

## Actual Behavior
Scraping with the new Python TVDB scraper is unreliable and causes crashing of Kodi

## Possible Fix
Unknown

### To Reproduce
1. Install the above add-ons. I use Windows 10 and Kodi v19
2. Attempt to scrape a few shows
3.

### Debuglog
Multiple debug logs have been provided over the last couple of months, but this is the most recent...
Errors start at Line 1296... https://paste.kodi.tv/esanotirig.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name:
**Running on Windows 10, kernel: Windows NT x86 64-bit version 10.0.18363**
**Host CPU: Intel(R) Core(TM) i7-3770K CPU @ 3.50GHz, 8 cores available**
**Desktop Resolution: 1920x1080 32Bit at 60Hz**

 - Kodi version:
**Starting Kodi (19.0-ALPHA1 Git:20200201-bc3d65b4ab). Platform: Windows NT x86 64-bit**

**Comment by yol** [comment]
@KarellenX sorry if I'm late to the party - can you upload your set of test files (just the names, content can be empty)? did you try on Linux?

**Comment by Paxxi** [comment]
This is a tricky one. It seems to be very reliably reproducible for @KarellenX and I  belive @sarbes also had a reliable repro. I've tried to reproduce it with their steps both in debug and release builds and have not managed to.

Inspecting the code there is nothing that seems to indicate use of shared globals or other patterns that is noticeable. The setup code for the min/max globals use member variables so they shouldn't be susceptible to race conditions.

From the python side trying to assign to min/max throws an error.

Any help in getting a portable reproduction would be great.

**Comment by yol** [comment]
@Paxxi I'm suspecting a race in our Python handling of sub-interpreters, GIL, etc...

Also: https://docs.python.org/3/c-api/init.html#bugs-and-caveats

**Comment by Paxxi** [comment]
> @Paxxi I'm suspecting a race in our Python handling of sub-interpreters, GIL, etc...
> 
> Also: https://docs.python.org/3/c-api/init.html#bugs-and-caveats

Yeah the top crash on windows have always been python threading issues 😀
The thing is that I can't see a race condition in this init code https://github.com/Paxxi/cpython/blob/df45a3248236c7676f3c53444015889b8ea16057/Modules/_datetimemodule.c#L6283

**Comment by KarellenX** [comment]
Sorry @yol  Somehow I missed your post.

Since @Razzeee updated the scraper to v1.0.0 recently and also the nfo file fix I reported a few days ago, the issue has changed for me.

I have been trying to replicate the conditions that cause the error, but every time I think I figured out the steps, it won't error the second or third time. 

I no longer encounter errors or crashing when **scraping** tv shows. I have repeated the tests 9 times since writing this Issue.

The problem is now encountered when scanning nfo files. But I cannot reliably replicate the problem. Sometimes it will crash on the first show, sometimes on the second, other times I can scan the entire source of 62 shows and 1250 episodes with only one or two unrelated python errors. 

Not sure if it is of any help. but the first show in that source is 3%... https://www.thetvdb.com/series/3-1
The scraper either completely misidentifies this show or it errors on it. Maybe the % sign is the problem? 

So I can send you the dummy files I use, but I have not figured out a way to reliably cause the crash and which files to send you.

**Comment by I-Cat** [comment]
The Kodi language strings are ASCII and the JSON data is UTF-8 - so is trying to convert the UTF-8 to ASCI ?? 

Aslo It looks lie the api Has changed ?

**Comment by yol** [comment]
@I-Cat please don't hijack this issue for off-topic conversation. thank you.

**Comment by yol** [comment]
Hrm. I don't think the test files are going to help then.

@Paxxi The race is probably not in the Python code per se, but rather how we initialize/use multiple interpreters. As the documentation says, multiple interpreters may use shared global module variables. If, for example, `datetime.min` refers to the same memory in multiple threads (no idea whether this is really case btw) but initialized by different ones simultaneously, that might invite some odd behavior.

I wonder if we could do some kind of stress-test add-on that just spawns hundreds of interpreters in parallel and imports some random modules (or just `datetime`) so we see whether this causes some issues.

**Comment by KarellenX** [comment]
Is there something I can install locally to record and document more details in the error?

**Comment by Paxxi** [comment]
@yol I understand that but those are only initialized once and not for every interpreter. Even with race conditions I haven't found a place that writes to datetime that looks susceptible to it.

Look at the datetime init I linked, the method uses local variables for the setup and then writes once to a static global

**Comment by L2501** [comment]
The datetime module in Kodi has been bugged since forever
https://forum.kodi.tv/showthread.php?tid=112916

**Comment by DaVukovic** [comment]
Just came across this as well while testing the Embuary-Info-Script. 

Just want to say that it happens on Linux (Fedora in my case) as well

**Comment by yol** [comment]
@Paxxi Makes sense. Then I have no "obvious" idea how this could happen.

@L2501 That might or might not be related, but thanks for the hint in any case

@DaVukovic Interesting, the problem appears clearly on second invocation of the script. And the interpreter is created in one thread while another one is being destroyed in another thread. This hints at some obscure multithreading/parallelism problem again unfortunately :-/

**Comment by yol** [comment]
@DaVukovic can you reproduce reliably?

**Comment by Paxxi** [comment]
@DaVukovic that's some great news! You just cleared me from breaking Python on Windows when doing the Kodi patches for it 🤣 

@yol stop agreeing with me and start telling me I'm missing something 😄 

The crash is good news as it gives us something to work from at least. I find it interesting that there doesn't appear to be any other python threads executing. Probably some ref counting that's not perfectly synchronized so some object is destroyed prematurely, but that's just a theory after a quick look at the code.

**Comment by DaVukovic** [comment]
> @DaVukovic can you reproduce reliably?

Yes, I can. It's easy to reproduce. As I don't use python scrapers (yet), and I tested something for sualfred, I installed those two add-ons: 

https://github.com/sualfred/script.embuary.info/tree/estuary
and
https://github.com/sualfred/context.embuary.info

after installing them, 
- navigate to a movie or episode entry in your library
- open the context menu and chose the "Info Script" which is mentioned at the bottom
- do that fast and multiple times for different entries 

@Paxxi @yol if you need anything else from my side, feel free to ping me

**Comment by yol** [comment]
@Paxxi if you want to have some fun, run Kodi with clang thread-sanitizer ;-)

**Comment by yol** [comment]
@DaVukovic Unfortunately the repro does not work for me :-/

**Comment by sualfred** [comment]
@yol 
fyi: The script is available in the matrix repo now if you wanna test it with it.

**Comment by yol** [comment]
As said I couldn't reach a reliable repro unfortunately

**Comment by sualfred** [comment]
@yol official Kodi matrix repo.

**Comment by yol** [comment]
@sualfred I don't have problems getting your add-on, it just doesn't trigger the error here

**Comment by sualfred** [comment]
@yol the was getting better in the last nightlies but is still there.
Try to walk the addon nodes and not calling it directly for a DB item. Quickly thru random nodes like "popular movies" and "trending movies". As fast as you can :)

**Comment by yol** [comment]
Stilll unable to reproduce... @sualfred @DaVukovic what Python versions are you on?

**Comment by yol** [comment]
Hi again! I hope you're still with me @sualfred @DaVukovic @KarellenX 

I've made some progress in the direction that the datetime Python module is at fault for not supporting multi-staged init and Python itself also has problems with module loading in subinterpreters not working according to documentation. Anyway, can you try the following?

Add here: https://github.com/xbmc/xbmc/blob/0c9d98851e9e3a0f7eba0ebda19c649fe8a8b1bc/xbmc/interfaces/python/XBPython.cpp#L531

`PyImport_ImportModule("_datetime")`

**Comment by KarellenX** [comment]
Hi @yol 

Yep, still here with you. Do I assume correctly that you were able to replicate the crash?

>Anyway, can you try the following?

Sorry, no idea how to try "the following". If there is a build somewhere, point me to it and I can test it. Hopefully I can still find the addon versions that manifested the problem.

**Comment by yol** [comment]
> Do I assume correctly that you were able to replicate the crash?

Not in Kodi, no. This is based on observations and test code that I did get to crash reliably.

> If there is a build somewhere, point me to it and I can test it. 

I can do a testbuild, but in any case you would first need to replicate the crash again with a recent nightly so we know it's not a fluke

**Comment by sualfred** [comment]
I'm currently not able to reproduce it with the latest nightly or with a slightly older nightly which I was running before.
But this means nothing. This error is mysterious and with some nightlies I was getting the error on each access, on some just randomly and now not getting it at all.

**Comment by KarellenX** [comment]
>I can do a testbuild, but in any case you would first need to replicate the crash again with a recent nightly so we know it's not a fluke

Yes, I can still reproduce 
- Using yesterdays nightly _(19.0-ALPHA3 (18.9.730) Git:20201108-3472c405ac). Platform: Windows NT x86 64-bit_
- Using this old version scraper... https://github.com/xbmc/metadata.tvshows.themoviedb.org.python/releases/tag/v1.1.9%2Bmatrix.1

Log... https://paste.kodi.tv/onosexoben.kodi

**Comment by yol** [comment]
https://mirrors.kodi.tv/test-builds/windows/win64/KodiSetup-20201109-1a475e8b-python-datetime-init-x64.exe

**Comment by yol** [comment]
and as FYI: https://bugs.python.org/issue42298

**Comment by KarellenX** [comment]
Thanks @yol  Unfortunately no change and crash still occurs...

Log... https://paste.kodi.tv/gipofoqoci.kodi

**Comment by yol** [comment]
That would have been too easy after all!

Only thing I can think of now is to merge the Python datetime 2stage init patch lying around in an abandoned PR, but I have zero idea how this works on Windows. Anyone on a non-WIndows platform able to reproduce?

**Comment by sualfred** [comment]
@DaVukovic was/is using Linux afaik.

**Comment by rb0135** [comment]
Hi. Just wanted to report that I am running 0.15.5 (and tried with 1.03) and I have the same as @yol. 

However, I am not running Windows but Ubunutu 20.04 LTS.

Info:
Kodi compiled 2021-02-19 by GCC 9.3.0 for Linux x86 64-bit version 5.4.78 (328782)
Running on Ubuntu 20.04.2 LTS, kernel: Linux x86 64-bit version 5.4.0-562012221313-generic

With version 0.15.5, I get this error (as mentioned above):
AttributeError: 'datetime.timedelta' object has no attribute 'tzinfo'

I upgraded the Arrow to the latest 1.03 and the error changed to:
AttributeError: 'datetime.timedelta' object has no attribute 'timestamp'

As @yol mentioned, a get a crash to the desktop, sometimes after the first error, sometimes after the 2nd.

I only use .nfo files and scrape locally.

**Comment by fuzzard** [comment]
Have any apple mac users been able to replicate this at all?
Only reason i ask, is cpython 3.10 alphas have merged a change regarding multi stage init for CAPI modules (including datetime)
https://github.com/python/cpython/pull/24096
https://bugs.python.org/issue41798

I can quite easily get an apple build running with this to test if theres a change in behaviour. Unfortunately i cant stand up windows builds, and linux uses system provided, so would need someone to run python 3.10a5 or newer on their linux system.

**Comment by gibxxi** [comment]
Using stock Kodi Matrix (19.0) on Windows 10, I'm getting the same error periodically as rb0135:

AttributeError: 'datetime.timedelta' object has no attribute 'timestamp'

The error log has no info regarding which TV show (or episode for that matter) this is falling over on.

**Comment by croneter** [comment]
Importing `arrow` in the PlexKodiConnect Kodi-Add-on, I get many tracebacks like this from the **OTHER** Kodi add-on `script.skin.helper` and `script.skin.helper.backgrounds`:
```
2021-05-24 11:39:25.494 T:31113 WARNING <general>: Skin Helper Backgrounds --> Exception details: Type: ModuleNotFoundError Value: No module named 'PIL' Traceback: Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.skin.helper.backgrounds/resources/lib/wallimages.py", line 24, in <module>
                                                       from PIL import Image
                                                   ModuleNotFoundError: No module named 'PIL'
                                                   
2021-05-24 11:39:25.495 T:31113   ERROR <general>: Skin Helper Backgrounds --> Exception in resources.lib.wallimages ! --> No module named 'PIL'
2021-05-24 11:39:25.561 T:31113 WARNING <general>: Skin Helper Backgrounds --> Exception details: Type: ModuleNotFoundError Value: No module named 'Image' Traceback: Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.skin.helper.backgrounds/resources/lib/wallimages.py", line 24, in <module>
                                                       from PIL import Image
                                                   ModuleNotFoundError: No module named 'PIL'
                                                   
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.skin.helper.backgrounds/resources/lib/wallimages.py", line 32, in <module>
                                                       import Image
                                                   ModuleNotFoundError: No module named 'Image'
```
Removing the `import` arrow in PlexKodiConnect (!!) solves this

**Comment by MarkusEh** [comment]
To provide a workaround for some cases, could you apply the following patch to addons/script.module.arrow/lib/arrow/constants.py?

`--- constants.py_orig   2022-03-01 16:03:29.603964942 +0100`
`+++ constants.py        2022-02-28 22:19:46.113142933 +0100`
`@@ -14,7 +14,7 @@`
`     # Get max timestamp. Works on POSIX-based systems like Linux and macOS,`
`     # but will trigger an OverflowError, ValueError, or OSError on Windows`
`     _MAX_TIMESTAMP = datetime.max.timestamp()`
`-except (OverflowError, ValueError, OSError):  # pragma: no cover`
`+except (OverflowError, ValueError, OSError, AttributeError):  # pragma: no cover`
`     # Fallback for Windows and 32-bit systems if initial max timestamp call fails`
`     # Must get max value of ctime on Windows based on architecture (x32 vs x64)`
`     # https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/ctime-ctime32-ctime64-wctime-wctime32-wctime64`

This will not fix everything, but provide some improvement,  until a better solution is found.

**Comment by manfeed** [comment]
> To provide a workaround for some cases, could you apply the following patch to addons/script.module.arrow/lib/arrow/constants.py?
> 
> This will not fix everything, but provide some improvement, until a better solution is found.

Thanks! I tested with this, but unfortunately I keep having crashes...

**Comment by MarkusEh** [comment]
The patch I provided should fix crashes in addons/script.module.arrow/lib/arrow/constants.py.
It is a workaround only :(
@manfeed , in which file/line do you still see crashes?

**Comment by manfeed** [comment]
I'm not a Python expert, so I can only tell you the behaviour that I get in Kodi. With the original code I was warned in Kodi that an error had produced, and most times I was able to exit Kodi and get the error message from the log. With your workaround Kodi just quits abruptly without any warning. When I go to the log, the last line mentions the addon (script.embuary.info) that uses script.module.arrow...

**Comment by manfeed** [comment]
@MarkusEh 
Today I got an error with your code, but Kodi let me exit and I could retrieve the log message, I hope it helps... thanks!

EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
- NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
Error Type: <class 'AttributeError'>
Error Contents: 'datetime.timedelta' object has no attribute 'toordinal'
Traceback (most recent call last):
File "C:\Matrix2\portable_data\addons\script.embuary.info\plugin.py", line 5, in <module>
from resources.lib.widgets import *
File "C:\Matrix2\portable_data\addons\script.embuary.info\resources\lib\widgets.py", line 11, in <module>
from resources.lib.helper import *
File "C:\Matrix2\portable_data\addons\script.embuary.info\resources\lib\helper.py", line 15, in <module>
import arrow
File "C:\Matrix2\portable_data\addons\script.module.arrow\lib\arrow\__init__.py", line 2, in <module>
from .api import get, now, utcnow
File "C:\Matrix2\portable_data\addons\script.module.arrow\lib\arrow\api.py", line 12, in <module>
from arrow.arrow import TZ_EXPR, Arrow
File "C:\Matrix2\portable_data\addons\script.module.arrow\lib\arrow\arrow.py", line 34, in <module>
from arrow import formatter, locales, parser, util
File "C:\Matrix2\portable_data\addons\script.module.arrow\lib\arrow\parser.py", line 26, in <module>
from arrow.util import next_weekday, normalize_timestamp
File "C:\Matrix2\portable_data\addons\script.module.arrow\lib\arrow\util.py", line 6, in <module>
from arrow.constants import (
File "C:\Matrix2\portable_data\addons\script.module.arrow\lib\arrow\constants.py", line 33, in <module>
MAX_ORDINAL: Final[int] = datetime.max.toordinal()
AttributeError: 'datetime.timedelta' object has no attribute 'toordinal'
-->End of Python script error report<--

**Comment by MarkusEh** [comment]
Hi,

There is a bug in KODI, cause by a bug in python. :(

Options for KODI:

1. Ask python developers to fix (we can try, but this is a well known bug in python and not fixed since years ...)
2. Move from python to another language (theoretical option, added for completeness)
3. Accept to have these bugs permanently in KODI
4. Implement workarounds in KODI

Even if I really hate option 4, it still seems to be the best alternative. Here's the question to the KODI developers: Are you willing to implement workarounds in KODI?

@manfeed , you can try to change the line

MAX_ORDINAL: Final[int] = datetime.max.toordinal()

to

`
MAX_ORDINAL: Final[int] = (
datetime(3000, 1, 1, 23, 59, 59, 999999).toordinal()
 if is_64bits
else datetime(2038, 1, 1, 23, 59, 59, 999999).toordinal()
)
`

**Comment by MarkusEh** [comment]
Complete patch, please apply to addons/script.module.arrow/lib/arrow/constants.py
[constants_patch.txt](https://github.com/xbmc/xbmc/files/8260705/constants_patch.txt)

**Comment by manfeed** [comment]
Please, bear with me, but I'm a complete noob in Python... now my constants.py reads this way... I hope that's correct...

[constants.txt](https://github.com/xbmc/xbmc/files/8261304/constants.txt)

Thanks!

**Comment by MarkusEh** [comment]
Looks good. Rename it to constants.py, and try it out!

**Comment by roidy** [comment]
> Looks good. Rename it to constants.py, and try it out!

There's an error in that constants.py

is_64bits has no initial value and is only set if the exception occurs.

Meaning if no exception occurs then at line 33 is_64bits is undefined and throws an error.

**Comment by MarkusEh** [comment]
[constants_patch.txt](https://github.com/xbmc/xbmc/files/8303527/constants_patch.txt)
Here an updated (corrected) patch

**Comment by manfeed** [comment]
Then I guess that now constants-py must be this way, isn'it?
[constants.txt](https://github.com/xbmc/xbmc/files/8306278/constants.txt)

**Comment by MarkusEh** [comment]
@manfeed , looks good

**Comment by manfeed** [comment]
Bad news... I just got another error

EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
 - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
Error Type: <class 'AttributeError'>
Error Contents: 'bytes' object has no attribute 'tzinfo'
Traceback (most recent call last):
File "C:\Matrix2\portable_data\addons\script.embuary.info\plugin.py", line 5, in <module>
from resources.lib.widgets import *
File "C:\Matrix2\portable_data\addons\script.embuary.info\resources\lib\widgets.py", line 11, in <module>
from resources.lib.helper import *
File "C:\Matrix2\portable_data\addons\script.embuary.info\resources\lib\helper.py", line 15, in <module>
import arrow
File "C:\Matrix2\portable_data\addons\script.module.arrow\lib\arrow\__init__.py", line 2, in <module>
from .api import get, now, utcnow
File "C:\Matrix2\portable_data\addons\script.module.arrow\lib\arrow\api.py", line 12, in <module>
from arrow.arrow import TZ_EXPR, Arrow
File "C:\Matrix2\portable_data\addons\script.module.arrow\lib\arrow\arrow.py", line 1704, in <module>
Arrow.max = Arrow.fromdatetime(dt_datetime.max)
File "C:\Matrix2\portable_data\addons\script.module.arrow\lib\arrow\arrow.py", line 318, in fromdatetime
if dt.tzinfo is None:
AttributeError: 'bytes' object has no attribute 'tzinfo'
-->End of Python script error report<--

**Comment by matke-84** [comment]
@KarellenX and other kodi team members. Are you working to solve this problem? This bug really causes a lot of problems for us, skinners. Titan bingie mode (i'm one of the developers of this skin), is one of the most popular in the kodi community. But this bug just kills our skin. Very often kodi crashing, crashing addons used in skin such as skin helper service, skin helper service widgets... Please people do something about this problem.

**Comment by razzeee** [comment]
@DaVukovic can you reproduce this with the flatpak?

**Comment by MarkusEh** [comment]
Hi,

Here a patch for .../addons/script.module.arrow/lib/arrow/arrow.py

~ Markus
[arrow.diff.txt](https://github.com/xbmc/xbmc/files/8403224/arrow.diff.txt)

**Comment by manfeed** [comment]
Thanks! Then what you mean now is to forget all the previous changes to constants.py (thus going back to the original) and only to make this change in arrow.py, isn'it?

**Comment by MarkusEh** [comment]
Hi manfeed,

Both patches (for constants.py and for arrow.py) are required.

~ Markus

**Comment by matke-84** [comment]
[constants.txt](https://github.com/xbmc/xbmc/files/8405147/constants.txt)
[arrow.txt](https://github.com/xbmc/xbmc/files/8405148/arrow.txt)
@MarkusEh 
For now it looks ok but I have to check on a few more computers.

**Comment by matke-84** [comment]
```
2022-04-04 09:37:09.206 T:15088   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: 'datetime.timedelta' object has no attribute 'year'
                                                   Traceback (most recent call last):
                                                     File "C:\Users\Marko\AppData\Roaming\Kodi\addons\script.skin.helper.service\service.py", line 10, in <module>
                                                       from resources.lib.main_service import MainService
                                                     File "C:\Users\Marko\AppData\Roaming\Kodi\addons\script.skin.helper.service\resources\lib\main_service.py", line 16, in <module>
                                                       from metadatautils import MetadataUtils
                                                     File "C:\Users\Marko\AppData\Roaming\Kodi\addons\script.module.metadatautils\lib\metadatautils.py", line 10, in <module>
                                                       import helpers.kodi_constants as kodi_constants
                                                     File "C:\Users\Marko\AppData\Roaming\Kodi\addons\script.module.metadatautils\lib\helpers\kodi_constants.py", line 11, in <module>
                                                       from .utils import KODI_VERSION
                                                     File "C:\Users\Marko\AppData\Roaming\Kodi\addons\script.module.metadatautils\lib\helpers\utils.py", line 13, in <module>
                                                       import arrow
                                                     File "C:\Users\Marko\AppData\Roaming\Kodi\addons\script.module.arrow\lib\arrow\__init__.py", line 2, in <module>
                                                       from .api import get, now, utcnow
                                                     File "C:\Users\Marko\AppData\Roaming\Kodi\addons\script.module.arrow\lib\arrow\api.py", line 12, in <module>
                                                       from arrow.arrow import TZ_EXPR, Arrow
                                                     File "C:\Users\Marko\AppData\Roaming\Kodi\addons\script.module.arrow\lib\arrow\arrow.py", line 1707, in <module>
                                                       Arrow.max = Arrow.fromdatetime(dt_datetime.max)
                                                     File "C:\Users\Marko\AppData\Roaming\Kodi\addons\script.module.arrow\lib\arrow\arrow.py", line 327, in fromdatetime
                                                       dt.year,
                                                   AttributeError: 'datetime.timedelta' object has no attribute 'year'
                                                   -->End of Python script error report<--
```
Not good. Still has a problem.

**Comment by MarkusEh** [comment]
Here an update of the arrow.diff.txt :
[arrow.diff.txt](https://github.com/xbmc/xbmc/files/8411724/arrow.diff.txt)

Note: the patch on constants.by is still required.

**Comment by manfeed** [comment]
Thanks, but I'm at my wits' end… If someone could provide here a whole arrow.py file with the changes I could help in testing…

**Comment by matke-84** [comment]
@manfeed
[arrow.txt](https://github.com/xbmc/xbmc/files/8427599/arrow.txt)

**Comment by manfeed** [comment]
Sorry to convey bad news...

Error Type: <class 'AttributeError'>
Error Contents: 'datetime.timedelta' object has no attribute 'timestamp'
Traceback (most recent call last):
 File "C:\Matrix2\portable_data\addons\script.embuary.info\plugin.py", line 5, in <module>
from resources.lib.widgets import *
 File "C:\Matrix2\portable_data\addons\script.embuary.info\resources\lib\widgets.py", line 11, in <module>
from resources.lib.helper import *
 File "C:\Matrix2\portable_data\addons\script.embuary.info\resources\lib\helper.py", line 15, in <module>
import arrow
 File "C:\Matrix2\portable_data\addons\script.module.arrow\lib\arrow\__init__.py", line 2, in <module>
from .api import get, now, utcnow
 File "C:\Matrix2\portable_data\addons\script.module.arrow\lib\arrow\api.py", line 12, in <module>
from arrow.arrow import TZ_EXPR, Arrow
 File "C:\Matrix2\portable_data\addons\script.module.arrow\lib\arrow\arrow.py", line 34, in <module>
from arrow import formatter, locales, parser, util
 File "C:\Matrix2\portable_data\addons\script.module.arrow\lib\arrow\parser.py", line 26, in <module>
from arrow.util import next_weekday, normalize_timestamp
 File "C:\Matrix2\portable_data\addons\script.module.arrow\lib\arrow\util.py", line 6, in <module>
from arrow.constants import (
 File "C:\Matrix2\portable_data\addons\script.module.arrow\lib\arrow\constants.py", line 16, in <module>
_MAX_TIMESTAMP = datetime.max.timestamp()
AttributeError: 'datetime.timedelta' object has no attribute 'timestamp'
-->End of Python script error report<--

**Comment by matke-84** [comment]
@manfeed 
I dont't have any error in previous three days. Are you sure you used the correct files. Your previous constants.py file was not good. Try this.
[constants.txt](https://github.com/xbmc/xbmc/files/8452498/constants.txt)
[arrow.txt](https://github.com/xbmc/xbmc/files/8452499/arrow.txt)

**Comment by manfeed** [comment]
I haven't had a single error since I started using the last version in my 2 devices (windows 10 64 bits & 11 64 bits)... Please, is there any plan to add this fix to script.module.arrow in the Kodi repository? Thanks!

**Comment by razzeee** [comment]
We really don't want patched versions of libraries, so the preferred approach would be to send this to upstream https://github.com/arrow-py/arrow

**Comment by manfeed** [comment]
I understand your comment about the preferred aproach, but I think that it must be taken into account that the current version that is being provided now to the Kodi users has a bug, and not a small one, since it makes Kodi crash once and again, what is very frustrating. Now that we finally have a fix, it’s a pity to delay more the release of a correct version…

**Comment by razzeee** [comment]
A bug that should affect users of python too, so why should we just fix that for Kodi?

**Comment by MarkusEh** [comment]
Yes, this should be fixed by python. And yes, there is a bug report:

https://bugs.python.org/issue27400
https://github.com/python/cpython/issues/71587
Created on 2016-06-27 13:49 by Denny Weinberg, last changed 2022-04-11 14:58 by admin.

OK, they didn't fix it since 5-6 years :( .

**Comment by razzeee** [comment]
That would be ideal, if they can't/won't the next best thing would be to have a workaround in arrow itself (or whatever lib it's using that causes this)

**Comment by manfeed** [comment]
10 days have gone by and no one in Python said a single word… Could it be now the time for the next best thing, please? Thanks!

**Comment by manfeed** [comment]
@razzeee 

Could this workaround be included yet? Almost 40 days and no one in Python seems to care about it…

Thanks!

**Comment by thezoggy** [comment]
fix noted here: https://kodi.wiki/view/Python_Problems
