### ISSUE TITLE
Python 3.7 is brocken on Android platform

### ISSUE THREAD

**Issue by puenktchen** [xbmc/xbmc#17881]
### Describe the bug
Several Matrix compatible addons are throwing Python errors under Android.
They are working under Windows though!

## Expected Behavior

Addons that are working under Windows OS should als work under Android.

## Actual Behavior

Addons are throwing errors right at loading under Android, but not under Windows.

### To Reproduce

1. Install EmbyCon Video Addon for Matrix from here: https://github.com/faush01/plugin.video.embycon/archive/feature/matrix.zip
2. Install Embuary Helper Script for Matrix from here: https://github.com/sualfred/script.embuary.helper/archive/matrix.zip
3. Just wait some seconds to for the addons to be loaded and you get errors.

### Debuglog

The debuglog can be found here: https://paste.kodi.tv/sajijocuxu.kodi

### Your Environment
Used Operating system:

 - [X ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Android 5 but also on Nvidia Shield with Android 9
 - Kodi version: 19.0-ALPHA1 Git:20200514-f2e83f2947

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by wsnipex** [comment]
Not all python extensions and modules are available on all platforms.
Addons not available in our repository are not officially supported.

**Comment by sualfred** [comment]
Tested it on a Shield and can confirm that PIL is broken on Android

```
2020-05-17 09:25:23.758 T:24807   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'ImportError'>
                                                   Error Contents: dlopen failed: library "./_imaging.cpython-37-x86_64-linux-gnu.so" not found
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.embuary.helper/plugin.py", line 10, in <module>
                                                       from resources.lib.plugin_content import *
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.embuary.helper/resources/lib/plugin_content.py", line 11, in <module>
                                                       from resources.lib.image import *
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.embuary.helper/resources/lib/image.py", line 12, in <module>
                                                       from PIL import ImageFilter,Image,ImageOps
                                                     File "/data/user/0/org.xbmc.kodi/cache/apk/assets/addons/script.module.pil/lib/PIL/Image.py", line 66, in <module>
                                                       from PIL import _imaging as core
                                                     File "/data/user/0/org.xbmc.kodi/cache/apk/assets/addons/script.module.pil/lib/PIL/_imaging.py", line 7, in <module>
                                                       __bootstrap__()
                                                     File "/data/user/0/org.xbmc.kodi/cache/apk/assets/addons/script.module.pil/lib/PIL/_imaging.py", line 6, in __bootstrap__
                                                       imp.load_dynamic(__name__,__file__)
                                                     File "/data/app/org.xbmc.kodi-47KwPn9LgT2b66257N7DvA==/base.apk/assets/python3.7/lib/python3.7/imp.py", line 342, in load_dynamic
                                                       return _load(spec)
                                                   ImportError: dlopen failed: library "./_imaging.cpython-37-x86_64-linux-gnu.so" not found
                                                   -->End of Python script error report<--
```

**Comment by wsnipex** [comment]
does the shard lib exist? It's either a packaging issue or something with DLL loading has changed

**Comment by puenktchen** [comment]
> Not all python extensions and modules are available on all platforms.

So you are expecting from an addon developer to have devices for all platforms to test his addon?
That doesn't seem right to me, especially if the same python modules where working previously on Leia and the modules are shipped within Kodi and cannot be upgraded seperately like under Linux.

> Addons not available in our repository are not officially supported.

You mean EmbyCon, i guess? It was in the official repository but is now marked broken there. Maybe the addon developer don't want to go through the hassle of creating pull requests and waiting for addon approval with every small update.
