### ISSUE TITLE
Unknown URL content://android.media.tv/channel

### ISSUE THREAD

**Issue by 912233235** [xbmc/xbmc#18431]
2020-09-16 14:55:50.069 9142-9668/org.xbmc.kodi E/ActivityThread: Failed to find provider info for android.media.tv
2020-09-16 14:55:50.073 9142-9668/org.xbmc.kodi E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
    Process: org.xbmc.kodi, PID: 9142
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$3.done(AsyncTask.java:354)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.IllegalArgumentException: Unknown URL content://android.media.tv/channel
        at android.content.ContentResolver.insert(ContentResolver.java:1583)
        at org.xbmc.kodi.channels.util.TvUtil.createChannel(TvUtil.java:118)
        at org.xbmc.kodi.channels.SyncChannelJobService$SyncChannelTask.doInBackground(SyncChannelJobService.java:150)
        at org.xbmc.kodi.channels.SyncChannelJobService$SyncChannelTask.doInBackground(SyncChannelJobService.java:78)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764) 
2020-09-16 14:55:50.071 9142-9668/org.xbmc.kodi E/ActivityThread: Failed to find provider info for android.media.tv
2020-09-16 14:55:50.231 3501-3573/system_process E/InputDispatcher: channel '7643b9b org.xbmc.kodi/org.xbmc.kodi.Main (server)' ~ Channel is unrecoverably broken and will be disposed!

**Comment by KarellenX** [comment]
Don't know what you are asking/reporting and you completely ignored the required template so I shall close your issue.
