### ISSUE TITLE
Scrapper: Multiple results should be ordered by popularity

### ISSUE THREAD

**Issue by malaterre** [xbmc/xbmc#18894]
### Describe the bug
Here is a clear and concise description of what the problem is:

Scrapper arbitrarily pick the first item when multiple matches are found. This can be an issue for pocahontas+1995 search.

* https://api.themoviedb.org/3/search/movie?api_key=f090bb54758cabf231fb605d3e3e0468&language=fr-FR&query=pocahontas&year=1995

If you load this movie using kodi git/master, the following item is found:

* https://www.themoviedb.org/movie/55346-pocahontas

This is the second item in the JSON result (and not the first one).

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

I would have expected:

* https://www.themoviedb.org/movie/10530-pocahontas

## Actual Behavior

if you load this movie, the following item is found:

* https://www.themoviedb.org/movie/55346-pocahontas

## Possible Fix

Since only the first result it pick in the JSON results:

'https://api.themoviedb.org/3/search/movie?api_key=f090bb54758cabf231fb605d3e3e0468&language=fr-FR&query=pocahontas&year=1995'

the set should be ordered by popularity (since this correspond to the majority of people).

### To Reproduce

Step to reproduce:

```
$ wget http://techslides.com/demos/sample-videos/small.mp4
$ ffmpeg -i small.mp4 -map_metadata -1 -metadata title="pocahontas"  -metadata date="1995"   -c copy movie.mp4 
$ rm small.mp4

```

### Debuglog

```
2020-12-02 16:37:05.562 T:23586   DEBUG <general>: ------ Window Init (DialogExtendedProgressBar.xml) ------
2020-12-02 16:37:05.564 T:23675    INFO <general>: VideoInfoScanner: Starting scan ..
2020-12-02 16:37:05.565 T:23675   DEBUG <CAddonSettings[metadata.themoviedb.org.python]>: trying to load setting definitions from old format...
2020-12-02 16:37:05.565 T:23675   DEBUG <general>: VideoInfoScanner: Scanning dir '/tmp/fr/' as not in the database
2020-12-02 16:37:05.565 T:23675   DEBUG <CAddonSettings[metadata.themoviedb.org.python]>: trying to load setting definitions from old format...
2020-12-02 16:37:05.566 T:23675   DEBUG <general>: FindMovie: Searching for 'pocahontas' using The Movie Database Python scraper (path: '/home/mathieu/.kodi/addons/metadata.themoviedb.org.python/', content: 'movies', version: '1.3.1+matrix.1')
2020-12-02 16:37:05.567 T:23675   DEBUG <general>: StartScript - calling plugin The Movie Database Python('plugin://metadata.themoviedb.org.python/','1','?action=find&pathSettings=%7b%22RatingS%22%3a%22TMDb%22%2c%22add_tags%22%3atrue%2c%22certprefix%22%3a%22Rated%20%22%2c%22enable_fanarttv_artwork%22%3atrue%2c%22fanart%22%3atrue%2c%22fanarttv_clientkey%22%3a%22%22%2c%22fanarttv_language%22%3a%22fr%22%2c%22imdbanyway%22%3afalse%2c%22keeporiginaltitle%22%3afalse%2c%22landscape%22%3atrue%2c%22language%22%3a%22fr-FR%22%2c%22lastUpdated%22%3a%220%22%2c%22multiple_studios%22%3afalse%2c%22originalUrl%22%3a%22%22%2c%22previewUrl%22%3a%22%22%2c%22tmdbcertcountry%22%3a%22fr%22%2c%22trailer%22%3atrue%2c%22traktanyway%22%3afalse%7d&title=pocahontas&year=1995','resume:false')
2020-12-02 16:37:05.567 T:23678   DEBUG <general>: Thread LanguageInvoker start, auto delete: false
2020-12-02 16:37:05.567 T:23678    INFO <general>: initializing python engine.
2020-12-02 16:37:05.567 T:23678   DEBUG <general>: CPythonInvoker(2, /home/mathieu/.kodi/addons/metadata.themoviedb.org.python/python/scraper.py): start processing
2020-12-02 16:37:05.632 T:23678   DEBUG <general>: -->Python Interpreter Initialized<--
2020-12-02 16:37:05.632 T:23678   DEBUG <general>: 
                                                   
2020-12-02 16:37:05.632 T:23678   DEBUG <general>: CPythonInvoker(2, /home/mathieu/.kodi/addons/metadata.themoviedb.org.python/python/scraper.py): the source file to load is "/home/mathieu/.kodi/addons/metadata.themoviedb.org.python/python/scraper.py"
2020-12-02 16:37:05.632 T:23678   DEBUG <general>: CPythonInvoker(2, /home/mathieu/.kodi/addons/metadata.themoviedb.org.python/python/scraper.py): setting the Python path to /home/mathieu/.kodi/addons/metadata.themoviedb.org.python/python:/home/mathieu/Perso/xbmc/bin:/usr/lib/python37.zip:/usr/lib/python3.7:/usr/lib/python3.7/lib-dynload:/home/mathieu/.local/lib/python3.7/site-packages:/usr/local/lib/python3.7/dist-packages:/usr/lib/python3/dist-packages
2020-12-02 16:37:05.632 T:23678   DEBUG <general>: CPythonInvoker(2, /home/mathieu/.kodi/addons/metadata.themoviedb.org.python/python/scraper.py): entering source directory /home/mathieu/.kodi/addons/metadata.themoviedb.org.python/python
2020-12-02 16:37:05.632 T:23678   DEBUG <general>: CPythonInvoker(2, /home/mathieu/.kodi/addons/metadata.themoviedb.org.python/python/scraper.py): instantiating addon using automatically obtained id of "metadata.themoviedb.org.python" dependent on version 3.0.0 of the xbmc.python api
2020-12-02 16:37:05.777 T:23586   DEBUG <general>: ------ Window Deinit (DialogConfirm.xml) ------
2020-12-02 16:37:05.835 T:23678    INFO <general>: [metadata.themoviedb.org.python]: Find movie with title 'pocahontas' from year '1995'
2020-12-02 16:37:05.835 T:23678   DEBUG <general>: using title of pocahontas to find movie
2020-12-02 16:37:05.835 T:23678   DEBUG <general>: Calling URL "https://api.themoviedb.org/3/search/movie?api_key=f090bb54758cabf231fb605d3e3e0468&language=fr-FR&query=pocahontas&year=1995"
2020-12-02 16:37:06.052 T:23678   DEBUG <CAddonSettings[metadata.themoviedb.org.python]>: trying to load setting definitions from old format...
2020-12-02 16:37:06.052 T:23678   DEBUG <general>: getting configuration details
2020-12-02 16:37:06.052 T:23678   DEBUG <general>: Calling URL "https://api.themoviedb.org/3/configuration?api_key=f090bb54758cabf231fb605d3e3e0468"
2020-12-02 16:37:06.593 T:23678   DEBUG <CAddonSettings[metadata.themoviedb.org.python]>: trying to load setting definitions from old format...
2020-12-02 16:37:06.594 T:23678   DEBUG <CAddonSettings[metadata.themoviedb.org.python]>: trying to load setting definitions from old format...
2020-12-02 16:37:06.597 T:23678   DEBUG <CAddonSettings[metadata.themoviedb.org.python]>: trying to load setting definitions from old format...
2020-12-02 16:37:06.598 T:23678    INFO <general>: CPythonInvoker(2, /home/mathieu/.kodi/addons/metadata.themoviedb.org.python/python/scraper.py): script successfully run
2020-12-02 16:37:06.598 T:23675   DEBUG <general>: VideoInfoScanner: Fetching url '{"tmdb": "55346"}' using The Movie Database Python scraper (content: 'movies')
2020-12-02 16:37:06.598 T:23675   DEBUG <general>: GetVideoDetails: Reading movie '{"tmdb": "55346"}' using The Movie Database Python scraper (file: '/home/mathieu/.kodi/addons/metadata.themoviedb.org.python/', content: 'movies', version: '1.3.1+matrix.1')
2020-12-02 16:37:06.599 T:23675   DEBUG <general>: StartScript - calling plugin The Movie Database Python('plugin://metadata.themoviedb.org.python/','1','?action=getdetails&url=%7b%22tmdb%22%3a%20%2255346%22%7d&pathSettings=%7b%22RatingS%22%3a%22TMDb%22%2c%22add_tags%22%3atrue%2c%22certprefix%22%3a%22Rated%20%22%2c%22enable_fanarttv_artwork%22%3atrue%2c%22fanart%22%3atrue%2c%22fanarttv_clientkey%22%3a%22%22%2c%22fanarttv_language%22%3a%22fr%22%2c%22imdbanyway%22%3afalse%2c%22keeporiginaltitle%22%3afalse%2c%22landscape%22%3atrue%2c%22language%22%3a%22fr-FR%22%2c%22lastUpdated%22%3a%220%22%2c%22multiple_studios%22%3afalse%2c%22originalUrl%22%3a%22%22%2c%22previewUrl%22%3a%22%22%2c%22tmdbcertcountry%22%3a%22fr%22%2c%22trailer%22%3atrue%2c%22traktanyway%22%3afalse%7d','resume:false')
2020-12-02 16:37:06.599 T:23675   DEBUG <general>: GetLanguageInvoker - Reusing LanguageInvokerThread 2 for script /home/mathieu/.kodi/addons/metadata.themoviedb.org.python/python/scraper.py
2020-12-02 16:37:06.599 T:23678    INFO <general>: initializing python engine.
2020-12-02 16:37:06.599 T:23678   DEBUG <general>: CPythonInvoker(2, /home/mathieu/.kodi/addons/metadata.themoviedb.org.python/python/scraper.py): start processing
2020-12-02 16:37:06.599 T:23678   DEBUG <general>: CPythonInvoker(2, /home/mathieu/.kodi/addons/metadata.themoviedb.org.python/python/scraper.py): entering source directory /home/mathieu/.kodi/addons/metadata.themoviedb.org.python/python
2020-12-02 16:37:06.599 T:23678   DEBUG <general>: CPythonInvoker(2, /home/mathieu/.kodi/addons/metadata.themoviedb.org.python/python/scraper.py): instantiating addon using automatically obtained id of "metadata.themoviedb.org.python" dependent on version 3.0.0 of the xbmc.python api
2020-12-02 16:37:06.601 T:23678   DEBUG <general>: using movie id of 55346 to get movie details
2020-12-02 16:37:06.601 T:23678   DEBUG <general>: Calling URL "https://api.themoviedb.org/3/movie/55346?api_key=f090bb54758cabf231fb605d3e3e0468&language=fr-FR&append_to_response=trailers%2Cimages%2Creleases%2Ccasts%2Ckeywords&include_image_language=fr%2Cen%2Cnull"
2020-12-02 16:37:06.734 T:23678   DEBUG <general>: using movie id of 55346 to get movie details
2020-12-02 16:37:06.734 T:23678   DEBUG <general>: Calling URL "https://api.themoviedb.org/3/movie/55346?api_key=f090bb54758cabf231fb605d3e3e0468&append_to_response=trailers"
2020-12-02 16:37:06.882 T:23678   DEBUG <CAddonSettings[metadata.themoviedb.org.python]>: trying to load setting definitions from old format...
2020-12-02 16:37:06.883 T:23678   DEBUG <general>: Calling URL "https://webservice.fanart.tv/v3/movies/55346"
2020-12-02 16:37:07.068 T:23678   DEBUG <general>: Calling URL "https://webservice.fanart.tv/v3/movies/None"
2020-12-02 16:37:07.238 T:23678    INFO <general>: CPythonInvoker(2, /home/mathieu/.kodi/addons/metadata.themoviedb.org.python/python/scraper.py): script successfully run
2020-12-02 16:37:07.239 T:23679   DEBUG <general>: Thread JobWorker start, auto delete: true
2020-12-02 16:37:07.239 T:23675   DEBUG <general>: VideoInfoScanner: Adding new item to movies:/tmp/fr/movie.mp4
2020-12-02 16:37:07.239 T:23679   DEBUG <general>: easy_acquire - Created session to https://image.tmdb.org
2020-12-02 16:37:07.255 T:23675   DEBUG <general>: VideoInfoScanner: Finished adding information from dir /tmp/fr/
2020-12-02 16:37:07.259 T:23675    INFO <general>: VideoInfoScanner: Finished scan. Scanning for video info took 00:01
2020-12-02 16:37:07.264 T:23586   DEBUG <general>: CGUIMediaWindow::GetDirectory (sources://video/)
2020-12-02 16:37:07.264 T:23586   DEBUG <general>:   ParentPath = [sources://video/]
2020-12-02 16:37:07.264 T:23681   DEBUG <general>: Thread waiting start, auto delete: false
2020-12-02 16:37:07.264 T:23681   DEBUG <general>: Thread waiting 140443442456320 terminating
2020-12-02 16:37:07.265 T:23682   DEBUG <general>: Thread BackgroundLoader start, auto delete: false
2020-12-02 16:37:07.267 T:23682   DEBUG <general>: Thread BackgroundLoader 140443857340160 terminating
2020-12-02 16:37:07.438 T:23679   DEBUG <general>: CCurlFile::GetMimeType - https://image.tmdb.org/t/p/original/hHecQ6qvs4G6XPgeMH62ONEy4f.jpg -> image/jpeg
2020-12-02 16:37:07.438 T:23679   DEBUG <general>: CurlFile::Open(0x7fbb8c0064e0) https://image.tmdb.org/t/p/original/hHecQ6qvs4G6XPgeMH62ONEy4f.jpg
2020-12-02 16:37:07.494 T:23586   DEBUG <general>: ------ Window Deinit (DialogExtendedProgressBar.xml) ------

```

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: git/master

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by KarellenX** [comment]
Not a bug so the issue will be closed.

Both your Pocahontas movies are from 1995, and to believe we can somehow code the scraper to choose the movie **you** consider correct is asking for a bit much.

We have always stated that scrapers are not 100% accurate. When the scraper returns the wrong title, simply Refresh it and pick the correct one from the list. That is not hard at all.

**Comment by malaterre** [comment]
> Both your Pocahontas movies are from 1995, and to believe we can somehow code the scraper to choose the movie you consider correct is asking for a bit much.

Do you have technical consideration in mind ? I did describe a potential solution (though I did not test), could you describe why this would fail in some situation ?

As a side note I also explained why picking one title vs another is not a matter of personal choice but basically picking the most likely result (based on tmdb stats). Picking an arbitrary or a low popularity seems very surprising, and I am hoping this can be improved.

**Comment by KarellenX** [comment]
submit a PR and we will review it.

https://github.com/xbmc/repo-scrapers

**Comment by malaterre** [comment]
@KarellenX Could you help me find the right startup page ?

* https://kodi.wiki/view/Development
** https://kodi.wiki/view/Scrapers
*** https://kodi.wiki/view/Adding_video_sources

They all seems to describe the previous video scraper. Basically I simply need to get passed this very simple error:

```
$ git clone git@github.com:malaterre/repo-scrapers.git
$ cd repo-scrapers
$ git checkout matrix
$ python3 ./metadata.themoviedb.org.python/python/scraper.py
Traceback (most recent call last):
  File "./metadata.themoviedb.org.python/python/scraper.py", line 3, in <module>
    import xbmc
ModuleNotFoundError: No module named 'xbmc'

```

I also tried:

```
$ git clone git@github.com:malaterre/metadata.themoviedb.org.python.git
$ cd metadata.themoviedb.org.python
$ python3 -m unittest discover -v
[...]
======================================================================
ERROR: test.unittests.test_imdbratings (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test.unittests.test_imdbratings
Traceback (most recent call last):
  File "/usr/lib/python3.7/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/home/mathieu/Perso/metadata.themoviedb.org.python/test/unittests/test_imdbratings.py", line 4, in <module>
    from python.lib.tmdbscraper import imdbratings
  File "/home/mathieu/Perso/metadata.themoviedb.org.python/python/lib/tmdbscraper/imdbratings.py", line 22, in <module>
    from . import api_utils
  File "/home/mathieu/Perso/metadata.themoviedb.org.python/python/lib/tmdbscraper/api_utils.py", line 22, in <module>
    import json, xbmc
ModuleNotFoundError: No module named 'xbmc'


----------------------------------------------------------------------
Ran 46 tests in 0.012s

FAILED (errors=1)

```

**Comment by KarellenX** [comment]
@rmrector 

Any thoughts here?

**Comment by malaterre** [comment]
[brain dump before I forgot]

It seems that I get consistant results. So in summary when choosing 'fr-FR' the /wrong/ pocahontas is being picked, while if I keep the default setting the /right/ pocahontas is being picked... to be continued

**Comment by malaterre** [comment]
Found the root issue. The `title` of a movie is different from the `originalTitle`. For french people we have:

```
(gdb) p movielist[0]
$7 = {m_data = "", m_title = "Pocahontas (1995)", m_id = "", m_relevance = 0, m_urls = std::vector of length 1, capacity 1 = {{m_spoof = "", m_url = "{\"tmdb\": \"55346\"}", m_cache = "", m_aspect = "", 
      m_type = CScraperUrl::UrlType::General, m_post = false, m_isgz = false, m_season = -1}}, m_parsed = false}
(gdb) p movielist[1]
$8 = {m_data = "", m_title = "Pocahontas : Une Légende indienne (1995)", m_id = "", m_relevance = 0, m_urls = std::vector of length 1, capacity 1 = {{m_spoof = "", m_url = "{\"tmdb\": \"10530\"}", 
      m_cache = "", m_aspect = "", m_type = CScraperUrl::UrlType::General, m_post = false, m_isgz = false, m_season = -1}}, m_parsed = false}
(gdb) 

```

**Comment by malaterre** [comment]
@KarellenX this issue can be closed. The first item is indeed the most correct one:

* https://github.com/xbmc/xbmc/blob/19.0b1-Matrix/xbmc/video/VideoInfoScanner.cpp#L2155

the whole issue is with scrapping and language (I queried the wrong title). Sorry for the noise.

**Comment by KarellenX** [comment]
No problems. I was starting to worry there was an issue, but glad there isn't.

Enjoy!!
