### ISSUE TITLE
SIGSEGV - vaSyncSurface - large audio sync error

### ISSUE THREAD

**Issue by vindicatorr** [xbmc/xbmc#19241]
### Describe the bug

It's not all that uncommon that I encounter such a crash or when skipping through video, the video itself goes black/dark, but audio still plays, so I have to stop the video and start again from that stopped point.

This was one such crash that occurred when I skipped through commercials, video went black with audio and I think I pressed "stop" (so I could start playing again at that point), and the process died.

I also tend to see such audio sync log entries often (maybe even every time at some point?). If it matters (and it may), I use old bluetooth headphones.

## Expected Behavior

Video doesn't go black when skipping through. Also, exceptions are caught.

## Actual Behavior

The antithesis to Expected Behavior? Maybe I just don't understand why both of these exist. This is not the only place I've seen it.

## Possible Fix

I have none.

### To Reproduce

1. Watch a video
2. Skip through commercials
3. Wait for "bad luck" to hit. I think the dark video typically happens ~57 minutes in.

### Debuglog

The debuglog can be found here:
https://github.com/kodi-pvr/pvr.hts/issues/493
I had incorrectly posted it to the pvr extension source. Rather than re-posting a long log, I thought it best to just link to it.

### Your Environment

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [X] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Arch Linux
 - Kodi version: 19.0-RC1 (18.9.910) Git:20210210-a976d2fffe-dirty

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by vindicatorr** [comment]
Similar thing again. As I'm typing this, the log is filling up while there is no video OR audio:
```
2021-02-16 09:51:58.008 T:2496049    INFO <general>: Skipped 1 duplicate messages..
2021-02-16 09:51:58.008 T:2496049 WARNING <general>: CGLContextEGL::SwapBuffers: last msc time greater than interval
2021-02-16 09:53:07.927 T:2496049 WARNING <general>: CGLContextEGL::SwapBuffers: last msc time greater than interval
2021-02-16 09:53:46.450 T:2496092 WARNING <general>: ActiveAE - large audio sync error: -89450.247562
2021-02-16 09:53:46.451 T:2496092 WARNING <general>: ActiveAE - large audio sync error: -89450.066343
2021-02-16 09:53:58.359 T:2496092 WARNING <general>: ActiveAE - large audio sync error: -89466.489972
2021-02-16 09:53:58.487 T:2496092 WARNING <general>: ActiveAE - large audio sync error: -89475.007746
2021-02-16 09:54:01.360 T:2496092 WARNING <general>: ActiveAE - large audio sync error: -89502.850539
2021-02-16 09:54:01.456 T:2496092 WARNING <general>: ActiveAE - large audio sync error: -89514.349441
2021-02-16 09:54:20.901 T:2496092 WARNING <general>: ActiveAE - large audio sync error: -89410.730588
2021-02-16 09:54:20.905 T:2496092 WARNING <general>: ActiveAE - large audio sync error: -89410.328545
2021-02-16 09:54:27.093 T:2496092 WARNING <general>: ActiveAE - large audio sync error: -89342.432611
2021-02-16 09:54:27.098 T:2496092 WARNING <general>: ActiveAE - large audio sync error: -89343.394811
2021-02-16 09:54:31.213 T:2496092 WARNING <general>: ActiveAE - large audio sync error: -89272.155039
2021-02-16 09:54:31.340 T:2496092 WARNING <general>: ActiveAE - large audio sync error: -89265.152540
2021-02-16 09:54:35.452 T:2509101 WARNING <general>: VAAPI::FFGetBuffer - no surface available - dec: 1, render: 0
2021-02-16 09:55:07.131 T:2496049 WARNING <general>: CGLContextEGL::SwapBuffers: last msc time greater than interval
2021-02-16 09:55:07.147 T:2496049 WARNING <general>: CGLContextEGL::SwapBuffers: last msc time greater than interval (1)
2021-02-16 09:55:10.831 T:2496049 WARNING <general>: CGLContextEGL::SwapBuffers: last msc time greater than interval
2021-02-16 09:59:19.961 T:2509101   ERROR <general>: VAAPI::Decode - timed out waiting for output message - decoded: 0, proc: 0, has free surface: no
2021-02-16 09:59:19.962 T:2509105   ERROR <general>: VAAPI::COutput::Uninit - not all CPostprcs released
2021-02-16 09:59:19.962 T:2509105    INFO <general>: COutput::OnExit: Output Thread terminated
2021-02-16 09:59:19.972 T:2509101    INFO <general>: VAAPI::Close - closing decoder context
2021-02-16 09:59:21.205 T:2518934    INFO <general>: COutput::OnStartup: Output Thread created
2021-02-16 09:59:21.242 T:2496092 WARNING <general>: ActiveAE - large audio sync error: 387164.647544
2021-02-16 09:59:21.243 T:2496092 WARNING <general>: ActiveAE - large audio sync error: 387164.001781
2021-02-16 09:59:21.243 T:2496092 WARNING <general>: ActiveAE - large audio sync error: 387164.001449
2021-02-16 09:59:21.497 T:2496092 WARNING <general>: ActiveAE - large audio sync error: 387061.690659
...
2021-02-16 10:02:09.562 T:2496092 WARNING <general>: ActiveAE - large audio sync error: 218893.066862
2021-02-16 10:02:09.602 T:2509100   ERROR <general>: CDVDAudio::AddPacketsRenderer - timeout adding data to renderer
2021-02-16 10:02:09.658 T:2496092 WARNING <general>: ActiveAE - large audio sync error: 218792.978438
...
```
And the "large audio sync error" has taken over the new log entries.

**Comment by lilgandhi1199** [comment]
That's interesting!
https://github.com/xbmc/xbmc/issues/17328
I outlined audio sync errors as well under EDL audio muting.
Commerical skips (COMSkips) also use EDL files to do video skipping and of course have to process audio too.

**Comment by vindicatorr** [comment]
Hmm, I can't speak to there ever having been any audio sync issues (from a visual standpoint, despite what the log says).

**Comment by lilgandhi1199** [comment]
With enough buildup of audio sync errors I believe the video blacks out while it waits to catch up to the audio.

**Comment by vindicatorr** [comment]
Too add a little more output after the blackout when the audio stopped and I didn't stop playback, I took a look at the log:
```
...//many audio sync messages
2021-02-18 09:00:00.424 T:2736268 WARNING <general>: ActiveAE - large audio sync error: 5005.974213
2021-02-18 09:00:00.880 T:2811922   ERROR <general>: CDVDAudio::AddPacketsRenderer - timeout adding data to renderer
2021-02-18 09:00:10.153 T:2811923    INFO <general>: Skipped 1 duplicate messages..
2021-02-18 09:00:10.153 T:2811923    INFO <general>: CDVDVideoCodecFFmpeg::CDropControl: lost diff
2021-02-18 09:00:40.004 T:2736252 WARNING <general>: CGLContextEGL::SwapBuffers: last msc time greater than interval
2021-02-18 09:00:40.021 T:2736252 WARNING <general>: CGLContextEGL::SwapBuffers: last msc time greater than interval (1)
2021-02-18 09:00:44.404 T:2736252    INFO <general>: Skipped 1 duplicate messages..
2021-02-18 09:00:44.404 T:2736252 WARNING <general>: CGLContextEGL::SwapBuffers: last msc time greater than interval
2021-02-18 09:01:03.202 T:2736252 WARNING <general>: CGLContextEGL::SwapBuffers: last msc time greater than interval
2021-02-18 09:02:10.755 T:2736252    INFO <general>: CVideoPlayer::CloseFile()
2021-02-18 09:02:10.765 T:2811915    INFO <general>: CVideoPlayer::OnExit()
2021-02-18 09:02:10.765 T:2811915    INFO <general>: Closing stream player 1
2021-02-18 09:02:10.775 T:2811915    INFO <general>: Waiting for audio thread to exit
2021-02-18 09:02:10.779 T:2736252    INFO <general>: VideoPlayer: waiting for threads to exit
2021-02-18 09:02:10.794 T:2811922    INFO <general>: thread end: CVideoPlayerAudio::OnExit()
2021-02-18 09:02:10.795 T:2811915    INFO <general>: Closing audio device
2021-02-18 09:02:10.880 T:2811915    INFO <general>: Deleting audio codec
2021-02-18 09:02:10.884 T:2736269    INFO <general>: CActiveAESink::OpenSink - initialize sink
2021-02-18 09:02:10.887 T:2811915    INFO <general>: Closing stream player 2
2021-02-18 09:02:10.887 T:2811915    INFO <general>: waiting for video thread to exit
2021-02-18 09:02:10.887 T:2811923   ERROR <general>: Got MSGQ_ABORT or MSGO_IS_ERROR return true
2021-02-18 09:02:10.887 T:2811923    INFO <general>: thread end: video_thread
2021-02-18 09:02:10.887 T:2811915    INFO <general>: deleting video codec
2021-02-18 09:02:10.887 T:2811915    INFO <general>: VAAPI::Close
2021-02-18 09:02:10.887 T:2820171   ERROR <general>: VAAPI::COutput::Uninit - not all CPostprcs released
2021-02-18 09:02:10.887 T:2820171    INFO <general>: COutput::OnExit: Output Thread terminated
2021-02-18 09:02:10.887 T:2811915    INFO <general>: VAAPI::Close - closing decoder context
2021-02-18 09:02:10.924 T:2811915   ERROR <general>: VAAPI/vpp vaSyncSurface error: invalid VADisplay (3)
2021-02-18 09:02:10.924 T:2811915    INFO <general>: Skipped 6 duplicate messages..
2021-02-18 09:02:10.924 T:2811915   ERROR <general>: VAAPI/vpp vaDestroyBuffer error: invalid VADisplay (3)
2021-02-18 09:02:10.924 T:2811915   ERROR <general>: VAAPI/vpp vaDestroyContext error: invalid VADisplay (3)
2021-02-18 09:02:10.924 T:2811915   ERROR <general>: VAAPI/vpp vaDestroySurface error: invalid VADisplay (3)
2021-02-18 09:02:10.924 T:2811915    INFO <general>: Skipped 6 duplicate messages..
2021-02-18 09:02:10.924 T:2811915   ERROR <general>: VAAPI/vpp vaDestroyConfig error: invalid VADisplay (3)
2021-02-18 09:02:10.933 T:2811915    INFO <general>: Closing stream player 3
2021-02-18 09:02:10.968 T:2736252    INFO <general>: VideoPlayer: finished waiting
2021-02-18 09:02:10.968 T:2736252    INFO <general>: CVideoPlayer::CloseFile()
2021-02-18 09:02:10.968 T:2736252    INFO <general>: VideoPlayer: waiting for threads to exit
2021-02-18 09:02:10.968 T:2736252    INFO <general>: VideoPlayer: finished waiting
2021-02-18 09:02:11.530 T:2820446    INFO <general>: Found BT Device - will adjust buffers to larger values
2021-02-18 09:02:11.531 T:2736269    INFO <general>: PulseAudio: Opened device Default in pcm mode with Buffersize 343 ms Periodsize 100 ms
//end
```
While I was looking at the log, I heard the audio come back, but when I went to look, I saw there was still no video.
Disabling vaapi to see if there's a better outcome.

**Comment by vindicatorr** [comment]
I'm now on version 20.0-ALPHA1 (19.90.101) Git:20210328-294513d8fa-dirty

I don't know if this is still relevant, but I thought I'd add to this issue rather than create a new one...

After the playing video ended, Kodi normally closes the video and goes back to the last screen (EPG/Video-Recordings).
When it didn't do that the past 2 times (last time, I just -9 killed it), I let it sit and wait.
While waiting, I opened the log and the end was:
```
2021-03-30 18:53:26.603 T:433844 WARNING <general>: ActiveAE - large audio sync error: -89247.482556
2021-03-30 18:53:50.045 T:438353    INFO <general>: CVideoPlayerAudio::Process - stream stalled
2021-03-30 18:53:50.917 T:438352    INFO <general>: CVideoPlayer::OnExit()
2021-03-30 18:53:50.917 T:438352    INFO <general>: VideoPlayer: eof, waiting for queues to empty
2021-03-30 18:53:50.917 T:438352    INFO <general>: Closing stream player 1
2021-03-30 18:53:50.917 T:438352    INFO <general>: CDVDMessageQueue(audio)::WaitUntilEmpty
2021-03-30 18:53:50.917 T:438352    INFO <general>: Waiting for audio thread to exit
2021-03-30 18:53:50.917 T:438353   ERROR <general>: Got MSGQ_ABORT or MSGO_IS_ERROR return true
2021-03-30 18:53:50.953 T:438353    INFO <general>: thread end: CVideoPlayerAudio::OnExit()
2021-03-30 18:53:50.954 T:438352    INFO <general>: Closing audio device
2021-03-30 18:53:50.972 T:438352    INFO <general>: Deleting audio codec
2021-03-30 18:53:51.011 T:438352    INFO <general>: Closing stream player 2
2021-03-30 18:53:51.011 T:438352    INFO <general>: CDVDMessageQueue(video)::WaitUntilEmpty
2021-03-30 18:53:51.013 T:438352    INFO <general>: waiting for video thread to exit
2021-03-30 18:53:51.013 T:438354   ERROR <general>: Got MSGQ_ABORT or MSGO_IS_ERROR return true
2021-03-30 18:53:51.013 T:438354    INFO <general>: thread end: video_thread
2021-03-30 18:53:51.013 T:438352    INFO <general>: deleting video codec
2021-03-30 18:53:51.053 T:438352    INFO <general>: Closing stream player 3
2021-03-30 18:53:51.443 T:433845    INFO <general>: CActiveAESink::OpenSink - initialize sink
2021-03-30 18:53:52.337 T:443401    INFO <general>: Found BT Device - will adjust buffers to larger values
2021-03-30 18:53:52.347 T:433845    INFO <general>: PulseAudio: Opened device Default in pcm mode with Buffersize 343 ms Periodsize 100 ms
2021-03-30 18:53:52.709 T:433812    INFO <general>: CVideoPlayer::CloseFile()
2021-03-30 18:53:52.718 T:433812    INFO <general>: VAAPI::Close
2021-03-30 18:53:52.722 T:438356    INFO <general>: COutput::OnExit: Output Thread terminated
2021-03-30 18:53:52.722 T:433812    INFO <general>: VAAPI::Close - closing decoder context
2021-03-30 18:53:52.768 T:433812    INFO <general>: VideoPlayer: waiting for threads to exit
2021-03-30 18:53:52.769 T:433812    INFO <general>: VideoPlayer: finished waiting
2021-03-30 18:53:52.769 T:433812    INFO <general>: CVideoPlayer::CloseFile()
2021-03-30 18:53:52.769 T:433812    INFO <general>: VideoPlayer: waiting for threads to exit
2021-03-30 18:53:52.769 T:433812    INFO <general>: VideoPlayer: finished waiting
```
So it looks like the video closed and everything, even "finished waiting", but it was still hung on the last frame and no mouse cursor shows up when moved around.
While still waiting, I attached gdb to the process and the backtrace was:
```
#0  0x0000700efe5cda9d in syscall () at /usr/lib/libc.so.6
#1  0x0000700efe3c4582 in std::__atomic_futex_unsigned_base::_M_futex_wait_until(unsigned int*, unsigned int, bool, std::chrono::duration<long, std::ratio<1l, 1l> >, std::chrono::duration<long, std::ratio<1l, 1000000000l> >)
    (this=<optimized out>, __addr=0x5fe934170fa0, __val=2147483648, __has_timeout=<optimized out>, __s=..., __ns=...) at /build/gcc/src/gcc/libstdc++-v3/src/c++11/futex.cc:76
#2  0x00005fe930c78802 in CThread::Join(unsigned int) ()
#3  0x00005fe930c79ba5 in CThread::StopThread(bool) ()
#4  0x00005fe93099c898 in CVideoReferenceClock::~CVideoReferenceClock() ()
#5  0x00005fe93099c9b9 in CVideoReferenceClock::~CVideoReferenceClock() ()
#6  0x00005fe930931b88 in CDVDClock::~CDVDClock() ()
#7  0x00005fe930969995 in CVideoPlayer::~CVideoPlayer() ()
#8  0x00005fe930969c49 in CVideoPlayer::~CVideoPlayer() ()
#9  0x00005fe931079ddd in CApplicationPlayer::ClosePlayer() ()
#10 0x00005fe93106c9a3 in CApplication::OnMessage(CGUIMessage&) ()
#11 0x00005fe930e092a1 in CGUIWindowManager::SendMessage(CGUIMessage&) ()
#12 0x00005fe930e0a6c3 in CGUIWindowManager::DispatchThreadMessages() ()
#13 0x00005fe9310690b3 in CApplication::Process() ()
#14 0x00005fe93113bbb6 in CXBApplicationEx::Run(CAppParamParser const&) ()
#15 0x00005fe930565386 in main ()
```
It's still that way after I quit gdb, tried closing the program, then attaching gdb to it again. No change to the log either. It's just hung up. Going to have to -9 it again.

**Comment by ilikenwf** [comment]
Try disabling VAAPI video decoding maybe?

I have audio sync issues with my Arch install and Kodi where VLC has no issues - apparently the VAAPI decoder is too slow or too fast and causes my audio to desync...

**Comment by vindicatorr** [comment]
I know this issue is a bit old, but I've now got my headphones plugged into the board's jack instead of using bluetooth.
I looked at my log and did see only 1 instance of the "error", but it's nothing like it was with BT.
I currently have VAAPI set to Motion Compensated.
I wouldn't expect there'd be a performance issue for hardware accelerated decoding of an mpeg2 file, but certainly wouldn't dismiss the possibility for my old Haswell. But I'm considering upgrading to Alder/Raptor-lake. Sort of want AV1 accelerated encoding with Raptor.
