### ISSUE TITLE
Kodi crashes on startup (due to concurrent access to video database?)

### ISSUE THREAD

**Issue by dchristl** [xbmc/xbmc#19445]
## Bug report
After startup Kodi crashes on importing channels from TVHeadend. This behaviour is often on the first startup after a reboot. The second start it works almost always. I'm not quite sure if this is a problem of pvr-hts or kodi itself. 

## Expected Behavior

No crash on startup

## Actual Behavior

Crash with crashlog (Program terminated with signal SIGSEGV, Segmentation fault.)

## Possible Fix

Starting a second time

### To Reproduce

1. Start kodi 

### Debuglog

The debuglog can be found here:
[kodi_crashlog-20210319_082927.log](https://github.com/xbmc/xbmc/files/6169395/kodi_crashlog-20210319_082927.log)

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Ubuntu 20.04.2 LTS
 - Kodi version: 19.0.0 (19.02.2021)

**Comment by ksooo** [comment]
> I'm not quite sure if this is a problem of pvr-hts or kodi itself.

 Not a problem of the add-on. Reporting this here is fine.

**Comment by ksooo** [comment]
From what I can see importing the channels is not the cause of the crash. Two threads are accessing the video database concurrently. `CVideoDataBase` implementation is not thread safe, afaik.

```
Thread 24 (Thread 0x7f9cc3fff700 (LWP 4145)):
#0  __libc_pread64 (offset=<optimized out>, count=4096, buf=0x7f9cbc9e66b8, fd=72) at ../sysdeps/unix/sysv/linux/pread64.c:29
#1  __libc_pread64 (fd=72, buf=0x7f9cbc9e66b8, count=4096, offset=11669504) at ../sysdeps/unix/sysv/linux/pread64.c:27
#2  0x00007f9d61b46583 in ?? () from /usr/lib/x86_64-linux-gnu/libsqlite3.so.0
#3  0x00007f9d61b8ae05 in ?? () from /usr/lib/x86_64-linux-gnu/libsqlite3.so.0
#4  0x00007f9d61ba127f in ?? () from /usr/lib/x86_64-linux-gnu/libsqlite3.so.0
#5  0x00007f9d61b72862 in ?? () from /usr/lib/x86_64-linux-gnu/libsqlite3.so.0
#6  0x00007f9d61ba86b2 in ?? () from /usr/lib/x86_64-linux-gnu/libsqlite3.so.0
#7  0x00007f9d61bcffe7 in ?? () from /usr/lib/x86_64-linux-gnu/libsqlite3.so.0
#8  0x00007f9d61bd541a in sqlite3_step () from /usr/lib/x86_64-linux-gnu/libsqlite3.so.0
#9  0x000055f44cc5df62 in dbiplus::SqliteDataset::query(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
#10 0x000055f44c8a81d3 in CVideoDatabase::GetCast(int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<SActorInfo, std::allocator<SActorInfo> >&) ()
#11 0x000055f44c8bb585 in CVideoDatabase::GetDetailsForMovie(std::vector<dbiplus::field_value, std::allocator<dbiplus::field_value> > const*, int) ()
#12 0x000055f44c8c2ddb in CVideoDatabase::GetMoviesByWhere(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, CDatabase::Filter const&, CFileItemList&, SortDescription const&, int) ()
#13 0x000055f44c8c39cb in CVideoDatabase::GetMoviesNav(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, CFileItemList&, int, int, int, int, int, int, int, int, SortDescription const&, int) ()
#14 0x000055f44d2fc76e in JSONRPC::CVideoLibrary::GetMovies(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, JSONRPC::ITransportLayer*, JSONRPC::IClient*, CVariant const&, CVariant&) ()
#15 0x000055f44d2bc684 in JSONRPC::CJSONRPC::HandleMethodCall(CVariant const&, CVariant&, JSONRPC::ITransportLayer*, JSONRPC::IClient*) ()
#16 0x000055f44d2be94f in JSONRPC::CJSONRPC::MethodCall(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, JSONRPC::ITransportLayer*, JSONRPC::IClient*) ()
#17 0x000055f44c614d36 in XBMCAddon::xbmc::executeJSONRPC[abi:cxx11](char const*) ()
#18 0x000055f44c5be5c1 in ?? ()
#19 0x00007f9d62ea0408 in ?? () from /usr/lib/x86_64-linux-gnu/libpython3.8.so.1.0
```

```
Thread 36 (Thread 0x7f9d2bfff700 (LWP 4122)):
#0  __libc_pread64 (offset=<optimized out>, count=4096, buf=0x7f9d146ba4e8, fd=56) at ../sysdeps/unix/sysv/linux/pread64.c:29
#1  __libc_pread64 (fd=56, buf=0x7f9d146ba4e8, count=4096, offset=315392) at ../sysdeps/unix/sysv/linux/pread64.c:27
#2  0x00007f9d61b46583 in ?? () from /usr/lib/x86_64-linux-gnu/libsqlite3.so.0
#3  0x00007f9d61b8ae05 in ?? () from /usr/lib/x86_64-linux-gnu/libsqlite3.so.0
#4  0x00007f9d61ba127f in ?? () from /usr/lib/x86_64-linux-gnu/libsqlite3.so.0
#5  0x00007f9d61b72862 in ?? () from /usr/lib/x86_64-linux-gnu/libsqlite3.so.0
#6  0x00007f9d61ba86b2 in ?? () from /usr/lib/x86_64-linux-gnu/libsqlite3.so.0
#7  0x00007f9d61bcffe7 in ?? () from /usr/lib/x86_64-linux-gnu/libsqlite3.so.0
#8  0x00007f9d61bd541a in sqlite3_step () from /usr/lib/x86_64-linux-gnu/libsqlite3.so.0
#9  0x000055f44cc5df62 in dbiplus::SqliteDataset::query(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
#10 0x000055f44cc4cfc1 in CDatabase::GetSingleValue(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::unique_ptr<dbiplus::Dataset, std::default_delete<dbiplus::Dataset> >&) ()
#11 0x000055f44cc4d199 in CDatabase::GetSingleValue(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
#12 0x000055f44c9ff815 in CRecentlyAddedJob::UpdateTotal() ()
#13 0x000055f44ca00b63 in CRecentlyAddedJob::DoWork() ()
#14 0x000055f44c9d4a61 in CJobWorker::Process() ()
#15 0x000055f44ca72661 in CThread::Action() ()
#16 0x000055f44ca74895 in ?? ()
#17 0x000055f44ca753bd in ?? ()
#18 0x00007f9d60d56d84 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#19 0x00007f9d63581609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#20 0x00007f9d612fa293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

**Comment by dchristl** [comment]
> From what I can see importing the channels is not the cause of the crash. Two threads (recently added job and some python add-on thread) are accessing the video database concurrently. `CVideoDataBase` implementation is not thread safe, afaik. This is unrelated to any PVR activity happening on Kodi startup.

With your hint I checked the addons and found two filmscraper after update to Matrix, that can cause your mentioned error:
![image](https://user-images.githubusercontent.com/2836933/111862186-ef005780-8953-11eb-9d9b-92f63a53c6d1.png)
![image](https://user-images.githubusercontent.com/2836933/111862205-15be8e00-8954-11eb-8f46-c1904d9c6376.png)
![image](https://user-images.githubusercontent.com/2836933/111862210-27079a80-8954-11eb-9e4f-ffbc599f564b.png)

 I don't think this was the case on Leia. It is impossible to uninstall or deactivate one of these. Which one is the right for Matrix (the python one?) or are they both valid? I can try to "uninstall" one of these by deleting the add-on folder.

**Comment by ksooo** [comment]
> Which one is the right for Matrix (the python one?)

 i guess it's the python one, which was introduced with v19 and is imo unfortunately causing the crash.
