### ISSUE TITLE
Android 7 : ModuleNotFoundError: No module named '_multiprocessing'

### ISSUE THREAD

**Issue by Botster** [xbmc/xbmc#19458]
### Describe the bug
Here is a clear and concise description of what the problem is:

Kodi running on Amazon AFTMM with Android 7.1.2 API level 25, kernel: Linux ARM 32-bit version 4.4.120+ fails to load the required module for python3.8 multiprocessing with: "ModuleNotFoundError: No module named '_multiprocessing'"

Relevant log snippet:
2021-03-21 23:11:55.831 T:17693   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
- NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
Error Type: <class 'ModuleNotFoundError'>
Error Contents: No module named '_multiprocessing'
Traceback (most recent call last):
    File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.liveleak/default.py", line 490, in <module>
    if url: index(url)
    File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.liveleak/default.py", line 380, in index
    pool = Pool(os.cpu_count() * 2)
    File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.8/lib/python3.8/multiprocessing/dummy/__init__.py", line 123, in Pool
    from ..pool import ThreadPool
    File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.8/lib/python3.8/multiprocessing/pool.py", line 30, in <module>
    from .connection import wait
    File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.8/lib/python3.8/multiprocessing/connection.py", line 21, in <module>
    import _multiprocessing
ModuleNotFoundError: No module named '_multiprocessing'
-->End of Python script error report<--
                                                   
2021-03-21 23:11:55.831 T:17693   DEBUG <general>: onExecutionDone(2, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.liveleak/default.py)

Full debug log link provided below.

Note: This info is from a user of the plugin.video.liveleak (v2.0.0) for Kodi 19 as reported here:
https://github.com/Botster/plugin.video.liveleak/issues/6#issuecomment-803678896

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

It is expected that the Python 3 built-in module should be able to load all of its dependencies.

## Actual Behavior

The required module is not found.

## Possible Fix

A possible fix depends upon whether this is an Android-specific Kodi compile issue, or an upstream issue with Android 7 itself.

### To Reproduce

1. Launch Kodi 19 on Android 7.1.2
2. Launch the LIveleak plugin v2.0.0 (plugin.video.liveleak)
3. Select a category to fetch any relevant videos from the target site

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/unozanidud.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

N/A

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

N/A

### Your Environment
Used Operating system:

 - [X] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 19

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by enen92** [comment]
@fuzzard maybe something that is also solved with your latest osx patch?
