### ISSUE TITLE
Python's `socketserver` vs `SocketServer`

### ISSUE THREAD

**Issue by minchinweb** [xbmc/xbmc#19641]
### Describe the bug

When upgrading Kodi on Windows, `SocketServer.py` is overwritten (as expected), but the capitalization wasn't updated to `socketserver.py`, likely because Windows filenames disregard capitalization when determining if a file is the "same". Python import are case sensitive however, and so select imports can fail.

Here is a clear and concise description of what the problem is:

This causes random Python imports to fail.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Imports of the standard library should not fail.

Overwriting files (on Windows, at least for Python) needs to update capitalization if it changes.

## Actual Behavior

On every start up of Kodi, an error box appears. The YouTube plugin is also unusable.

## Possible Fix

Delete the original file and replace, rather than overwriting in place.

Uninstall and then re-install Kodi.

### To Reproduce

1. Install Kodi 18 (on Windows).
2. Install the YouTube plugin.
3. Upgrade to Kodi 19.
4. Launch Kodi 19.

### Debuglog

The debuglog can be found here:

Example (using the YouTube plugin):

```
2021-04-12 10:07:02.847 T:4208    ERROR <general>: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.youtube/
2021-04-12 10:07:02.880 T:10700   ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.youtube/) failed
2021-04-12 10:08:21.163 T:4584     INFO <general>: CActiveAESink::OpenSink - initialize sink
2021-04-12 10:08:34.515 T:11164    INFO <general>: CServiceAddonManager: failed to stop plugin.video.youtube (may have ended)
2021-04-12 10:08:34.761 T:10700 WARNING <general>: CGUIMediaWindow::OnMessage - updating in progress
2021-04-12 10:08:49.156 T:10868    INFO <general>: CAddonMgr::ADDON::CAddonMgr::FindAddon: plugin.video.youtube v6.8.10+matrix.1 installed
2021-04-12 10:08:49.161 T:1852     INFO <general>: initializing python engine.
2021-04-12 10:08:49.302 T:10700 WARNING <general>: CGUIMediaWindow::OnMessage - updating in progress
2021-04-12 10:08:49.818 T:1852    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'ModuleNotFoundError'>
                                                   Error Contents: No module named 'socketserver'
                                                   Traceback (most recent call last):
                                                     File "C:\Users\William\AppData\Roaming\Kodi\addons\plugin.video.youtube\resources\lib\startup.py", line 11, in <module>
                                                       from youtube_plugin.kodion import service
                                                     File "C:\Users\William\AppData\Roaming\Kodi\addons\plugin.video.youtube\resources\lib\youtube_plugin\kodion\__init__.py", line 18, in <module>
                                                       from .abstract_provider import AbstractProvider
                                                     File "C:\Users\William\AppData\Roaming\Kodi\addons\plugin.video.youtube\resources\lib\youtube_plugin\kodion\abstract_provider.py", line 20, in <module>
                                                       from . import utils
                                                     File "C:\Users\William\AppData\Roaming\Kodi\addons\plugin.video.youtube\resources\lib\youtube_plugin\kodion\utils\__init__.py", line 19, in <module>
                                                       from .http_server import get_http_server, is_httpd_live, get_client_ip_address
                                                     File "C:\Users\William\AppData\Roaming\Kodi\addons\plugin.video.youtube\resources\lib\youtube_plugin\kodion\utils\http_server.py", line 10, in <module>
                                                       from six.moves import BaseHTTPServer
                                                     File "C:\Users\William\AppData\Roaming\Kodi\addons\script.module.six\lib\six.py", line 92, in __get__
                                                       result = self._resolve()
                                                     File "C:\Users\William\AppData\Roaming\Kodi\addons\script.module.six\lib\six.py", line 115, in _resolve
                                                       return _import_module(self.mod)
                                                     File "C:\Users\William\AppData\Roaming\Kodi\addons\script.module.six\lib\six.py", line 82, in _import_module
                                                       __import__(name)
                                                     File "C:\Program Files\Kodi\system\python\Lib\http\server.py", line 102, in <module>
                                                       import socketserver
                                                   ModuleNotFoundError: No module named 'socketserver'
                                                   -->End of Python script error report<--
```

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

See also https://github.com/anxdpanic/plugin.video.youtube/issues/114

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10
 - Kodi version: 19

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by MinchinWeb** [comment]
`queue.py` vs `Queue.py` as well

**Comment by CastagnaIT** [comment]
FWIK this is not a bug, on Python 3 these imports are lowercase not camelcase,
you should adapt your imports to support python migration,
this can help you: https://python-future.org/compatible_idioms.html

**Comment by MinchinWeb** [comment]
@CastagnaIT 
> FWIK this is not a bug, on Python 3 these imports are lowercase not camelcase,

The bug here isn't the import (the imports are correct), it's that Kodi has installed the files with the wrong capitalization of the filenames on Windows. That bug seems to be in how upgrading Kodi from v18 to v19 overwrites the Python 2.7 standard library with the Python 3 standard library.

From the debug log (notice the capitalization):

```
File "C:\Program Files\Kodi\system\python\Lib\http\server.py", line 102, in <module>
    import socketserver
ModuleNotFoundError: No module named 'socketserver'
```

**Comment by CastagnaIT** [comment]
When you upgrade from Kodi 18 to Kodi 19
the "Program Files\Kodi" folder will be completely deleted before that Kodi 19 will be installed, then all old python 2 files are removed the new files has the right lowercase names,
i have just tried and i do not have this errors

**Comment by MinchinWeb** [comment]
I guess I made an assumption that this is somehow part of the upgrade process; I haven't tested that part directly. But what I do know:

1. This (the import error on the YouTube plugin) has happened on multiple computer. The error has been ongoing for some time, but I just got frustrated enough to try and get it solved.
2. Both systems have Kodi installed via chocolately. Both were upgrade from Kodi 18 to 19.
3. Manually renaming the files to lowercase solves this.

Here is the current file listing (from PowerShell) for the files in the Python standard library, maybe this has some clues:

```
    Directory: C:\Program Files\Kodi\system\Python\Lib

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----          2021-02-28  9:46 AM                asyncio
d----          2021-02-28  9:46 AM                collections
d----          2021-02-17  9:47 PM                compiler
d----          2021-02-28  9:46 AM                concurrent
d----          2021-02-28  9:46 AM                ctypes
d----          2021-02-28  9:46 AM                dbm
d----          2021-02-28  9:46 AM                distutils
d----          2021-02-28  9:46 AM                email
d----          2021-02-28  9:46 AM                encodings
d----          2021-02-17  9:47 PM                ensurepip
d----          2021-02-17  9:47 PM                hotshot
d----          2021-02-28  9:46 AM                html
d----          2021-02-28  9:46 AM                http
d----          2021-02-28  9:46 AM                importlib
d----          2021-02-17  9:47 PM                json
d----          2021-02-17  9:47 PM                lib2to3
d----          2021-02-17  9:47 PM                logging
d----          2021-02-28  9:46 AM                multiprocessing
d----          2021-02-28  9:46 AM                pydoc_data
d----          2021-02-28  9:46 AM                site-packages
d----          2021-02-17  9:47 PM                sqlite3
d----          2021-02-28  9:46 AM                tkinter
d----          2021-02-28  9:46 AM                turtledemo
d----          2021-02-28  9:46 AM                urllib
d----          2021-02-28  9:46 AM                venv
d----          2021-02-17  9:47 PM                wsgiref
d----          2021-02-17  9:47 PM                xml
d----          2021-02-28  9:46 AM                xmlrpc
-a---          2021-02-11  7:46 AM           5109 __future__.py
-a---          2021-02-11  7:46 AM             64 __phello__.foo.py
-a---          2016-12-17  1:05 PM          18619 _abcoll.py
-a---          2021-02-11  7:46 AM           1801 _bootlocale.py
-a---          2021-02-11  7:46 AM          26100 _collections_abc.py
-a---          2021-02-11  7:46 AM           8749 _compat_pickle.py
-a---          2021-02-11  7:46 AM           5340 _compression.py
-a---          2021-02-11  7:46 AM           6027 _dummy_thread.py
-a---          2016-12-17  1:05 PM           6553 _LWPCookieJar.py
-a---          2021-02-11  7:46 AM          14598 _markupbase.py
-a---          2016-12-17  1:05 PM           5797 _MozillaCookieJar.py
-a---          2021-02-11  7:46 AM          19600 _osx_support.py
-a---          2021-02-11  7:46 AM           6189 _py_abc.py
-a---          2021-02-11  7:46 AM         228666 _pydecimal.py
-a---          2021-02-11  7:46 AM          93177 _pyio.py
-a---          2021-02-11  7:46 AM           3115 _sitebuiltins.py
-a---          2021-02-11  7:46 AM          25268 _strptime.py
-a---          2021-02-11  7:46 AM           7220 _threading_local.py
-a---          2021-02-11  7:46 AM           5735 _weakrefset.py
-a---          2021-02-11  7:46 AM           4489 abc.py
-a---          2021-02-11  7:46 AM          32814 aifc.py
-a---          2021-02-11  7:46 AM            477 antigravity.py
-a---          2016-12-17  1:05 PM           2663 anydbm.py
-a---          2021-02-11  7:46 AM          96015 argparse.py
-a---          2021-02-11  7:46 AM          18895 ast.py
-a---          2021-02-11  7:46 AM          11328 asynchat.py
-a---          2021-02-11  7:46 AM          20094 asyncore.py
-a---          2016-12-17  1:05 PM           1705 atexit.py
-a---          2016-12-17  1:05 PM           7597 audiodev.py
-a---          2021-02-11  7:46 AM          20382 base64.py
-a---          2016-12-17  1:05 PM          22747 BaseHTTPServer.py
-a---          2016-12-17  1:05 PM           5744 Bastion.py
-a---          2021-02-11  7:46 AM          32056 bdb.py
-a---          2021-02-11  7:46 AM          13954 binhex.py
-a---          2021-02-11  7:46 AM           2214 bisect.py
-a---          2021-02-11  7:46 AM          12558 bz2.py
-a---          2021-02-11  7:46 AM          24832 calendar.py
-a---          2021-02-11  7:46 AM          33608 cgi.py
-a---          2016-12-17  1:05 PM          13089 CGIHTTPServer.py
-a---          2021-02-11  7:46 AM          12096 cgitb.py
-a---          2021-02-11  7:46 AM           5435 chunk.py
-a---          2021-02-11  7:46 AM          14860 cmd.py
-a---          2021-02-11  7:46 AM          10622 code.py
-a---          2021-02-11  7:46 AM          36667 codecs.py
-a---          2021-02-11  7:46 AM           6275 codeop.py
-a---          2016-12-17  1:05 PM          27798 collections.py
-a---          2021-02-11  7:46 AM           4064 colorsys.py
-a---          2016-12-17  1:05 PM           2545 commands.py
-a---          2021-02-11  7:46 AM          13678 compileall.py
-a---          2021-02-11  7:46 AM          54374 ConfigParser.py
-a---          2021-02-11  7:46 AM          24995 contextlib.py
-a---          2021-02-11  7:46 AM            129 contextvars.py
-a---          2016-12-17  1:05 PM          26538 Cookie.py
-a---          2016-12-17  1:05 PM          65000 cookielib.py
-a---          2016-12-17  1:05 PM           6800 copy_reg.py
-a---          2021-02-11  7:46 AM           8661 copy.py
-a---          2021-02-11  7:46 AM           7135 copyreg.py
-a---          2021-02-11  7:46 AM           6600 cProfile.py
-a---          2021-02-11  7:46 AM           3610 crypt.py
-a---          2021-02-11  7:46 AM          16144 csv.py
-a---          2021-02-11  7:46 AM          49936 dataclasses.py
-a---          2021-02-11  7:46 AM          88074 datetime.py
-a---          2016-12-17  1:05 PM            498 dbhash.py
-a---          2021-02-11  7:46 AM            320 decimal.py
-a---          2021-02-11  7:46 AM          84058 difflib.py
-a---          2016-12-17  1:05 PM           1126 dircache.py
-a---          2021-02-11  7:46 AM          20566 dis.py
-a---          2021-02-11  7:46 AM         104543 doctest.py
-a---          2016-12-17  1:05 PM          10500 DocXMLRPCServer.py
-a---          2016-12-17  1:05 PM           9141 dumbdbm.py
-a---          2016-12-17  1:05 PM           4418 dummy_thread.py
-a---          2021-02-11  7:46 AM           2815 dummy_threading.py
-a---          2021-02-11  7:46 AM          34882 enum.py
-a---          2021-02-11  7:46 AM           9830 filecmp.py
-a---          2021-02-11  7:46 AM          14709 fileinput.py
-a---          2021-02-11  7:46 AM           4056 fnmatch.py
-a---          2021-02-11  7:46 AM          15143 formatter.py
-a---          2016-12-17  1:05 PM           4699 fpformat.py
-a---          2021-02-11  7:46 AM          24329 fractions.py
-a---          2021-02-11  7:46 AM          34768 ftplib.py
-a---          2021-02-11  7:46 AM          37406 functools.py
-a---          2021-02-11  7:46 AM           4975 genericpath.py
-a---          2021-02-11  7:46 AM           7489 getopt.py
-a---          2021-02-11  7:46 AM           5994 getpass.py
-a---          2021-02-11  7:46 AM          27138 gettext.py
-a---          2021-02-11  7:46 AM           5697 glob.py
-a---          2021-02-11  7:46 AM          21441 gzip.py
-a---          2021-02-11  7:46 AM           9730 hashlib.py
-a---          2021-02-11  7:46 AM          22877 heapq.py
-a---          2021-02-11  7:46 AM           6629 hmac.py
-a---          2016-12-17  1:05 PM          18056 htmlentitydefs.py
-a---          2016-12-17  1:05 PM          12869 htmllib.py
-a---          2016-12-17  1:05 PM          17136 HTMLParser.py
-a---          2016-12-17  1:05 PM          50605 httplib.py
-a---          2016-12-17  1:05 PM          18986 ihooks.py
-a---          2021-02-11  7:46 AM          53606 imaplib.py
-a---          2021-02-11  7:46 AM           3808 imghdr.py
-a---          2021-02-11  7:46 AM          10536 imp.py
-a---          2016-12-17  1:05 PM          25764 imputil.py
-a---          2021-02-11  7:46 AM         118040 inspect.py
-a---          2021-02-11  7:46 AM           3541 io.py
-a---          2021-02-11  7:46 AM          71172 ipaddress.py
-a---          2021-02-11  7:46 AM            945 keyword.py
-a---          2021-02-11  7:46 AM           5330 linecache.py
-a---          2021-02-11  7:46 AM          78191 locale.py
-a---          2021-02-11  7:46 AM          12983 lzma.py
-a---          2016-12-17  1:05 PM           6289 macpath.py
-a---          2016-12-17  1:05 PM           2731 macurl2path.py
-a---          2021-02-11  7:46 AM          78661 mailbox.py
-a---          2021-02-11  7:46 AM           8104 mailcap.py
-a---          2016-12-17  1:05 PM          14643 markupbase.py
-a---          2016-12-17  1:05 PM            358 md5.py
-a---          2016-12-17  1:05 PM          33434 mhlib.py
-a---          2016-12-17  1:05 PM           7168 mimetools.py
-a---          2021-02-11  7:46 AM          21721 mimetypes.py
-a---          2016-12-17  1:05 PM           6482 MimeWriter.py
-a---          2016-12-17  1:05 PM          15021 mimify.py
-a---          2021-02-11  7:46 AM          24430 modulefinder.py
-a---          2016-12-17  1:05 PM           4820 multifile.py
-a---          2016-12-17  1:05 PM           1878 mutex.py
-a---          2021-02-11  7:46 AM           5566 netrc.py
-a---          2016-12-17  1:05 PM            610 new.py
-a---          2021-02-11  7:46 AM          43261 nntplib.py
-a---          2021-02-11  7:46 AM          27734 ntpath.py
-a---          2021-02-11  7:46 AM           2584 nturl2path.py
-a---          2021-02-11  7:46 AM          10244 numbers.py
-a---          2021-02-11  7:46 AM           5808 opcode.py
-a---          2021-02-11  7:46 AM          10711 operator.py
-a---          2021-02-11  7:46 AM          60369 optparse.py
-a---          2021-02-11  7:46 AM          38995 os.py
-a---          2016-12-17  1:05 PM           4635 os2emxpath.py
-a---          2021-02-11  7:46 AM          51839 pathlib.py
-a---          2016-12-17  1:05 PM           7914 pdb.doc
-a---          2021-02-11  7:46 AM          62678 pdb.py
-a---          2021-02-11  7:46 AM          64396 pickle.py
-a---          2021-02-11  7:46 AM          93486 pickletools.py
-a---          2021-02-11  7:46 AM           8916 pipes.py
-a---          2021-02-11  7:46 AM          21461 pkgutil.py
-a---          2021-02-11  7:46 AM          40328 platform.py
-a---          2021-02-11  7:46 AM          31251 plistlib.py
-a---          2016-12-17  1:05 PM           8416 popen2.py
-a---          2021-02-11  7:46 AM          15077 poplib.py
-a---          2016-12-17  1:05 PM           8003 posixfile.py
-a---          2021-02-11  7:46 AM          15627 posixpath.py
-a---          2021-02-11  7:46 AM          21484 pprint.py
-a---          2021-02-11  7:46 AM          23136 profile.py
-a---          2021-02-11  7:46 AM          27317 pstats.py
-a---          2021-02-11  7:46 AM           4807 pty.py
-a---          2021-02-11  7:46 AM           8250 py_compile.py
-a---          2021-02-11  7:46 AM          15255 pyclbr.py
-a---          2021-02-11  7:46 AM         107309 pydoc.py
-a---          2021-02-11  7:46 AM          11356 Queue.py
-a---          2021-02-11  7:46 AM           7254 quopri.py
-a---          2021-02-11  7:46 AM          28802 random.py
-a---          2021-02-11  7:46 AM          15861 re.py
-a---          2016-12-17  1:05 PM           4296 repr.py
-a---          2021-02-11  7:46 AM           5267 reprlib.py
-a---          2016-12-17  1:05 PM          20148 rexec.py
-a---          2016-12-17  1:05 PM          33542 rfc822.py
-a---          2021-02-11  7:46 AM           7097 rlcompleter.py
-a---          2016-12-17  1:05 PM           7587 robotparser.py
-a---          2021-02-11  7:46 AM          12052 runpy.py
-a---          2021-02-11  7:46 AM           6442 sched.py
-a---          2021-02-11  7:46 AM           2038 secrets.py
-a---          2021-02-11  7:46 AM          18561 selectors.py
-a---          2016-12-17  1:05 PM          19050 sets.py
-a---          2016-12-17  1:05 PM          17884 sgmllib.py
-a---          2016-12-17  1:05 PM            393 sha.py
-a---          2021-02-11  7:46 AM           8527 shelve.py
-a---          2021-02-11  7:46 AM          13325 shlex.py
-a---          2021-02-11  7:46 AM          50752 shutil.py
-a---          2021-02-11  7:46 AM           2273 signal.py
-a---          2016-12-17  1:05 PM           7997 SimpleHTTPServer.py
-a---          2016-12-17  1:05 PM          25812 SimpleXMLRPCServer.py
-a---          2021-02-11  7:46 AM          21329 site.py
-a---          2021-02-11  7:46 AM          34711 smtpd.py
-a---          2021-02-11  7:46 AM          44328 smtplib.py
-a---          2021-02-11  7:46 AM           7099 sndhdr.py
-a---          2021-02-11  7:46 AM          35243 socket.py
-a---          2021-02-11  7:46 AM          26923 SocketServer.py
-a---          2021-02-11  7:46 AM          26695 sre_compile.py
-a---          2021-02-11  7:46 AM           7154 sre_constants.py
-a---          2021-02-11  7:46 AM          40230 sre_parse.py
-a---          2016-12-17  1:05 PM            384 sre.py
-a---          2021-02-11  7:46 AM          50760 ssl.py
-a---          2021-02-11  7:46 AM           5485 stat.py
-a---          2021-02-11  7:46 AM          39690 statistics.py
-a---          2016-12-17  1:05 PM            898 statvfs.py
-a---          2021-02-11  7:46 AM          10535 string.py
-a---          2016-12-17  1:05 PM          10662 StringIO.py
-a---          2016-12-17  1:05 PM          12449 stringold.py
-a---          2021-02-11  7:46 AM          12917 stringprep.py
-a---          2021-02-11  7:46 AM            257 struct.py
-a---          2021-02-11  7:46 AM          77289 subprocess.py
-a---          2021-02-11  7:46 AM          18375 sunau.py
-a---          2016-12-17  1:05 PM           1399 sunaudio.py
-a---          2021-02-11  7:46 AM           2109 symbol.py
-a---          2021-02-11  7:46 AM           7573 symtable.py
-a---          2021-02-11  7:46 AM          24461 sysconfig.py
-a---          2021-02-11  7:46 AM          11408 tabnanny.py
-a---          2021-02-11  7:46 AM          93662 tarfile.py
-a---          2021-02-11  7:46 AM          23254 telnetlib.py
-a---          2021-02-11  7:46 AM          27595 tempfile.py
-a---          2021-02-11  7:46 AM          19407 textwrap.py
-a---          2021-02-11  7:46 AM           1003 this.py
-a---          2021-02-11  7:46 AM          50820 threading.py
-a---          2021-02-11  7:46 AM          13482 timeit.py
-a---          2016-12-17  1:05 PM           3142 toaiff.py
-a---          2021-02-11  7:46 AM           2368 token.py
-a---          2021-02-11  7:46 AM          25841 tokenize.py
-a---          2021-02-11  7:46 AM          29859 trace.py
-a---          2021-02-11  7:46 AM          23478 traceback.py
-a---          2021-02-11  7:46 AM          17076 tracemalloc.py
-a---          2021-02-11  7:46 AM            879 tty.py
-a---          2021-02-11  7:46 AM         143602 turtle.py
-a---          2021-02-11  7:46 AM           9713 types.py
-a---          2021-02-11  7:46 AM          68962 typing.py
-a---          2016-12-17  1:05 PM          59939 urllib.py
-a---          2016-12-17  1:05 PM          52513 urllib2.py
-a---          2016-12-17  1:05 PM          15164 urlparse.py
-a---          2016-12-17  1:05 PM           1627 user.py
-a---          2016-12-17  1:05 PM           7060 UserDict.py
-a---          2016-12-17  1:05 PM           3644 UserList.py
-a---          2016-12-17  1:05 PM           9687 UserString.py
-a---          2021-02-11  7:46 AM           6959 uu.py
-a---          2021-02-11  7:46 AM          30394 uuid.py
-a---          2021-02-11  7:46 AM          19688 warnings.py
-a---          2021-02-11  7:46 AM          18230 wave.py
-a---          2021-02-11  7:46 AM          21387 weakref.py
-a---          2021-02-11  7:46 AM          24065 webbrowser.py
-a---          2016-12-17  1:05 PM           3379 whichdb.py
-a---          2016-12-17  1:05 PM            187 wsgiref.egg-info
-a---          2021-02-11  7:46 AM           5913 xdrlib.py
-a---          2016-12-17  1:05 PM          34865 xmllib.py
-a---          2016-12-17  1:05 PM          52136 xmlrpclib.py
-a---          2021-02-11  7:46 AM           7535 zipapp.py
-a---          2021-02-11  7:46 AM          87668 zipfile.py
-a---          2021-02-11  7:46 AM          30765 zipimport.py
```

**Comment by titobrasolin** [comment]
> 2\. Both systems have Kodi installed via chocolately.

In my opinion the behavior can be reproduced by installing Kodi from the command line in silent mode:

    .\kodi-18.9-Leia-x64.exe /S
    .\kodi-19.0-Matrix-x64.exe /S

I believe this is what Chocolatey does.

**Comment by CastagnaIT** [comment]
@titobrasolin i have tried and i can confirm
the problem happen only with the silent install `/S`
that is why i have never encountered this problem..

the silent install seem do not perform the uninstall of previous installed version (that happen with regular setup), then all the existing files in Kodi programm folder are overwrited by the new setup with the result of mentioned problem,
this should be specified in the Issue steps details

i do not know if this is a desidered behaviour from Kodi devs, is needed to wait a their reply

**Comment by Paxxi** [comment]
Thank you for your excellent analysis and troubleshooting @MinchinWeb . This seems like an oversight when the installer was created. Possibly it was deliberately skipped since the uninstaller is not silent.

It's probably a "niche" issue as it only happens during an upgrade from v18 to v19 with /S, v19 to v20 won't have the issue. With that said I think we should attempt to fix it for 19.1 or 19.2 if I can find the time to look into how the installer works.

**Comment by matthuisman** [comment]
Just had a user with this but it was the queue module. which is Queue in python2. Good to see the team is aware and looking into it :)

**Comment by minchinweb** [comment]
Ran into this again today, now with Kodi v21.2, with `configparser`

**Comment by minchinweb** [comment]
Ran into a new variation, that I think stems from the same root problem.

The YouTube plugin has this backwards capacity check:

```py
    try:
        from StringIO import StringIO as _StringIO
    except ImportError:
        from io import StringIO as _StringIO
```

However, in my install, the `StringIO` file still exists (not updated from 2016...), and so it fails with this error:

```
2025-04-11 19:17:19.549 T:7456    error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'SyntaxError'>
                                                   Error Contents: invalid syntax (StringIO.py, line 40)
                                                   Traceback (most recent call last):
                                                     File "C:\Users\W\AppData\Roaming\Kodi\addons\plugin.video.youtube\resources\lib\plugin.py", line 13, in <module>
                                                       from youtube_plugin.kodion import plugin_runner
                                                     File "C:\Users\W\AppData\Roaming\Kodi\addons\plugin.video.youtube\resources\lib\youtube_plugin\kodion\plugin_runner.py", line 15, in <module>
                                                       from .debug import Profiler
                                                     File "C:\Users\W\AppData\Roaming\Kodi\addons\plugin.video.youtube\resources\lib\youtube_plugin\kodion\debug.py", line 39, in <module>
                                                       class Profiler(object):
                                                     File "C:\Users\W\AppData\Roaming\Kodi\addons\plugin.video.youtube\resources\lib\youtube_plugin\kodion\debug.py", line 57, in Profiler
                                                       from StringIO import StringIO as _StringIO
                                                     File "C:\Program Files\Kodi\system\python\Lib\StringIO.py", line 40
                                                       raise ValueError, "I/O operation on closed file"
                                                                       ^
                                                   SyntaxError: invalid syntax
                                                   -->End of Python script error report<--
```

removing the `StringIO.py` file solves this.

**Comment by minchinweb** [comment]
Ran into this again, this time with the Python version of the movie scraper.

It has a Python v2/v3 check at the beginning, and finds the old `urllib2.py` file in the Python folder, and breaks importing it.

~~~
2025-08-28 19:37:18.450 T:14952   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'SyntaxError'>
                                                   Error Contents: invalid syntax (urllib2.py, line 254)
                                                   Traceback (most recent call last):
                                                     File "C:\Users\W\AppData\Roaming\Kodi\addons\metadata.themoviedb.org.python\python\scraper.py", line 8, in <module>
                                                       from lib.tmdbscraper.tmdb import TMDBMovieScraper
                                                     File "C:\Users\W\AppData\Roaming\Kodi\addons\metadata.themoviedb.org.python\python\lib\tmdbscraper\tmdb.py", line 2, in <module>
                                                       from . import tmdbapi
                                                     File "C:\Users\W\AppData\Roaming\Kodi\addons\metadata.themoviedb.org.python\python\lib\tmdbscraper\tmdbapi.py", line 22, in <module>
                                                       from . import api_utils
                                                     File "C:\Users\W\AppData\Roaming\Kodi\addons\metadata.themoviedb.org.python\python\lib\tmdbscraper\api_utils.py", line 32, in <module>
                                                       from urllib2 import Request, urlopen
                                                     File "C:\Program Files\Kodi\system\python\Lib\urllib2.py", line 254
                                                       raise AttributeError, attr
                                                                           ^
                                                   SyntaxError: invalid syntax
                                                   -->End of Python script error report<--
~~~
