### ISSUE TITLE
[UWP] [Xbox] Version Check add-on causes Python exception

### ISSUE THREAD

**Issue by thexai** [xbmc/xbmc#19666]
### Describe the bug
Here is a clear and concise description of what the problem is:

Version Check add-on causes Python exception on UWP-64 builds

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

No Python exceptions

## Actual Behavior

![Captura de pantalla 2021-05-01 102109](https://user-images.githubusercontent.com/58434170/116776068-fc3a5700-aa66-11eb-80a0-dc7f71dba92d.png)

100% reproducible on both Windows 10 (running UWP-64 build) and Xbox

### To Reproduce

1.  Only start Kodi
2.
3.

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/cuyaheleja.kodi

Relevant lines for this issue:
```
2021-04-28 08:50:02.288 T:5832    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'PermissionError'>
                                                   Error Contents: [Errno 13] Permission denied: 'nul'
                                                   Traceback (most recent call last):
                                                     File "S:\Program Files\WindowsApps\XBMCFoundation.Kodi_19.0.0.0_x64__4n2hpmxwrvr6p\addons\service.xbmc.versioncheck\resources\lib\runner.py", line 14, in <module>
                                                       from version_check import service  # pylint: disable=import-error
                                                     File "S:\Program Files\WindowsApps\XBMCFoundation.Kodi_19.0.0.0_x64__4n2hpmxwrvr6p\addons\service.xbmc.versioncheck\resources\lib\version_check\service.py", line 41, in <module>
                                                       DISTRIBUTION = distro.linux_distribution(full_distribution_name=False)[0].lower()
                                                     File "S:\Program Files\WindowsApps\XBMCFoundation.Kodi_19.0.0.0_x64__4n2hpmxwrvr6p\addons\service.xbmc.versioncheck\resources\lib\version_check\distro\distro.py", line 122, in linux_distribution
                                                       return _distro.linux_distribution(full_distribution_name)
                                                     File "S:\Program Files\WindowsApps\XBMCFoundation.Kodi_19.0.0.0_x64__4n2hpmxwrvr6p\addons\service.xbmc.versioncheck\resources\lib\version_check\distro\distro.py", line 676, in linux_distribution
                                                       self.name() if full_distribution_name else self.id(),
                                                     File "S:\Program Files\WindowsApps\XBMCFoundation.Kodi_19.0.0.0_x64__4n2hpmxwrvr6p\addons\service.xbmc.versioncheck\resources\lib\version_check\distro\distro.py", line 694, in id
                                                       distro_id = self.lsb_release_attr('distributor_id')
                                                     File "S:\Program Files\WindowsApps\XBMCFoundation.Kodi_19.0.0.0_x64__4n2hpmxwrvr6p\addons\service.xbmc.versioncheck\resources\lib\version_check\distro\distro.py", line 899, in lsb_release_attr
                                                       return self._lsb_release_info.get(attribute, '')
                                                     File "S:\Program Files\WindowsApps\XBMCFoundation.Kodi_19.0.0.0_x64__4n2hpmxwrvr6p\addons\service.xbmc.versioncheck\resources\lib\version_check\distro\distro.py", line 552, in __get__
                                                       ret = obj.__dict__[self._fname] = self._f(obj)
                                                     File "S:\Program Files\WindowsApps\XBMCFoundation.Kodi_19.0.0.0_x64__4n2hpmxwrvr6p\addons\service.xbmc.versioncheck\resources\lib\version_check\distro\distro.py", line 1009, in _lsb_release_info
                                                       with open(os.devnull, 'w') as devnull:
                                                   PermissionError: [Errno 13] Permission denied: 'nul'
                                                   -->End of Python script error report<--
                                                   
2021-04-28 08:50:02.296 T:5832     INFO <general>: Python interpreter stopped
```

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [X] Windows UWP

 - Operating system version/name: Windows 10 20H2 / Xbox Series X with WINDOWS 10.0.19041.7722
 - Kodi version: v19.0 nightlies (Matrix or master)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by thexai** [comment]
Ping @fuzzard and @Paxxi

**Comment by Paxxi** [comment]
Looking at the stack trace this is a bug in the addon. It makes little sense for an addon to open devnull on any platform and definitely not on windows
