### ISSUE TITLE
movie scraper 'The Movie Database Python' doesn't work constant after update

### ISSUE THREAD

**Issue by Peacekeeper2000** [xbmc/xbmc#20349]
### Description
When updating the library after adding new movies, I received a couple of errors on screen that the add-on has stopped and should look in the event log. 
Some movies have been added with correct informations into my library. 
When I try to update the information for the other, not recognized movies I will receive the same error again.

There is no difference when I switch the search language from en-US to de-DE or back in the setting of the Movie Scraper Module
### Log File snippet
`2021-10-19 22:54:34.069 T:16688    INFO <general>: initializing python engine.
2021-10-19 22:54:34.364 T:16688    INFO <general>: [metadata.themoviedb.org.python]: Find movie with title '3 Engel für Charlie - Volle Power' from year 'None'
2021-10-19 22:54:34.373 T:16688   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'UnboundLocalError'>
                                                   Error Contents: local variable 'search_results' referenced before assignment
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/metadata.themoviedb.org.python/python/scraper.py", line 185, in <module>
                                                       run()
                                                     File "/storage/.kodi/addons/metadata.themoviedb.org.python/python/scraper.py", line 172, in run
                                                       search_for_movie(params["title"], params.get("year"), params['handle'], settings)
                                                     File "/storage/.kodi/addons/metadata.themoviedb.org.python/python/scraper.py", line 40, in search_for_movie
                                                       if not search_results:
                                                   UnboundLocalError: local variable 'search_results' referenced before assignment
                                                   -->End of Python script error report<--
                                                   
2021-10-19 22:54:34.811 T:16688 WARNING <general>: CPythonInvoker(400, /storage/.kodi/addons/metadata.themoviedb.org.python/python/scraper.py): the python script "/storage/.kodi/addons/metadata.themoviedb.org.python/python/scraper.py" has left several classes in mem
ory that we couldn't clean up. The classes include: N9XBMCAddon9xbmcaddon5AddonE
2021-10-19 22:54:34.811 T:16688    INFO <general>: Python interpreter stopped
2021-10-19 22:54:34.813 T:16687   ERROR <general>: GetDirectory - Error getting plugin://metadata.themoviedb.org.python/?action=find&pathSettings=%7b%22RatingS%22%3a%22TMDb%22%2c%22add_tags%22%3atrue%2c%22certprefix%22%3a%22Rated%20%22%2c%22enable_fanarttv_artwork%2
2%3atrue%2c%22fanart%22%3atrue%2c%22fanarttv_clientkey%22%3a%22%22%2c%22fanarttv_language%22%3a%22de%22%2c%22imdbanyway%22%3afalse%2c%22keeporiginaltitle%22%3afalse%2c%22landscape%22%3atrue%2c%22language%22%3a%22de-DE%22%2c%22lastUpdated%22%3a%220%22%2c%22multiple_s
`tudios%22%3afalse%2c%22originalUrl%22%3a%22%22%2c%22previewUrl%22%3a%22%22%2c%22searchlanguage%22%3a%22en-US%22%2c%22tmdbcertcountry%22%3a%22de%22%2c%22trailer%22%3afalse%2c%22traktanyway%22%3afalse%7d&title=3%20Engel%20f%c3%bcr%20Charlie%20-%20Volle%20Power`

## Possible Fix
coding issue

I also see in the log, that the search language is always `en-US` regardless what I configure (e.g. `de-DE` ). But searching for english titel doesn't make a difference

### To Reproduce
I am sure I am not the only one with this issue

### Screenshots 
N/A

## Additional context or screenshots (if appropriate)
N/A

### Your Environment
Kodi System is a RPi4 with LibreELEC 10.0.0
The Movie Database Python Version 1.5.0+matrix.1
(Former Version 1.4 worked without any trouble ) 
local language is German - and so is the search configured with de-DE

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: LibreELEC 10.0.0
 - Kodi version:19.1.0

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by Peacekeeper2000** [comment]
Sorry, wrong place for the issue. Issue seems to be fixed in upcoming version 1.5.1 of the plug-in
