### ISSUE TITLE
python script error when trying to launch radio addon

### ISSUE THREAD

**Issue by funzzionale** [xbmc/xbmc#20564]
### Describe the bug
Here is a clear and concise description of what the problem is:

using fedora 35 the radio addon https://kodi.wiki/view/Add-on:Radio will not launch
this worked before on fedora 34
installing python 2 does not fix the issue
here is the bug report on fusion with the answer that this is an upstream issue
https://bugzilla.rpmfusion.org/show_bug.cgi?id=6152

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

install radio from the official repo
launch radio

## Actual Behavior

launch radio results in error

## Possible Fix

The add-on does not support Python 3.10, which is what Fedora 35 uses

### To Reproduce

1. https://bugzilla.rpmfusion.org/show_bug.cgi?id=6152
2.
3.

### Debuglog

The debuglog can be found here:
the log shows:

2021-11-22 23:05:19.557 T:20144    INFO <general>: initializing python engine.
2021-11-22 23:05:19.680 T:20144   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: module 'collections' has no attribute 'MutableMapping'
                                                   Traceback (most recent call last):
                                                     File "/home/lagaffe/.kodi/addons/plugin.audio.radio_de/addon.py", line 11, in <module>
                                                       from resources.lib import plugin
                                                     File "/home/lagaffe/.kodi/addons/plugin.audio.radio_de/resources/lib/plugin.py", line 11, in <module>
                                                       from xbmcswift2 import Plugin, xbmc, listitem
                                                     File "/home/lagaffe/.kodi/addons/script.module.xbmcswift2/lib/xbmcswift2/__init__.py", line 66, in <module>
                                                       from xbmcswift2.storage import TimedStorage
                                                     File "/home/lagaffe/.kodi/addons/script.module.xbmcswift2/lib/xbmcswift2/storage.py", line 110, in <module>
                                                       class _Storage(collections.MutableMapping, _PersistentDictMixin):
                                                   AttributeError: module 'collections' has no attribute 'MutableMapping'
                                                   -->End of Python script error report<--
                                                   
2021-11-22 23:05:19.705 T:20144    INFO <general>: Python interpreter stopped
2021-11-22 23:05:19.718 T:20142   ERROR <general>: GetDirectory - Error getting plugin://plugin.audio.radio_de/
2021-11-22 23:05:19.729 T:19856   ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.audio.radio_de/) failed

### Screenshots 
Here are some links or screenshots to help explain the problem:

https://bugzilla.rpmfusion.org/show_bug.cgi?id=6152

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: fedora 35
 - Kodi version: 19.3.0

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by fuzzard** [comment]
This isnt a kodi issue. You will need to contact the addon dev and have them fix it in the addon. Looks like best place will be on the forums - https://forum.kodi.tv/showthread.php?tid=119362

**Comment by funzzionale** [comment]
enen92 is the developer
