### ISSUE TITLE
Error in /addons/script.module.arrow/lib/arrow/constants.py", line 16: "AttributeError: 'datetime.timedelta' object has no attribute 'timestamp'"

### ISSUE THREAD

**Issue by MarkusEh** [xbmc/xbmc#21046]
### Describe the bug
Here is a clear and concise description of what the problem is:

Python exception "AttributeError: 'datetime.timedelta' object has no attribute 'timestamp'"

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

No Python exception

## Actual Behavior

Python exception "AttributeError: 'datetime.timedelta' object has no attribute 'timestamp'"

## Possible Fix

Not sure. Small change in .kodi/addons/script.module.arrow/lib/arrow/constants.py ?

### To Reproduce

1.  Scrap (scan) with thetvdb (new) scraper (metadata.tvdb.com.python v1.0.3 )
2.
3.

### Debuglog

The debuglog can be found here:

022-02-27 17:33:48.010 T:16354    INFO <general>: Starting Kodi (19.3 (19.3.0) Git:20211118-a22c0ba337). Platform: Linux ARM 32-bit
2022-02-27 17:33:48.010 T:16354    INFO <general>: Using Release Kodi x32
2022-02-27 17:33:48.010 T:16354    INFO <general>: Kodi compiled 2021-11-18 by GCC 10.2.1 for Linux ARM 32-bit version 5.10.63 (330303)
2022-02-27 17:33:48.010 T:16354    INFO <general>: Running on BCM2835 with Raspbian GNU/Linux 11 (bullseye), kernel: Linux ARM 32-bit version 5.15.24-v7+
2022-02-27 17:33:48.010 T:16354    INFO <general>: FFmpeg version/source: 4.3.3-0+rpt2+deb11u1
2022-02-27 17:33:48.010 T:16354    INFO <general>: Host CPU: ARMv7 Processor rev 4 (v7l), 4 cores available
2022-02-27 17:33:48.010 T:16354    INFO <general>: ARM Features: Neon enabled

2022-02-27 17:33:48.629 T:16354    INFO <general>: CAddonMgr::FindAddons: metadata.tvdb.com.python v1.0.3 installed
2022-02-27 17:33:48.642 T:16354    INFO <general>: CAddonMgr::FindAddons: xbmc.python v3.0.0 installed

...

2022-02-27 17:39:30.533 T:16638   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: 'datetime.timedelta' object has no attribute 'timestamp'
                                                   Traceback (most recent call last):
                                                     File "/var/lib/vdr/.kodi/addons/metadata.tvdb.com.python/scraper.py", line 3, in <module>
                                                       from resources.lib import actions
                                                     File "/var/lib/vdr/.kodi/addons/metadata.tvdb.com.python/resources/lib/actions.py", line 14, in <module>
                                                       from . import episodes, series
                                                     File "/var/lib/vdr/.kodi/addons/metadata.tvdb.com.python/resources/lib/episodes.py", line 10, in <module>
                                                       from .nfo import parse_episode_guide_url
                                                     File "/var/lib/vdr/.kodi/addons/metadata.tvdb.com.python/resources/lib/nfo.py", line 7, in <module>
                                                       from . import series
                                                     File "/var/lib/vdr/.kodi/addons/metadata.tvdb.com.python/resources/lib/series.py", line 11, in <module>
                                                       from .ratings import ratings
                                                     File "/var/lib/vdr/.kodi/addons/metadata.tvdb.com.python/resources/lib/ratings.py", line 6, in <module>
                                                       from .trakt_rating import get_trakt_rating_and_votes
                                                     File "/var/lib/vdr/.kodi/addons/metadata.tvdb.com.python/resources/lib/trakt_rating.py", line 4, in <module>
                                                       from trakt import Trakt
                                                     File "/var/lib/vdr/.kodi/addons/script.module.trakt/lib/trakt/__init__.py", line 3, in <module>
                                                       from trakt.client import TraktClient
                                                     File "/var/lib/vdr/.kodi/addons/script.module.trakt/lib/trakt/client.py", line 3, in <module>
                                                       from trakt.core.configuration import ConfigurationManager
                                                     File "/var/lib/vdr/.kodi/addons/script.module.trakt/lib/trakt/core/configuration.py", line 3, in <module>
                                                       from trakt.core.context_collection import ContextCollection
                                                     File "/var/lib/vdr/.kodi/addons/script.module.trakt/lib/trakt/core/context_collection.py", line 3, in <module>
                                                       from trakt.core.helpers import synchronized
                                                     File "/var/lib/vdr/.kodi/addons/script.module.trakt/lib/trakt/core/helpers.py", line 9, in <module>
                                                       import arrow
                                                     File "/var/lib/vdr/.kodi/addons/script.module.arrow/lib/arrow/__init__.py", line 2, in <module>
                                                       from .api import get, now, utcnow
                                                     File "/var/lib/vdr/.kodi/addons/script.module.arrow/lib/arrow/api.py", line 12, in <module>
                                                       from arrow.arrow import TZ_EXPR, Arrow
                                                     File "/var/lib/vdr/.kodi/addons/script.module.arrow/lib/arrow/arrow.py", line 34, in <module>
                                                       from arrow import formatter, locales, parser, util
                                                     File "/var/lib/vdr/.kodi/addons/script.module.arrow/lib/arrow/parser.py", line 26, in <module>
                                                       from arrow.util import next_weekday, normalize_timestamp
                                                     File "/var/lib/vdr/.kodi/addons/script.module.arrow/lib/arrow/util.py", line 6, in <module>
                                                       from arrow.constants import (
                                                     File "/var/lib/vdr/.kodi/addons/script.module.arrow/lib/arrow/constants.py", line 16, in <module>
                                                       _MAX_TIMESTAMP = datetime.max.timestamp()
                                                   AttributeError: 'datetime.timedelta' object has no attribute 'timestamp'
                                                   -->End of Python script error report<--

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:Linux rpi3 5.15.24-v7+ # 1526 SMP Fri Feb 18 14:55:32 GMT 2022 armv7l GNU/Linu
 - Kodi version:Starting Kodi (19.3 (19.3.0) Git:20211118-a22c0ba337). Platform: Linux ARM 32-bit

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by KarellenX** [comment]
Similar or same report?
https://github.com/xbmc/xbmc/issues/17311

**Comment by matthuisman** [comment]
Yes, this is that same issue (duplicate)
