### ISSUE TITLE
Linux master builds segfault on exit

### ISSUE THREAD

**Issue by mglae** [xbmc/xbmc#21240]
### Describe the bug
Here is a clear and concise description of what the problem is:

Since #21174 Linux master builds segfault on exit in thread FDEventMonitor.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

No crash.

## Actual Behavior

Crash because Log() is used after logging was uninitialized.

### To Reproduce

1. Build current master
2. Exit kodi

### Debuglog

The debuglog can be found here:

Debug log ends with `INFO <general>: Exiting the application...`. Backtrace is:
```
Thread 6 "FDEventMonitor" received signal SIGSEGV, Segmentation fault.

#0  CLog::FormatAndLogInternal<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&> (format=..., 
    level=spdlog::level::debug, this=0x0) at /usr/include/c++/8/bits/shared_ptr_base.h:996
        message = "Thread FDEventMonitor 140736800478976 terminating"
        message = <optimized out>
#1  CLog::Log<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&> (format=..., level=spdlog::level::debug)
    at /home/mg/build/kodi/kodi-git/xbmc/utils/log.h:101
No locals.
#2  CLog::Log<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&> (format=..., level=0)
    at /home/mg/build/kodi/kodi-git/xbmc/utils/log.h:81
No locals.
#3  CThread::<lambda(CThread*, std::promise<bool>)>::operator()(CThread *, std::promise<bool>) (
    pThread=<optimized out>, promise=..., __closure=<optimized out>)
    at /home/mg/build/kodi/kodi-git/xbmc/threads/Thread.cpp:147
        name = "FDEventMonitor"
        autodelete = <optimized out>
        ss = <incomplete type>
        id = "140736800478976"
        __FUNCTION__ = <optimized out>
#4  0x000000000109e136 in std::__invoke_impl<void, CThread::Create(bool)::<lambda(CThread*, std::promise<bool>)>, CThread*, std::promise<bool> > (__f=...) at /usr/include/c++/8/bits/invoke.h:60
No locals.
#5  std::__invoke<CThread::Create(bool)::<lambda(CThread*, std::promise<bool>)>, CThread*, std::promise<bool> > (
    __fn=...) at /usr/include/c++/8/bits/invoke.h:95
No locals.
#6  std::thread::_Invoker<std::tuple<CThread::Create(bool)::<lambda(CThread*, std::promise<bool>)>, CThread*, std::promise<bool> > >::_M_invoke<0, 1, 2> (this=<optimized out>) at /usr/include/c++/8/thread:244
No locals.
#7  std::thread::_Invoker<std::tuple<CThread::Create(bool)::<lambda(CThread*, std::promise<bool>)>, CThread*, std::promise<bool> > >::operator() (this=<optimized out>) at /usr/include/c++/8/thread:253
No locals.
#8  std::thread::_State_impl<std::thread::_Invoker<std::tuple<CThread::Create(bool)::<lambda(CThread*, std::promise<bool>)>, CThread*, std::promise<bool> > > >::_M_run(void) (this=<optimized out>)
    at /usr/include/c++/8/thread:196
No locals.
#9  0x00007fffed5b3c74 in ?? () from /usr/lib64/libstdc++.so.6
No symbol table info available.
#10 0x00007fffed0ac539 in start_thread (arg=0x7fffd6ffd700) at pthread_create.c:465
        pd = 0x7fffd6ffd700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140736800478976, 8021298964176438805, 140736817258206, 
                140736817258207, 140736615943776, 140736817258208, -8021248386058287595, -8021268289186298347}, 
              mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, 
              canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
        frame = <optimized out>
#11 0x00007fffefe43e0f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
No locals.
```

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

First noticed in https://github.com/LibreELEC/LibreELEC.tv/pull/6353. Reproduced on desktop with symbols.

Reverting #21174 let the crash disappear.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [X] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Linux
 - Kodi version: 20

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by basilgello** [comment]
I confirm the same issue on master trunk built for Debian unstable.
