### ISSUE TITLE
Kodi 19 crash when playing HLS: ActiveAE - Arithmetic exception

### ISSUE THREAD

**Issue by TermeHansen** [xbmc/xbmc#21353]
### Describe the bug
When starting playback of some specific streams via the plugin.video.drnu addon, kodi will crash when using the adaptive inputstream. When using the normal ffmpeg demuxer it will play but will crash when trying to skip.

### Expected Behavior
Normal playback of hls stream

### Actual Behavior
kodi crashes with no errors in debug log

## Possible Fix
no known

### To Reproduce
Play a .strm file with:

```
#KODIPROP:inputstream=inputstream.adaptive
#KODIPROP:inputstream.adaptive.manifest_type=hls
https://drod22d.akamaized.net/dk/encrypted/none/b4/625ef6edaa5a612268e778b4/00022162620/stream_fmp4/master_manifest.m3u8

``` 

### Debuglog

The debuglog can be found here:
https://pastebin.com/qPSALQ9v

### Additional context
tried with ffmpegdirect. It starts but kodi crash when trying to skip...
```
#KODIPROP:inputstream=inputstream.ffmpegdirect
#KODIPROP:mimetype=application/x-mpegURL
#KODIPROP:inputstream.ffmpegdirect.manifest_type=hls
https://drod22d.akamaized.net/dk/encrypted/none/b4/625ef6edaa5a612268e778b4/00022162620/stream_fmp4/master_manifest.m3u8

```

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [X] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Ubuntu 20.04
 - Kodi version: 19.4.0

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by CastagnaIT** [comment]
for InputStream adaptive crash please open the issue on repository:
https://github.com/xbmc/inputstream.adaptive/issues

and remember to attach also a copy of the manifest "master_manifest.m3u8" file
the link provided seem need to account somewhere

**Comment by TermeHansen** [comment]
Thanks, I was also in doubt where to put it.

https://github.com/xbmc/inputstream.adaptive/issues/963

I'll close this here.

**Comment by CastagnaIT** [comment]
Reopened since last info given highlighted a possible bug in `ActiveAE::CActiveAEBufferPool::Create`

stacktrace:

gdb gave this:
```
[New Thread 0x7fffd67fc700 (LWP 51058)]
--Type <RET> for more, q to quit, c to continue without paging--

Thread 6 "ActiveAE" received signal SIGFPE, Arithmetic exception.
[Switching to Thread 0x7fffd77fe700 (LWP 51017)]
0x000055555703b2f3 in ActiveAE::CActiveAEBufferPool::Create(unsigned int) ()
(gdb) bt full
#0  0x000055555703b2f3 in ActiveAE::CActiveAEBufferPool::Create(unsigned int) ()
No symbol table info available.
#1  0x00005555570342fd in ActiveAE::CActiveAE::Configure(AEAudioFormat*) ()
No symbol table info available.
#2  0x000055555703778f in ActiveAE::CActiveAE::StateMachine(int, Actor::Protocol*, Actor::Message*) ()
No symbol table info available.
#3  0x0000555557038743 in ActiveAE::CActiveAE::Process() ()
No symbol table info available.
#4  0x0000555556609331 in CThread::Action() ()
No symbol table info available.
#5  0x000055555660b565 in ?? ()
No symbol table info available.
#6  0x000055555660c08d in ?? ()
No symbol table info available.
#7  0x00007ffff5e02de4 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#8  0x00007ffff7624609 in start_thread (arg=<optimized out>) at pthread_create.c:477
        ret = <optimized out>
        pd = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140736808871680, -8742103893974472751, 140737488345598, 
                140737488345599, 140737488345600, 140736808868928, 8742155572215261137, 8742085113886910417}, 
              mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, 
              canceltype = 0}}}
        not_first_call = 0
#9  0x00007ffff6241163 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
No locals.

```

and then

```
(gdb) continue
Continuing.
Couldn't get registers: No such process.
Couldn't get registers: No such process.
(gdb) [Thread 0x7fffd67fc700 (LWP 51058) exited]
[Thread 0x7fff6cff9700 (LWP 51057) exited]
[Thread 0x7fff6d7fa700 (LWP 51056) exited]
[Thread 0x7fff6dffb700 (LWP 51055) exited]
[Thread 0x7fff6e7fc700 (LWP 51054) exited]
[Thread 0x7fff6effd700 (LWP 51053) exited]
[Thread 0x7fff6f7fe700 (LWP 51052) exited]
[Thread 0x7fff6ffff700 (LWP 51051) exited]
[Thread 0x7fff88c49700 (LWP 51046) exited]
[Thread 0x7fff89ffb700 (LWP 51039) exited]
[Thread 0x7fff8a7fc700 (LWP 51038) exited]
[Thread 0x7fff8affd700 (LWP 51037) exited]
[Thread 0x7fff8bfff700 (LWP 51035) exited]
[Thread 0x7fffa0ff9700 (LWP 51034) exited]
[Thread 0x7fffa17fa700 (LWP 51033) exited]
[Thread 0x7fffa1ffb700 (LWP 51032) exited]
[Thread 0x7fffa27fc700 (LWP 51031) exited]
[Thread 0x7fffa2ffd700 (LWP 51030) exited]
[Thread 0x7fffa37fe700 (LWP 51029) exited]
[Thread 0x7fffa3fff700 (LWP 51028) exited]
[Thread 0x7fffb0f0b700 (LWP 51027) exited]
[Thread 0x7fffb2139700 (LWP 51024) exited]
[Thread 0x7fffb3fff700 (LWP 51023) exited]
[Thread 0x7fffd6ffd700 (LWP 51018) exited]
[Thread 0x7fffd77fe700 (LWP 51017) exited]
[Thread 0x7ffff0d70700 (LWP 51015) exited]
[Thread 0x7ffff1571700 (LWP 51013) exited]
[Thread 0x7ffff15750c0 (LWP 51009) exited]

Program terminated with signal SIGFPE, Arithmetic exception.
The program no longer exists.

```

**Comment by TermeHansen** [comment]
this issue is now fixed in https://github.com/xbmc/inputstream.adaptive/issues/963 

I'll close this issue here then!
