### ISSUE TITLE
v20 TvOS/MacOS - Missing python module error

### ISSUE THREAD

**Issue by eengert** [xbmc/xbmc#21524]
## Bug report
In Kodi Nexus v20 on TvOS and MacOS, addons which rely on the pkg_resources python module error.  

### Describe the bug
I have a clean install of Kodi Nexus v20 on the latest versions of TvOS and MacOS.  I have tested this on both the Alpha 1 release and on a couple of the latest nightly builds.

An example of the problem is when trying to run the addon TextureMaker ( [https://github.com/jurialmunkey/script.texturemaker/releases](https://github.com/jurialmunkey/script.texturemaker/releases) ).  Any time that addon is invoked in v20, it errors and doesn't run.  It looks like a necessary python module is missing.  The addon works fine in Matrix v19 on MacOS and TvOS.   I will attach the debug log from MacOS (the issue is exactly the same on TvOS), but here is what appears to be the relevant portion from the log:

2022-06-08 07:09:11.454 T:3274640   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'ModuleNotFoundError'>
                                                   Error Contents: No module named 'pkg_resources'
                                                   Traceback (most recent call last):
                                                     File "/Users/eengert/Library/Application Support/Kodi/addons/script.texturemaker/script.py", line 5, in <module>
                                                       from resources.lib.script import Script
                                                     File "/Users/eengert/Library/Application Support/Kodi/addons/script.texturemaker/resources/lib/script.py", line 10, in <module>
                                                       from PIL import Image, ImageChops
                                                     File "<frozen zipimport>", line 259, in load_module
                                                     File "/Applications/Kodi.app/Contents/Libraries/lib/python3.9/site-packages/Pillow-8.4.0-py3.9-macosx-10.14-x86_64.egg/PIL/Image.py", line 114, in <module>
                                                       from . import _imaging as core
                                                     File "<frozen zipimport>", line 259, in load_module
                                                     File "/Applications/Kodi.app/Contents/Libraries/lib/python3.9/site-packages/Pillow-8.4.0-py3.9-macosx-10.14-x86_64.egg/PIL/_imaging.py", line 9, in <module>
                                                       __bootstrap__()
                                                     File "/Applications/Kodi.app/Contents/Libraries/lib/python3.9/site-packages/Pillow-8.4.0-py3.9-macosx-10.14-x86_64.egg/PIL/_imaging.py", line 3, in __bootstrap__
                                                       import sys, pkg_resources, importlib.util
                                                   ModuleNotFoundError: No module named 'pkg_resources'
                                                   -->End of Python script error report<--

### To Reproduce

1. Install Kodi v20 Alpha 1 on MacOS or TvOS
2. Install TextureMaker addon (or any addon which relies on the pkg_resources python module)  [https://github.com/jurialmunkey/script.texturemaker/releases](https://github.com/jurialmunkey/script.texturemaker/releases)
3. Try to run the TextureMaker addon

### Debuglog

The debuglog can be found here:  [https://paste.kodi.tv/oponuvoren](https://paste.kodi.tv/oponuvoren)

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x] tvOS
 - [ ] Linux
 - [x] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:  MacOS 12.4 and TvOS 15.5.1
 - Kodi version:  Nexus v20 Alpha 1

**Comment by fuzzard** [comment]
Can you try one of the jenkins outputs (osx or tvos) from https://github.com/xbmc/xbmc/pull/21534 once they build.

**Comment by eengert** [comment]
The MacOS version solve the issue and is working properly now.

The TvOS version didn't solve the issue.  Looks like the included module is for the MacOS architecture, not TvOS.  Here is the new error:

2022-06-10 08:07:49.095 T:301639   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'ImportError'>
                                                   Error Contents: dlopen(/private/var/containers/Bundle/Application/9369CBB9-1A83-4759-905A-BCD86AE682A5/Kodi.app/AppData/AppHome/addons/script.module.pil/lib/PIL/_imaging.cpython-39-darwin.so, 0x0002): tried: '/private/var/containers/Bundle/Application/9369CBB9-1A83-4759-905A-BCD86AE682A5/Kodi.app/AppData/AppHome/addons/script.module.pil/lib/PIL/_imaging.cpython-39-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e'))
                                                   Traceback (most recent call last):
                                                     File "/private/var/mobile/Containers/Data/Application/93697879-648C-4FC2-B619-E3C3B0AE4B99/Library/Caches/Kodi/addons/script.texturemaker/script.py", line 5, in <module>
                                                       from resources.lib.script import Script
                                                     File "/private/var/mobile/Containers/Data/Application/93697879-648C-4FC2-B619-E3C3B0AE4B99/Library/Caches/Kodi/addons/script.texturemaker/resources/lib/script.py", line 10, in <module>
                                                       from PIL import Image, ImageChops
                                                     File "/private/var/containers/Bundle/Application/9369CBB9-1A83-4759-905A-BCD86AE682A5/Kodi.app/AppData/AppHome/addons/script.module.pil/lib/PIL/Image.py", line 114, in <module>
                                                       from . import _imaging as core
                                                   ImportError: dlopen(/private/var/containers/Bundle/Application/9369CBB9-1A83-4759-905A-BCD86AE682A5/Kodi.app/AppData/AppHome/addons/script.module.pil/lib/PIL/_imaging.cpython-39-darwin.so, 0x0002): tried: '/private/var/containers/Bundle/Application/9369CBB9-1A83-4759-905A-BCD86AE682A5/Kodi.app/AppData/AppHome/addons/script.module.pil/lib/PIL/_imaging.cpython-39-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e'))
                                                   -->End of Python script error report<--

**Comment by fuzzard** [comment]
No

**Comment by bigretromike** [comment]
I just tested build from your PR, it did not helped. I had hopes because the original issue was also around PIL module thanks anyway

**Comment by eengert** [comment]
I tried this build just now, but still getting the same error.

[https://jenkins.kodi.tv/job/TVOS/10731/artifact/tools/darwin/packaging/tvos/kodi-20220611-d042aa7d-PR21534-10731-tvos.deb](https://jenkins.kodi.tv/job/TVOS/10731/artifact/tools/darwin/packaging/tvos/kodi-20220611-d042aa7d-PR21534-10731-tvos.deb)


2022-06-11 09:32:07.233 T:611151   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'ImportError'>
                                                   Error Contents: dlopen(/private/var/containers/Bundle/Application/821C454D-5661-4224-A8BA-C4D3AE57D375/Kodi.app/AppData/AppHome/addons/script.module.pil/lib/PIL/_imaging.cpython-39-darwin.so, 0x0002): tried: '/private/var/containers/Bundle/Application/821C454D-5661-4224-A8BA-C4D3AE57D375/Kodi.app/AppData/AppHome/addons/script.module.pil/lib/PIL/_imaging.cpython-39-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e'))
                                                   Traceback (most recent call last):
                                                     File "/private/var/mobile/Containers/Data/Application/00C3CC4F-F229-42CE-AFEF-B54112E511DA/Library/Caches/Kodi/addons/script.texturemaker/script.py", line 5, in <module>
                                                       from resources.lib.script import Script
                                                     File "/private/var/mobile/Containers/Data/Application/00C3CC4F-F229-42CE-AFEF-B54112E511DA/Library/Caches/Kodi/addons/script.texturemaker/resources/lib/script.py", line 10, in <module>
                                                       from PIL import Image, ImageChops
                                                     File "/private/var/containers/Bundle/Application/821C454D-5661-4224-A8BA-C4D3AE57D375/Kodi.app/AppData/AppHome/addons/script.module.pil/lib/PIL/Image.py", line 114, in <module>
                                                       from . import _imaging as core
                                                   ImportError: dlopen(/private/var/containers/Bundle/Application/821C454D-5661-4224-A8BA-C4D3AE57D375/Kodi.app/AppData/AppHome/addons/script.module.pil/lib/PIL/_imaging.cpython-39-darwin.so, 0x0002): tried: '/private/var/containers/Bundle/Application/821C454D-5661-4224-A8BA-C4D3AE57D375/Kodi.app/AppData/AppHome/addons/script.module.pil/lib/PIL/_imaging.cpython-39-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e'))
                                                   -->End of Python script error report<--

**Comment by eengert** [comment]
This error doesn’t occur in Matrix 19.3 or 19.4 on the same Apple TV. I’m able to run this skin and the TextureMaker addon with no errors and they work as expected. Not sure if that helps but maybe grab the same pil module that’s used in Matrix?

**Comment by eengert** [comment]
Just wondering if anyone is still working on this?  Please let me know if I can provide any more information that would help get the correct library added. Thanks.

**Comment by fuzzard** [comment]
I'm aware, that's why the issue is still open, no there's nothing I need from you at this time.

**Comment by fuzzard** [comment]
@eengert can you please test the artifacts from #21573 

ios - https://jenkins.kodi.tv/job/IOS-ARM64/19803/artifact/tools/darwin/packaging/ios/kodi-20220618-91d2d9e0-PR21573-19803-ios64.deb
tvos - https://jenkins.kodi.tv/job/TVOS/10809/artifact/tools/darwin/packaging/tvos/kodi-20220618-91d2d9e0-PR21573-10809-tvos.deb

**Comment by eengert** [comment]
This fixes the problem on TvOS. Thanks!
