### ISSUE TITLE
Cannot play videos on CuriosityStream addon from Kodi addon repository

### ISSUE THREAD

**Issue by sdaau** [xbmc/xbmc#21993]
## Bug report

Apologies if I'm reporting at the wrong place; https://kodi.tv/addons/matrix/plugin.video.curiositystream mentions https://github.com/GMaxera/repo-plugins/tree/curiositystream-leia/plugin.video.curiositystream ; but that repo has no Github issues.

I cannot watch any more videos (I'm a subscriber) on Curiosity Stream addon, installed from the Kodi addon repository, with current version GMaxera-2.0.2+matrix.2

![image](https://user-images.githubusercontent.com/26737749/194413842-06939e87-a8fb-47d7-9e36-2fe332ef95bf.png)

### Describe the bug
Here is a clear and concise description of what the problem is:

When I use this addon, I can list CuriosityStream videos fine in Kodi:

![image](https://user-images.githubusercontent.com/26737749/194412430-ad2f99f5-fa13-492b-a118-8d0c1bec4b6f.png)

... however, I cannot play any video:

![image](https://user-images.githubusercontent.com/26737749/194412546-f1f286cc-ec18-4c09-98c1-eafc1254e9f7.png)

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

When I click on a video to play it, it should play.

## Actual Behavior

I get "Playback failed: One or more items failed to play. Check the log for more information about this message"

## Possible Fix

None

### To Reproduce

1. Create an account at CuriosityStream
2. Install CuriosityStream addon from Kodi Addons in Kodi 19.4 on Android 9
3. Enter your CuriosityStream credentials in the CuriosityStream addon settings
4. Enter the addon
5. Try to play any of the listed videos

### Debuglog

The debuglog can be found here:

The only thing I can see relevant is this:

```
2022-10-06 22:13:11.386 T:21885    INFO <general>: initializing python engine.
2022-10-06 22:13:15.822 T:21885    INFO <general>: CPythonInvoker(6, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.curiositystream/main.py): script successfully run
2022-10-06 22:13:16.442 T:21885    INFO <general>: Python interpreter stopped
2022-10-06 22:13:26.985 T:22560    INFO <general>: initializing python engine.
2022-10-06 22:13:39.368 T:22560    INFO <general>: CPythonInvoker(7, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.curiositystream/main.py): script successfully run
2022-10-06 22:13:40.593 T:22560    INFO <general>: Python interpreter stopped
2022-10-06 22:13:45.963 T:24253    INFO <general>: initializing python engine.
2022-10-06 22:13:54.716 T:24253    INFO <general>: CPythonInvoker(8, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.curiositystream/main.py): script successfully run
2022-10-06 22:13:56.013 T:24253    INFO <general>: Python interpreter stopped
2022-10-06 22:13:59.596 T:25335    INFO <general>: initializing python engine.
2022-10-06 22:14:04.568 T:13265    INFO <general>: Loading skin file: DialogConfirm.xml, load type: KEEP_IN_MEMORY
2022-10-06 22:14:05.339 T:25335   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'IndexError'>
                                                   Error Contents: list index out of range
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.curiositystream/main.py", line 6, in <module>
                                                       router.route(sys.argv[2])
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.curiositystream/resources/lib/router.py", line 78, in route
                                                       self._play_media(params["media"])
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.curiositystream/resources/lib/router.py", line 234, in _play_media
                                                       play_item = xbmcgui.ListItem(path=stream["streams"][0]["master_playlist_url"])
                                                   IndexError: list index out of range
                                                   -->End of Python script error report<--
                                                   
2022-10-06 22:14:06.609 T:25335    INFO <general>: Python interpreter stopped
2022-10-06 22:14:06.627 T:13265   ERROR <general>: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.curiositystream/?action=play&media=4544]
...
2022-10-06 22:29:13.142 T:30549    INFO <general>: initializing python engine.
2022-10-06 22:29:18.637 T:30549   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'KeyError'>
                                                   Error Contents: 'is_bookmarked'
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.curiositystream/main.py", line 6, in <module>
                                                       router.route(sys.argv[2])
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.curiositystream/resources/lib/router.py", line 76, in route
                                                       self._list_media_or_collections(action, parent, page)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.curiositystream/resources/lib/router.py", line 206, in _list_media_or_collections
                                                       tr(30023) if m["is_bookmarked"] else tr(30024),
                                                   KeyError: 'is_bookmarked'
                                                   -->End of Python script error report<--
                                                   
2022-10-06 22:29:19.730 T:30549    INFO <general>: Python interpreter stopped
2022-10-06 22:29:19.748 T:30548   ERROR <general>: GetDirectory - Error getting plugin://plugin.video.curiositystream/?action=list_collections2
2022-10-06 22:29:19.760 T:13265   ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.curiositystream/?action=list_collections2) failed
```

### Screenshots 
Here are some links or screenshots to help explain the problem:

See above.

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Android 9
 - Kodi version: 19.4

![image](https://user-images.githubusercontent.com/26737749/194414303-3f9a816e-31a2-42ae-997e-638e6a8984a3.png)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by fuzzard** [comment]
There may be a thread on the forums you can post to.
This issue tracker isn't for add-ons, only the core app.
