### ISSUE TITLE
service.xbmc.versioncheck - Command '('lsb_release', '-a')' returned non-zero exit status 3

### ISSUE THREAD

**Issue by craigcarnell** [xbmc/xbmc#22570]
### Describe the bug
service.xbmc.versioncheck will throw a python exception when performing a version check at Kodi boot, this is due to this distribution not supplying anything with lsb_release, I am cross-compiling to this arm board.

lsb_release -a
```
LSB Version:	n/a
Distributor ID:	n/a
Description:	(none)
Release:	n/a
Codename:	n/a
```

The following code at (https://github.com/xbmc/xbmc/blob/master/addons/service.xbmc.versioncheck/resources/lib/version_check/service.py#L44)
should check for empty string / null before assuming it returned something valid.
```
DISTRIBUTION = distro.linux_distribution(full_distribution_name=False)[0].lower()
```

## Expected Behavior
No exception thrown

## Actual Behavior
Throws the exception in logs below in kodi.log

## Possible Fix
See above

### To Reproduce
1. return empty or null string with lsb_release -a

### Debuglog
```
2023-01-21 19:28:06.318 T:15281   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'subprocess.CalledProcessError'>
                                                   Error Contents: Command '('lsb_release', '-a')' returned non-zero exit status 3.
                                                   Traceback (most recent call last):
                                                     File "/media/developer/tmp/kodi-build/addons/service.xbmc.versioncheck/resources/lib/runner.py", line 14, in <module>
                                                       from version_check import service  # pylint: disable=import-error
                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/media/developer/tmp/kodi-build/addons/service.xbmc.versioncheck/resources/lib/version_check/service.py", line 44, in <module>
                                                       DISTRIBUTION = distro.linux_distribution(full_distribution_name=False)[0].lower()
                                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/media/developer/tmp/kodi-build/addons/service.xbmc.versioncheck/resources/lib/version_check/distro/distro.py", line 122, in linux_distribution
                                                       return _distro.linux_distribution(full_distribution_name)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/media/developer/tmp/kodi-build/addons/service.xbmc.versioncheck/resources/lib/version_check/distro/distro.py", line 676, in linux_distribution
                                                       self.name() if full_distribution_name else self.id(),
                                                                                                  ^^^^^^^^^
                                                     File "/media/developer/tmp/kodi-build/addons/service.xbmc.versioncheck/resources/lib/version_check/distro/distro.py", line 694, in id
                                                       distro_id = self.lsb_release_attr('distributor_id')
                                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/media/developer/tmp/kodi-build/addons/service.xbmc.versioncheck/resources/lib/version_check/distro/distro.py", line 899, in lsb_release_attr
                                                       return self._lsb_release_info.get(attribute, '')
                                                              ^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/media/developer/tmp/kodi-build/addons/service.xbmc.versioncheck/resources/lib/version_check/distro/distro.py", line 552, in __get__
                                                       ret = obj.__dict__[self._fname] = self._f(obj)
                                                                                         ^^^^^^^^^^^^
                                                     File "/media/developer/tmp/kodi-build/addons/service.xbmc.versioncheck/resources/lib/version_check/distro/distro.py", line 1012, in _lsb_release_info
                                                       stdout = subprocess.check_output(cmd, stderr=devnull)
                                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/media/developer/opt/xbmc-deps/arm-linux-gnueabi-release/lib/python3.11/subprocess.py", line 466, in check_output
                                                       return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/media/developer/opt/xbmc-deps/arm-linux-gnueabi-release/lib/python3.11/subprocess.py", line 571, in run
                                                       raise CalledProcessError(retcode, process.args,
                                                   subprocess.CalledProcessError: Command '('lsb_release', '-a')' returned non-zero exit status 3.
                                                   -->End of Python script error report<--
                                                   

```

### Your Environment
Used Operating system:

 - [x] Linux

 - Kodi version: master

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by craigcarnell** [comment]
@enen92 That repo does not have issues enabled.

**Comment by enen92** [comment]
please check again :)

**Comment by craigcarnell** [comment]
@enen92 Done thanks
