### ISSUE TITLE
Sometimes, on enter a replay the Audio of the whole Kodi break. Reboot needed.

### ISSUE THREAD

**Issue by Mannshoch** [xbmc/xbmc#22759]
### Describe the bug
Sometimes, on enter a replay the Audio of the whole Kodi break. Reboot needed.
Addon developper redirected this error to kodi https://github.com/rbuehlma/pvr.zattoo/issues/163

## Expected Behavior
Audio still works.

## Actual Behavior
Audio Breaks the whole System.

### To Reproduce

1. Start a PVR replay 
2. The Replay has no audio. 

### Debuglog

<Details>

```
2023-02-11 17:38:28.159 T:1510  WARNING <general>: Unable to determine channel type. Defaulting to TV.
2023-02-11 17:38:59.509 T:1510     INFO <general>: Skipped 1 duplicate messages..
2023-02-11 17:38:59.509 T:1510  WARNING <general>: Unable to determine channel type. Defaulting to TV.
2023-02-11 17:39:17.269 T:991      INFO <general>: Skipped 1 duplicate messages..
2023-02-11 17:39:17.269 T:991     ERROR <general>: Control 50 in window 10704 has been asked to focus, but it can't
2023-02-11 17:39:30.026 T:1510  WARNING <general>: Unable to determine channel type. Defaulting to TV.
2023-02-11 17:39:43.924 T:1510     INFO <general>: Skipped 1 duplicate messages..
2023-02-11 17:39:43.924 T:1510  WARNING <general>: Unable to determine channel type. Defaulting to TV.
2023-02-11 17:39:57.658 T:1510  WARNING <general>: Unable to determine channel type. Defaulting to TV.
2023-02-11 17:42:06.704 T:991      INFO <general>: Skipped 1 duplicate messages..
2023-02-11 17:42:06.704 T:991      INFO <general>: Loading skin file: DialogPVRInfo.xml, load type: LOAD_EVERY_TIME
2023-02-11 17:42:09.658 T:991      INFO <general>: VideoPlayer::OpenFile: pvr://guide/0036/2023-02-11 15:45:00.epg
2023-02-11 17:42:09.662 T:4233     INFO <general>: Creating InputStream
2023-02-11 17:42:09.663 T:4233     INFO <general>: AddOnLog: inputstream.adaptive: SetVideoResolution (1920 x 1080)
2023-02-11 17:42:09.692 T:4233     INFO <general>: AddOnLog: inputstream.adaptive: Successfully parsed manifest file. #Periods: 1, #Streams in first period: 2, Type: VOD, Download speed: 0.0000 Bytes/s
2023-02-11 17:42:09.759 T:1466     INFO <general>: Librespot: Kodi playback started
2023-02-11 17:42:10.022 T:32024    INFO <general>: Librespot: suspended sink 1
2023-02-11 17:42:10.022 T:32024    INFO <general>: Librespot: librespot stopped
2023-02-11 17:42:10.023 T:32024    INFO <general>: Librespot: librespot thread stopped
2023-02-11 17:42:10.344 T:4233     INFO <general>: Creating Demuxer
2023-02-11 17:42:10.345 T:4233     INFO <general>: Opening stream: 1001 source: 256
2023-02-11 17:42:10.351 T:4233     INFO <general>: Creating video codec with codec id: 27
2023-02-11 17:42:10.351 T:4233     INFO <general>: CDVDVideoCodecFFmpeg::Open() Using codec: H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
2023-02-11 17:42:10.352 T:4233     INFO <general>: Creating video thread
2023-02-11 17:42:10.352 T:4239     INFO <general>: running thread: video_thread
2023-02-11 17:42:10.353 T:4233     INFO <general>: Opening stream: 1002 source: 256
2023-02-11 17:42:10.359 T:4233     INFO <general>: Finding audio codec for: 86018
2023-02-11 17:42:10.360 T:4233     INFO <general>: CDVDAudioCodecFFmpeg::Open() Successful opened audio decoder aac
2023-02-11 17:42:10.360 T:4233     INFO <general>: Creating audio thread
2023-02-11 17:42:10.361 T:4241     INFO <general>: running thread: CVideoPlayerAudio::Process()
2023-02-11 17:42:10.361 T:4233     INFO <general>: AddOnLog: inputstream.adaptive: PosTime (300000)
2023-02-11 17:42:10.377 T:4233     INFO <general>: AddOnLog: inputstream.adaptive: seekTime(300.0) for Stream:1 continues at 300.8 (PTS: 300840000)
2023-02-11 17:42:10.396 T:4233     INFO <general>: AddOnLog: inputstream.adaptive: seekTime(300.8) for Stream:2 continues at 300.8 (PTS: 300821333)
2023-02-11 17:42:10.413 T:4241     INFO <general>: CDVDAudioCodecFFmpeg::Open() Successful opened audio decoder aac
2023-02-11 17:42:10.413 T:4241     INFO <general>: Creating audio stream (codec id: 86018, channels: 2, sample rate: 48000, no pass-through)
2023-02-11 17:42:10.418 T:4239     INFO <general>: CDVDVideoCodecFFmpeg::Open() Using codec: H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
2023-02-11 17:42:10.474 T:991      INFO <general>: GLES: Selecting single pass rendering
2023-02-11 17:42:10.474 T:991      INFO <general>: GLES: Selecting YUV 2 RGB shader
2023-02-11 17:42:11.619 T:4241    ERROR <general>: CDVDAudio::AddPacketsRenderer - timeout adding data to renderer
2023-02-11 17:42:12.414 T:1044    ERROR <general>: ActiveAE::FlushEngine - failed to flush
2023-02-11 17:42:12.826 T:4241    ERROR <general>: CDVDAudio::AddPacketsRenderer - timeout adding data to renderer
2023-02-11 17:42:17.414 T:1044     INFO <general>: Skipped 3 duplicate messages..
2023-02-11 17:42:17.414 T:1044    ERROR <general>: ActiveAE::InitSink - failed to init
2023-02-11 17:42:17.414 T:1044  WARNING <general>: CActiveAE::StateMachine - signal: 11 from port: OutputControlPort not handled for state: 2
2023-02-11 17:42:17.419 T:1044  WARNING <general>: CActiveAE::StateMachine - signal: 12 from port: OutputControlPort not handled for state: 2
2023-02-11 17:42:17.419 T:1044  WARNING <general>: CActiveAE::StateMachine - signal: 7 from port: OutputControlPort not handled for state: 2
2023-02-11 17:42:17.650 T:4241    ERROR <general>: CDVDAudio::AddPacketsRenderer - timeout adding data to renderer
2023-02-11 17:42:18.189 T:4239     INFO <general>: CDVDVideoCodecFFmpeg::CDropControl: calculated diff time: 40000
2023-02-11 17:42:19.947 T:4241    ERROR <general>: CDVDAudio::AddPacketsRenderer - timeout adding data to renderer
2023-02-11 17:42:20.120 T:991      INFO <general>: CVideoPlayer::CloseFile()
2023-02-11 17:42:20.122 T:991      INFO <general>: VideoPlayer: waiting for threads to exit
2023-02-11 17:42:20.130 T:4233     INFO <general>: CVideoPlayer::OnExit()
2023-02-11 17:42:20.130 T:4233     INFO <general>: Closing stream player 1
2023-02-11 17:42:20.130 T:4233     INFO <general>: Waiting for audio thread to exit
2023-02-11 17:42:20.590 T:4239  WARNING <general>: OutputPicture - timeout waiting for buffer
2023-02-11 17:42:21.958 T:4241    ERROR <general>: CDVDAudio::AddPacketsRenderer - timeout adding data to renderer
2023-02-11 17:42:21.958 T:4241     INFO <general>: thread end: CVideoPlayerAudio::OnExit()
2023-02-11 17:42:21.958 T:4233     INFO <general>: Closing audio device
2023-02-11 17:42:23.959 T:4233    ERROR <general>: CActiveAE::FreeStream - failed
2023-02-11 17:42:23.960 T:4233     INFO <general>: Deleting audio codec
2023-02-11 17:42:23.960 T:1044    ERROR <general>: ActiveAE::FlushEngine - failed to flush
2023-02-11 17:42:23.961 T:4233     INFO <general>: Closing stream player 2
2023-02-11 17:42:23.962 T:4233     INFO <general>: waiting for video thread to exit
2023-02-11 17:42:23.962 T:4239    ERROR <general>: Got MSGQ_ABORT or MSGO_IS_ERROR return true
2023-02-11 17:42:23.962 T:4239     INFO <general>: thread end: video_thread
2023-02-11 17:42:23.962 T:4233     INFO <general>: deleting video codec
2023-02-11 17:42:23.969 T:4233     INFO <general>: ADDON: Dll Destroyed - InputStream Adaptive
2023-02-11 17:42:23.973 T:991      INFO <general>: VideoPlayer: finished waiting
2023-02-11 17:42:23.973 T:991      INFO <general>: CVideoPlayer::CloseFile()
2023-02-11 17:42:23.973 T:991      INFO <general>: VideoPlayer: waiting for threads to exit
2023-02-11 17:42:23.974 T:991      INFO <general>: VideoPlayer: finished waiting
2023-02-11 17:42:24.227 T:1466     INFO <general>: Librespot: Kodi playback stopped
2023-02-11 17:42:24.228 T:4257     INFO <general>: Librespot: librespot thread started
2023-02-11 17:42:24.302 T:4257     INFO <general>: Librespot: librespot started
2023-02-11 17:42:24.375 T:4257     INFO <general>: Librespot: [2023-02-11T16:42:24Z INFO  librespot] librespot 0.3.1 1d5c210b2d (Built on 2021-12-24, Build ID: 9ivxgKm5, Profile: release)
2023-02-11 17:42:24.393 T:4257     INFO <general>: Librespot: *** WARNING *** The program 'librespot' uses the Apple Bonjour compatibility layer of Avahi.
2023-02-11 17:42:24.394 T:4257     INFO <general>: Librespot: *** WARNING *** Please fix your application to use the native API of Avahi!
2023-02-11 17:42:24.394 T:4257     INFO <general>: Librespot: *** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
2023-02-11 17:42:26.064 T:1044    ERROR <general>: ActiveAE::FlushEngine - failed to flush
2023-02-11 17:42:31.064 T:1044    ERROR <general>: ActiveAE::InitSink - failed to init
2023-02-11 17:42:35.068 T:991      INFO <general>: Loading skin file: DialogButtonMenu.xml, load type: KEEP_IN_MEMORY
2023-02-11 17:42:39.257 T:991      INFO <general>: Saving exitCode 66
2023-02-11 17:42:39.300 T:1483     INFO <general>: WebSocket: connection closed by client
2023-02-11 17:42:39.331 T:1483     INFO <general>: JSONRPC Server: Disconnection detected
2023-02-11 17:42:39.491 T:4257     INFO <general>: Librespot: suspended sink 1
2023-02-11 17:42:39.492 T:4257     INFO <general>: Librespot: librespot stopped
2023-02-11 17:42:39.560 T:4257     INFO <general>: Librespot: librespot started
2023-02-11 17:42:39.565 T:4257     INFO <general>: Librespot: [2023-02-11T16:42:39Z INFO  librespot] librespot 0.3.1 1d5c210b2d (Built on 2021-12-24, Build ID: 9ivxgKm5, Profile: release)
2023-02-11 17:42:39.579 T:4257     INFO <general>: Librespot: *** WARNING *** The program 'librespot' uses the Apple Bonjour compatibility layer of Avahi.
2023-02-11 17:42:39.581 T:4257     INFO <general>: Librespot: *** WARNING *** Please fix your application to use the native API of Avahi!
2023-02-11 17:42:39.581 T:4257     INFO <general>: Librespot: *** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
2023-02-11 17:42:39.936 T:991      INFO <general>: Quitting due to POSIX signal
2023-02-11 17:42:39.970 T:991      INFO <general>: Stopping player
2023-02-11 17:42:39.971 T:991      INFO <general>: Storing total System Uptime
2023-02-11 17:42:39.971 T:991      INFO <general>: Saving settings
2023-02-11 17:42:39.987 T:991      INFO <general>: Saving skin settings
2023-02-11 17:42:39.998 T:991      INFO <general>: Stopping all
2023-02-11 17:42:39.999 T:991      INFO <general>: ES: Stopping event server
2023-02-11 17:42:40.000 T:991      INFO <general>: AIRPLAY: Cleaning up photoassetcache
2023-02-11 17:42:40.130 T:991      INFO <general>: stopping upnp
2023-02-11 17:42:40.208 T:1482     INFO <general>: ES: UDP Event server stopped
2023-02-11 17:42:40.438 T:1508    ERROR <general>: Exception ignored on calling ctypes callback function
2023-02-11 17:42:40.439 T:1508    ERROR <general>: : 
2023-02-11 17:42:40.439 T:1508    ERROR <general>: <function Connection.add_filter.<locals>.wrap_function at 0xe566d360>
2023-02-11 17:42:40.439 T:1508    ERROR <general>: 
                                                   
2023-02-11 17:42:40.439 T:1508    ERROR <general>: Traceback (most recent call last):
                                                   
2023-02-11 17:42:40.439 T:1508    ERROR <general>:   File "/usr/lib/python3.8/site-packages/dbussy.py", line 2573, in wrap_function
                                                   
2023-02-11 17:42:40.440 T:1508    ERROR <general>:   File "/usr/lib/python3.8/site-packages/ravel.py", line 1992, in _message_interface_dispatch
                                                   
2023-02-11 17:42:40.440 T:1508    ERROR <general>:   File "/usr/share/kodi/addons/service.libreelec.settings/resources/lib/dbus_bluez.py", line 68, in Release
                                                   
2023-02-11 17:42:40.441 T:1508    ERROR <general>: NotImplementedError
2023-02-11 17:42:40.441 T:1508    ERROR <general>: : 
2023-02-11 17:42:40.441 T:1508    ERROR <general>: 
2023-02-11 17:42:40.441 T:1508    ERROR <general>: 
                                                   
2023-02-11 17:42:40.487 T:991      INFO <general>: stopping zeroconf publishing
2023-02-11 17:42:40.496 T:991      INFO <CWebserver[8080]>: Stopped
2023-02-11 17:42:40.496 T:991      INFO <general>: AIRPLAY: Cleaning up photoassetcache
2023-02-11 17:42:40.612 T:991      INFO <general>: stop dvd detect media
2023-02-11 17:42:40.613 T:991      INFO <general>: Stopping zeroconf browser
2023-02-11 17:42:40.634 T:991      INFO <general>: CServiceAddonManager: failed to stop inputstream.ffmpegdirect (may have ended)
2023-02-11 17:42:40.694 T:1459     INFO <general>: CPythonInvoker(1, /storage/.kodi/addons/plugin.video.youtube/resources/lib/startup.py): script successfully run
2023-02-11 17:42:41.041 T:1459     INFO <general>: Python interpreter interrupted by user
2023-02-11 17:42:41.085 T:1463     INFO <general>: CPythonInvoker(2, /storage/.kodi/addons/script.module.tubed.api/resources/lib/service.py): script successfully run
2023-02-11 17:42:41.357 T:1463     INFO <general>: Python interpreter interrupted by user
2023-02-11 17:42:41.566 T:1464     INFO <general>: CPythonInvoker(3, /storage/.kodi/addons/script.xbmcbackup/service.py): script successfully run
2023-02-11 17:42:41.891 T:1464     INFO <general>: Python interpreter interrupted by user
2023-02-11 17:42:41.954 T:1576     INFO <general>: SETTINGS: run # updateThread Stopped
2023-02-11 17:42:41.955 T:1578     INFO <general>: SETTINGS: run # Received exit
2023-02-11 17:42:42.421 T:1465     INFO <general>: CPythonInvoker(4, /usr/share/kodi/addons/service.libreelec.settings/service.py): script successfully run
2023-02-11 17:42:42.568 T:1465     INFO <general>: Python interpreter interrupted by user
2023-02-11 17:42:42.568 T:1466     INFO <general>: Librespot: monitor aborted
2023-02-11 17:42:42.648 T:4257     INFO <general>: Librespot: suspended sink 1
2023-02-11 17:42:42.649 T:4257     INFO <general>: Librespot: librespot stopped
2023-02-11 17:42:42.649 T:4257     INFO <general>: Librespot: librespot thread stopped
2023-02-11 17:42:42.795 T:1466     INFO <general>: Librespot: unloaded module-rtp-send destination_ip=127.0.0.1 port=24642 source=librespot.monitor
2023-02-11 17:42:42.865 T:1466     INFO <general>: Librespot: unloaded module-null-sink sink_name=librespot
2023-02-11 17:42:42.865 T:1466     INFO <general>: Librespot: monitor stopped
2023-02-11 17:42:42.866 T:1466     INFO <general>: CPythonInvoker(5, /storage/.kodi/addons/service.librespot/default.py): script successfully run
2023-02-11 17:42:42.870 T:1045    ERROR <general>: Sink Timer expired for more than buffer time: 300l
2023-02-11 17:42:42.871 T:1044  WARNING <general>: Pulseaudio module module-allow-passthrough not loaded - opening PT devices might fail
2023-02-11 17:42:42.872 T:1044     INFO <general>: Found 1 Lists of Devices
2023-02-11 17:42:42.872 T:1044     INFO <general>: Enumerated PULSE devices:
2023-02-11 17:42:42.872 T:1044     INFO <general>:     Device 1
2023-02-11 17:42:42.872 T:1044     INFO <general>:         m_deviceName      : Default
2023-02-11 17:42:42.872 T:1044     INFO <general>:         m_displayName     : Default
2023-02-11 17:42:42.872 T:1044     INFO <general>:         m_displayNameExtra: Bluetooth Audio (PULSEAUDIO)
2023-02-11 17:42:42.872 T:1044     INFO <general>:         m_deviceType      : AE_DEVTYPE_PCM
2023-02-11 17:42:42.872 T:1044     INFO <general>:         m_channels        : FL, FR
2023-02-11 17:42:42.872 T:1044     INFO <general>:         m_sampleRates     : 5512,8000,11025,16000,22050,32000,44100,48000,64000,88200,96000,176400,192000,384000
2023-02-11 17:42:42.872 T:1044     INFO <general>:         m_dataFormats     : AE_FMT_U8,AE_FMT_S16NE,AE_FMT_S24NE3,AE_FMT_S24NE4,AE_FMT_S32NE,AE_FMT_FLOAT
2023-02-11 17:42:42.872 T:1044     INFO <general>:         m_streamTypes     : No passthrough capabilities
2023-02-11 17:42:43.002 T:1466     INFO <general>: Python interpreter interrupted by user
2023-02-11 17:42:43.002 T:1467     INFO <general>: CPythonInvoker(6, /storage/.kodi/addons/service.snapclient/default.py): script successfully run
2023-02-11 17:42:43.047 T:1467     INFO <general>: Python interpreter interrupted by user
2023-02-11 17:42:43.048 T:1468     INFO <general>: CPythonInvoker(7, /storage/.kodi/addons/service.snapserver/default.py): script successfully run
2023-02-11 17:42:43.086 T:1468     INFO <general>: Python interpreter interrupted by user
2023-02-11 17:42:43.302 T:1469     INFO <general>: CPythonInvoker(8, /storage/.kodi/addons/service.system.docker/default.py): script successfully run
2023-02-11 17:42:43.344 T:1469     INFO <general>: Python interpreter interrupted by user
2023-02-11 17:42:43.501 T:1045    ERROR <general>: Sink Timer expired for more than buffer time: 300l
2023-02-11 17:42:44.873 T:1044     INFO <general>: Skipped 1 duplicate messages..
2023-02-11 17:42:44.872 T:1044    ERROR <general>: ActiveAE::UnconfigureSink - failed to unconfigure
2023-02-11 17:42:45.424 T:1045    ERROR <general>: Sink Timer expired for more than buffer time: 300l
2023-02-11 17:42:46.873 T:1044    ERROR <general>: ActiveAE::FlushEngine - failed to flush
2023-02-11 17:42:46.927 T:1045    ERROR <general>: Sink Timer expired for more than buffer time: 300l
2023-02-11 17:42:46.977 T:1045    ERROR <general>: CActiveAESink::OutputSamples - failed
2023-02-11 17:42:46.984 T:1045     INFO <general>: CActiveAESink::OpenSink - initialize sink
2023-02-11 17:42:46.985 T:1045     INFO <general>: CAESinkALSA::Initialize - Attempting to open device "hdmi:CARD=vc4hdmi0,DEV=0"
2023-02-11 17:42:46.994 T:1045     INFO <general>: CAESinkALSA::Initialize - Opened device "hdmi:CARD=vc4hdmi0,DEV=0,AES0=0x04,AES1=0x82,AES2=0x00,AES3=0x00"
2023-02-11 17:42:46.996 T:1045     INFO <general>: CAESinkALSA::InitializeHW - Your hardware does not support AE_FMT_FLOAT, trying other formats
2023-02-11 17:42:46.996 T:1045     INFO <general>: CAESinkALSA::InitializeHW - Using data format AE_FMT_S24NE3
2023-02-11 17:42:47.000 T:1045     INFO <general>: CActiveAESink::OpenSink - initialize sink
2023-02-11 17:42:47.002 T:1045     INFO <general>: CAESinkALSA::Initialize - Attempting to open device "hdmi:CARD=vc4hdmi0,DEV=0"
2023-02-11 17:42:47.010 T:1045     INFO <general>: CAESinkALSA::Initialize - Opened device "hdmi:CARD=vc4hdmi0,DEV=0,AES0=0x04,AES1=0x82,AES2=0x00,AES3=0x00"
2023-02-11 17:42:47.012 T:1045     INFO <general>: CAESinkALSA::InitializeHW - Your hardware does not support AE_FMT_FLOAT, trying other formats
2023-02-11 17:42:47.012 T:1045     INFO <general>: CAESinkALSA::InitializeHW - Using data format AE_FMT_S24NE3
2023-02-11 17:42:47.015 T:1045     INFO <general>: CActiveAESink::OpenSink - initialize sink
2023-02-11 17:42:47.016 T:1045     INFO <general>: CAESinkALSA::Initialize - Attempting to open device "hdmi:CARD=vc4hdmi0,DEV=0"
2023-02-11 17:42:47.024 T:1045     INFO <general>: CAESinkALSA::Initialize - Opened device "hdmi:CARD=vc4hdmi0,DEV=0,AES0=0x04,AES1=0x82,AES2=0x00,AES3=0x02"
2023-02-11 17:42:47.025 T:1045     INFO <general>: CAESinkALSA::InitializeHW - Your hardware does not support AE_FMT_FLOAT, trying other formats
2023-02-11 17:42:47.025 T:1045     INFO <general>: CAESinkALSA::InitializeHW - Using data format AE_FMT_S24NE3
2023-02-11 17:42:47.029 T:1045     INFO <general>: CActiveAESink::OpenSink - initialize sink
2023-02-11 17:42:47.030 T:1045     INFO <general>: CAESinkALSA::Initialize - Attempting to open device "hdmi:CARD=vc4hdmi0,DEV=0"
2023-02-11 17:42:47.038 T:1045     INFO <general>: CAESinkALSA::Initialize - Opened device "hdmi:CARD=vc4hdmi0,DEV=0,AES0=0x04,AES1=0x82,AES2=0x00,AES3=0x00"
2023-02-11 17:42:47.039 T:1045     INFO <general>: CAESinkALSA::InitializeHW - Your hardware does not support AE_FMT_FLOAT, trying other formats
2023-02-11 17:42:47.039 T:1045     INFO <general>: CAESinkALSA::InitializeHW - Using data format AE_FMT_S24NE3
2023-02-11 17:42:47.043 T:1045     INFO <general>: CActiveAESink::OpenSink - initialize sink
2023-02-11 17:42:47.044 T:1045     INFO <general>: CAESinkALSA::Initialize - Attempting to open device "hdmi:CARD=vc4hdmi0,DEV=0"
2023-02-11 17:42:47.052 T:1045     INFO <general>: CAESinkALSA::Initialize - Opened device "hdmi:CARD=vc4hdmi0,DEV=0,AES0=0x04,AES1=0x82,AES2=0x00,AES3=0x00"
2023-02-11 17:42:47.053 T:1045     INFO <general>: CAESinkALSA::InitializeHW - Your hardware does not support AE_FMT_FLOAT, trying other formats
2023-02-11 17:42:47.053 T:1045     INFO <general>: CAESinkALSA::InitializeHW - Using data format AE_FMT_S24NE3
2023-02-11 17:42:47.211 T:991      INFO <general>: Application stopped
2023-02-11 17:42:47.412 T:991      INFO <general>: XBApplicationEx: destroying...
2023-02-11 17:42:47.412 T:991      INFO <general>: PVR Manager: Stopping
2023-02-11 17:42:47.413 T:1527     INFO <general>: EPG Container: Persisting unsaved events...
2023-02-11 17:42:47.413 T:1527     INFO <general>: EPG Container: Persisting events done
2023-02-11 17:42:47.755 T:991      INFO <general>: PVR Manager: Stopped
2023-02-11 17:42:47.962 T:991      INFO <general>: ADDON: Dll Destroyed - Zattoo PVR Client
2023-02-11 17:42:48.276 T:991      INFO <general>: AddOnLog: peripheral.joystick: Disabling joystick interface "linux"
2023-02-11 17:42:48.278 T:991      INFO <general>: ADDON: Dll Destroyed - Joystick Support
2023-02-11 17:42:48.278 T:991      INFO <general>: unload skin
2023-02-11 17:42:48.359 T:991   WARNING <general>: Cleanup: Having to cleanup texture lists/focus.png
2023-02-11 17:42:48.419 T:991      INFO <general>: Unloaded skin
2023-02-11 17:42:48.442 T:991      INFO <general>: unload sections
2023-02-11 17:42:48.457 T:991      INFO <general>: ADDON: Dll Destroyed - SFTP support
2023-02-11 17:42:48.982 T:991      INFO <general>: XBApplicationEx: application stopped!
```
</Details>

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Libreelec 10.0.4
 - Kodi version: Kodi (19.5 (19.5.0) Git:19.5-Matrix). Platform: Linux ARM 32-bit

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by arnova** [comment]
Please provide a FULL DEBUG log. Yours is neither....

**Comment by Mannshoch** [comment]
As far I know there is no way for me to create such a log. Because I did not found any clue how to do that in:

- https://github.com/xbmc/xbmc/blob/master/README.md
- https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md
- No hint in the Template for a new issue

Please lead me where to find how to do that.

**Comment by Mannshoch** [comment]
Could I deactivate the Overlay on TV? My wife would not accept this Overlay for approximately 1 Week.

**Comment by DaVukovic** [comment]
Yes. 

Use the following at the `advancedsettings.xml`:

```
<advancedsettings>
    <loglevel>1</loglevel>  
</advancedsettings>
```

See: https://kodi.wiki/view/Advancedsettings.xml#loglevel

**Comment by Mannshoch** [comment]
This time It was fast.  I activated the debug and rebooted. The next try was a hit with the Audio Problem.
https://paste.kodi.tv/oyaguberef.kodi

**Comment by Mannshoch** [comment]
New Situation here.
I setup the debug log restarted found the situation with no audion and uploaded th Log. 
Then I deactivated the log and rebootet. But now I every time do not have any audio!

Until this the crash of audio happened around once a week and a reboot solved the problem. Now the audio is permanently missing. A reboot do not anymore help.

Any idea how to solve that?

**Comment by Mannshoch** [comment]
@DaVukovic , @enen92 
Anything I  could do or you need? otherwise I have to purge the current system and Setup a new one.

**Comment by Mannshoch** [comment]
As said, I reinstalled Libreelec. I used Libreelec 11 Beta2 Everyting works until now.
I check if this Problem appear again.
