### ISSUE TITLE
First time using this just have an error constantly through a lot of different addons. this is my whole log if anyone knows whats happening here id love a response to get this working.

### ISSUE THREAD

**Issue by JakeStephens1** [xbmc/xbmc#23040]
2023-03-23 02:19:22.432 T:25720 WARNING <general>: Repository add-on repository.chainsrepo uses plain HTTP for add-on downloads in path http://thechains24.com/_zips/ - this is insecure and will make your Kodi installation vulnerable to attacks if enabled!
2023-03-23 02:19:22.670 T:31960    INFO <general>: Skipped 1 duplicate messages..
2023-03-23 02:19:22.670 T:31960    INFO <general>: CAddonMgr::ADDON::CAddonMgr::FindAddon: plugin.program.thecrewiz v1.1.9 installed
2023-03-23 02:19:22.680 T:18704    INFO <general>: initializing python engine.
2023-03-23 02:19:22.689 T:1584  WARNING <general>: Repository add-on repository.chainsrepo uses plain HTTP for add-on downloads in path http://thechains24.com/_zips/ - this is insecure and will make your Kodi installation vulnerable to attacks if enabled!
2023-03-23 02:19:22.776 T:18704   ERROR <general>: Skipped 3 duplicate messages..
2023-03-23 02:19:22.776 T:18704   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'OSError'>
                                                   Error Contents: [Errno 22] Invalid argument: 'C:\\Users\\Admin\\AppData\\Roaming\\Kodi\\addons\\plugin.program.thecrewiz\\uservar.py'
                                                   Traceback (most recent call last):
                                                     File "C:\Users\Admin\AppData\Roaming\Kodi\addons\plugin.program.thecrewiz\startup.py", line 22, in <module>
                                                       import uservar
                                                     File "<frozen importlib._bootstrap>", line 991, in _find_and_load
                                                     File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
                                                     File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
                                                     File "<frozen importlib._bootstrap_external>", line 774, in exec_module
                                                     File "<frozen importlib._bootstrap_external>", line 910, in get_code
                                                     File "<frozen importlib._bootstrap_external>", line 967, in get_data
                                                   OSError: [Errno 22] Invalid argument: 'C:\\Users\\Admin\\AppData\\Roaming\\Kodi\\addons\\plugin.program.thecrewiz\\uservar.py'
                                                   -->End of Python script error report<--
                                                   
2023-03-23 02:19:22.829 T:18704    INFO <general>: Python interpreter stopped
2023-03-23 02:20:07.310 T:24260    INFO <general>: Loading skin file: MyPrograms.xml, load type: KEEP_IN_MEMORY
2023-03-23 02:20:07.340 T:5176     INFO <general>: initializing python engine.
2023-03-23 02:20:07.405 T:5176    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'OSError'>
                                                   Error Contents: [Errno 22] Invalid argument: 'C:\\Users\\Admin\\AppData\\Roaming\\Kodi\\addons\\plugin.program.thecrewiz\\uservar.py'
                                                   Traceback (most recent call last):
                                                     File "C:\Users\Admin\AppData\Roaming\Kodi\addons\plugin.program.thecrewiz\default.py", line 23, in <module>
                                                       import uservar
                                                     File "<frozen importlib._bootstrap>", line 991, in _find_and_load
                                                     File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
                                                     File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
                                                     File "<frozen importlib._bootstrap_external>", line 774, in exec_module
                                                     File "<frozen importlib._bootstrap_external>", line 910, in get_code
                                                     File "<frozen importlib._bootstrap_external>", line 967, in get_data
                                                   OSError: [Errno 22] Invalid argument: 'C:\\Users\\Admin\\AppData\\Roaming\\Kodi\\addons\\plugin.program.thecrewiz\\uservar.py'
                                                   -->End of Python script error report<--
                                                   
2023-03-23 02:20:07.409 T:5176     INFO <general>: Python interpreter stopped
2023-03-23 02:20:07.423 T:25308   ERROR <general>: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.program.thecrewiz/
2023-03-23 02:20:07.423 T:24260   ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.program.thecrewiz/) failed
2023-03-23 02:20:08.104 T:10708   ERROR <general>: CImageLoader::DoWork - Direct texture file loading failed for special://masterprofile/Thumbnails/f/f9ed114f.png
2023-03-23 02:20:09.497 T:10708   ERROR <general>: CImageLoader::DoWork - Direct texture file loading failed for special://masterprofile/Thumbnails/1/1ea45b61.jpg
2023-03-23 02:20:10.122 T:27820    INFO <general>: initializing python engine.
2023-03-23 02:20:10.180 T:27820   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'OSError'>
                                                   Error Contents: [Errno 22] Invalid argument: 'C:\\Users\\Admin\\AppData\\Roaming\\Kodi\\addons\\plugin.program.thecrewiz\\uservar.py'
                                                   Traceback (most recent call last):
                                                     File "C:\Users\Admin\AppData\Roaming\Kodi\addons\plugin.program.thecrewiz\default.py", line 23, in <module>
                                                       import uservar
                                                     File "<frozen importlib._bootstrap>", line 991, in _find_and_load
                                                     File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
                                                     File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
                                                     File "<frozen importlib._bootstrap_external>", line 774, in exec_module
                                                     File "<frozen importlib._bootstrap_external>", line 910, in get_code
                                                     File "<frozen importlib._bootstrap_external>", line 967, in get_data
                                                   OSError: [Errno 22] Invalid argument: 'C:\\Users\\Admin\\AppData\\Roaming\\Kodi\\addons\\plugin.program.thecrewiz\\uservar.py'
                                                   -->End of Python script error report<--
                                                   
2023-03-23 02:20:10.182 T:27820    INFO <general>: Python interpreter stopped
2023-03-23 02:20:10.183 T:8364    ERROR <general>: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.program.thecrewiz/
2023-03-23 02:20:10.183 T:24260   ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.program.thecrewiz/) failed
2023-03-23 02:20:13.343 T:20832    INFO <general>: initializing python engine.
2023-03-23 02:20:13.409 T:20832   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'OSError'>
                                                   Error Contents: [Errno 22] Invalid argument: 'C:\\Users\\Admin\\AppData\\Roaming\\Kodi\\addons\\plugin.program.thecrewiz\\uservar.py'
                                                   Traceback (most recent call last):
                                                     File "C:\Users\Admin\AppData\Roaming\Kodi\addons\plugin.program.thecrewiz\default.py", line 23, in <module>
                                                       import uservar
                                                     File "<frozen importlib._bootstrap>", line 991, in _find_and_load
                                                     File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
                                                     File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
                                                     File "<frozen importlib._bootstrap_external>", line 774, in exec_module
                                                     File "<frozen importlib._bootstrap_external>", line 910, in get_code
                                                     File "<frozen importlib._bootstrap_external>", line 967, in get_data
                                                   OSError: [Errno 22] Invalid argument: 'C:\\Users\\Admin\\AppData\\Roaming\\Kodi\\addons\\plugin.program.thecrewiz\\uservar.py'
                                                   -->End of Python script error report<--
                                                   
2023-03-23 02:20:13.413 T:20832    INFO <general>: Python interpreter stopped
2023-03-23 02:20:13.425 T:16420   ERROR <general>: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.program.thecrewiz/
2023-03-23 02:20:13.425 T:24260   ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.program.thecrewiz/) failed
2023-03-23 02:20:15.537 T:24260 WARNING <general>: Repository add-on repository.chainsrepo uses plain HTTP for add-on downloads in path http://thechains24.com/_zips/ - this is insecure and will make your Kodi installation vulnerable to attacks if enabled!
2023-03-23 02:20:20.802 T:32740   ERROR <general>: Skipped 2 duplicate messages..
2023-03-23 02:20:20.802 T:32740   ERROR <general>: CImageLoader::DoWork - Direct texture file loading failed for special://masterprofile/Thumbnails/9/91a5e31d.png
2023-03-23 02:20:21.339 T:29552 WARNING <general>: Repository add-on repository.chainsrepo uses plain HTTP for add-on downloads in path http://thechains24.com/_zips/ - this is insecure and will make your Kodi installation vulnerable to attacks if enabled!
2023-03-23 02:21:24.076 T:24260 WARNING <general>: Repository add-on repository.chainsrepo uses plain HTTP for add-on downloads in path http://thechains24.com/_zips/ - this is insecure and will make your Kodi installation vulnerable to attacks if enabled!
2023-03-23 02:21:28.383 T:24260 WARNING <general>: Skipped 1 duplicate messages..
2023-03-23 02:21:28.383 T:24260 WARNING <general>: CGUIWindowManager - CGUIWindowManager::HandleAction - ignoring action 107, because topmost modal dialog closing animation is running
2023-03-23 02:21:28.618 T:24260    INFO <general>: Skipped 11 duplicate messages..
2023-03-23 02:21:28.618 T:24260    INFO <general>: Loading skin file: FileBrowser.xml, load type: KEEP_IN_MEMORY
2023-03-23 02:21:30.083 T:12524 WARNING <general>: Repository add-on repository.chainsrepo uses plain HTTP for add-on downloads in path http://thechains24.com/_zips/ - this is insecure and will make your Kodi installation vulnerable to attacks if enabled!
2023-03-23 02:21:33.040 T:24260   ERROR <general>: Skipped 2 duplicate messages..
2023-03-23 02:21:33.040 T:24260   ERROR <general>: Control 55 in window 10001 has been asked to focus, but it can't
2023-03-23 02:21:33.055 T:13352    INFO <general>: initializing python engine.
2023-03-23 02:21:33.115 T:13352   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'ModuleNotFoundError'>
                                                   Error Contents: No module named 'uservar'
                                                   Traceback (most recent call last):
                                                     File "C:\Users\Admin\AppData\Roaming\Kodi\addons\plugin.program.thecrewiz\default.py", line 23, in <module>
                                                       import uservar
                                                   ModuleNotFoundError: No module named 'uservar'
                                                   -->End of Python script error report<--
                                                   
2023-03-23 02:21:33.117 T:13352    INFO <general>: Python interpreter stopped
2023-03-23 02:21:33.118 T:10180   ERROR <general>: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.program.thecrewiz/
2023-03-23 02:21:33.118 T:24260   ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.program.thecrewiz/) failed
2023-03-23 02:21:33.120 T:27896    INFO <general>: CActiveAESink::OpenSink - initialize sink
2023-03-23 02:21:34.494 T:24260 WARNING <general>: Repository add-on repository.chainsrepo uses plain HTTP for add-on downloads in path http://thechains24.com/_zips/ - this is insecure and will make your Kodi installation vulnerable to attacks if enabled!
2023-03-23 02:21:38.074 T:24260   ERROR <general>: Skipped 1 duplicate messages..
2023-03-23 02:21:38.074 T:24260   ERROR <general>: Control 55 in window 10001 has been asked to focus, but it can't
2023-03-23 02:21:38.088 T:28764    INFO <general>: initializing python engine.
2023-03-23 02:21:38.149 T:28764   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'ModuleNotFoundError'>
                                                   Error Contents: No module named 'uservar'
                                                   Traceback (most recent call last):
                                                     File "C:\Users\Admin\AppData\Roaming\Kodi\addons\plugin.program.thecrewiz\default.py", line 23, in <module>
                                                       import uservar
                                                   ModuleNotFoundError: No module named 'uservar'
                                                   -->End of Python script error report<--
                                                   
2023-03-23 02:21:38.153 T:28764    INFO <general>: Python interpreter stopped
2023-03-23 02:21:38.171 T:7480    ERROR <general>: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.program.thecrewiz/
2023-03-23 02:21:38.171 T:24260   ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.program.thecrewiz/) failed
2023-03-23 02:21:40.568 T:26384    INFO <general>: initializing python engine.
2023-03-23 02:21:40.679 T:26384    INFO <general>: CPythonInvoker(9, C:\Users\Admin\AppData\Roaming\Kodi\addons\plugin.program.chef19\addon.py): script successfully run
2023-03-23 02:21:40.686 T:26384    INFO <general>: Python interpreter stopped
2023-03-23 02:21:41.754 T:21384    INFO <general>: initializing python engine.
2023-03-23 02:21:42.156 T:21384    INFO <general>: CPythonInvoker(10, C:\Users\Admin\AppData\Roaming\Kodi\addons\plugin.program.chef19\addon.py): script successfully run
2023-03-23 02:21:42.162 T:21384    INFO <general>: Python interpreter stopped
2023-03-23 02:21:43.018 T:7476    ERROR <general>: CImageLoader::DoWork - Direct texture file loading failed for special://masterprofile/Thumbnails/a/aa939b11.png
2023-03-23 02:21:43.341 T:8432     INFO <general>: initializing python engine.
2023-03-23 02:21:43.456 T:8432     INFO <general>: CPythonInvoker(11, C:\Users\Admin\AppData\Roaming\Kodi\addons\plugin.program.chef19\addon.py): script successfully run
2023-03-23 02:21:43.464 T:8432     INFO <general>: Python interpreter stopped
2023-03-23 02:21:44.404 T:26664    INFO <general>: initializing python engine.
2023-03-23 02:21:44.509 T:26664    INFO <general>: CPythonInvoker(12, C:\Users\Admin\AppData\Roaming\Kodi\addons\plugin.program.chef19\addon.py): script successfully run
2023-03-23 02:21:44.516 T:26664    INFO <general>: Python interpreter stopped
2023-03-23 02:21:44.860 T:5452    ERROR <general>: CImageLoader::DoWork - Direct texture file loading failed for special://masterprofile/Thumbnails/0/03914f92.jpg
2023-03-23 02:21:44.956 T:7476    ERROR <general>: CImageLoader::DoWork - Direct texture file loading failed for special://masterprofile/Thumbnails/e/e6d327b1.jpg
2023-03-23 02:21:45.250 T:5452    ERROR <general>: CImageLoader::DoWork - Direct texture file loading failed for special://masterprofile/Thumbnails/b/bf3eca5f.jpg
2023-03-23 02:21:45.688 T:19680    INFO <general>: initializing python engine.
2023-03-23 02:21:45.802 T:19680    INFO <general>: CPythonInvoker(13, C:\Users\Admin\AppData\Roaming\Kodi\addons\plugin.program.chef19\addon.py): script successfully run
2023-03-23 02:21:45.810 T:19680    INFO <general>: Python interpreter stopped
2023-03-23 02:21:47.218 T:29164    INFO <general>: initializing python engine.
2023-03-23 02:21:47.326 T:29164 WARNING <general>: Attempt to use invalid handle -1
2023-03-23 02:21:47.326 T:29164    INFO <general>: Skipped 1 duplicate messages..
2023-03-23 02:21:47.326 T:29164    INFO <general>: CPythonInvoker(14, C:\Users\Admin\AppData\Roaming\Kodi\addons\plugin.program.chef19\addon.py): script successfully run
2023-03-23 02:21:47.334 T:29164    INFO <general>: Python interpreter stopped
2023-03-23 02:21:47.346 T:24260   ERROR <general>: CScriptInvocationManager::ExecuteAsync - Not executing non-existing script script.module.myaccts
2023-03-23 02:21:49.082 T:25860    INFO <general>: initializing python engine.
2023-03-23 02:21:49.185 T:25860 WARNING <general>: Attempt to use invalid handle -1
2023-03-23 02:21:49.185 T:25860    INFO <general>: Skipped 1 duplicate messages..
2023-03-23 02:21:49.185 T:25860    INFO <general>: CPythonInvoker(15, C:\Users\Admin\AppData\Roaming\Kodi\addons\plugin.program.chef19\addon.py): script successfully run
2023-03-23 02:21:49.192 T:25860    INFO <general>: Python interpreter stopped
2023-03-23 02:21:49.215 T:24260   ERROR <general>: CScriptInvocationManager::ExecuteAsync - Not executing non-existing script script.module.myaccts
2023-03-23 02:21:50.301 T:13168    INFO <general>: initializing python engine.
2023-03-23 02:21:50.407 T:13168    INFO <general>: CPythonInvoker(16, C:\Users\Admin\AppData\Roaming\Kodi\addons\plugin.program.chef19\addon.py): script successfully run
2023-03-23 02:21:50.417 T:13168    INFO <general>: Python interpreter stopped
2023-03-23 02:21:50.664 T:28120    INFO <general>: initializing python engine.
2023-03-23 02:21:50.772 T:28120    INFO <general>: CPythonInvoker(17, C:\Users\Admin\AppData\Roaming\Kodi\addons\plugin.program.chef19\addon.py): script successfully run
2023-03-23 02:21:50.777 T:28120    INFO <general>: Python interpreter interrupted by user
2023-03-23 02:21:50.778 T:32244   ERROR <general>: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.program.chef19/
2023-03-23 02:21:50.779 T:24260   ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.program.chef19/) failed
2023-03-23 02:21:51.085 T:24260 WARNING <general>: Repository add-on repository.chainsrepo uses plain HTTP for add-on downloads in path http://thechains24.com/_zips/ - this is insecure and will make your Kodi installation vulnerable to attacks if enabled!
2023-03-23 02:21:55.372 T:24260 WARNING <general>: Skipped 1 duplicate messages..
2023-03-23 02:21:55.372 T:24260 WARNING <general>: CGUIWindowManager - CGUIWindowManager::HandleAction - ignoring action 107, because topmost modal dialog closing animation is running
2023-03-23 02:21:55.779 T:7476  WARNING <general>: Skipped 43 duplicate messages..
2023-03-23 02:21:55.779 T:7476  WARNING <general>: Repository add-on repository.chainsrepo uses plain HTTP for add-on downloads in path http://thechains24.com/_zips/ - this is insecure and will make your Kodi installation vulnerable to attacks if enabled!
2023-03-23 02:21:55.911 T:7476     INFO <general>: CAddonMgr::ADDON::CAddonMgr::FindAddon: plugin.program.breezz19wizard v1.0.1 installed
2023-03-23 02:21:55.940 T:8032     INFO <general>: initializing python engine.
2023-03-23 02:21:55.961 T:30116 WARNING <general>: Repository add-on repository.chainsrepo uses plain HTTP for add-on downloads in path http://thechains24.com/_zips/ - this is insecure and will make your Kodi installation vulnerable to attacks if enabled!
2023-03-23 02:21:56.113 T:24260    INFO <general>: Skipped 3 duplicate messages..
2023-03-23 02:21:56.113 T:24260    INFO <general>: Loading skin file: DialogSelect.xml, load type: KEEP_IN_MEMORY
2023-03-23 02:22:00.137 T:8032     INFO <general>: CPythonInvoker(18, C:\Users\Admin\AppData\Roaming\Kodi\addons\plugin.program.breezz19wizard\service.py): script successfully run
2023-03-23 02:22:00.145 T:8032     INFO <general>: Python interpreter stopped
2023-03-23 02:22:02.158 T:24260   ERROR <general>: Control 500 in window 10001 has been asked to focus, but it can't
2023-03-23 02:22:02.173 T:3656     INFO <general>: initializing python engine.
2023-03-23 02:22:02.267 T:24260 WARNING <general>: CGUIWindowManager - CGUIWindowManager::HandleAction - ignoring action 107, because topmost modal dialog closing animation is running
2023-03-23 02:22:02.268 T:3656     INFO <general>: CPythonInvoker(19, C:\Users\Admin\AppData\Roaming\Kodi\addons\plugin.program.breezz19wizard\addon.py): script successfully run
2023-03-23 02:22:02.275 T:3656     INFO <general>: Python interpreter stopped
2023-03-23 02:22:03.690 T:28156    INFO <general>: initializing python engine.
2023-03-23 02:22:04.088 T:28156   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'urllib.error.HTTPError'>
                                                   Error Contents: HTTP Error 404: Not Found
                                                   Traceback (most recent call last):
                                                     File "C:\Users\Admin\AppData\Roaming\Kodi\addons\plugin.program.breezz19wizard\addon.py", line 370, in <module>
                                                       BuildMenu()
                                                     File "C:\Users\Admin\AppData\Roaming\Kodi\addons\plugin.program.breezz19wizard\addon.py", line 49, in BuildMenu
                                                       response = urlopen(req).read()
                                                     File "C:\Program Files\Kodi\system\python\Lib\urllib\request.py", line 222, in urlopen
                                                       return opener.open(url, data, timeout)
                                                     File "C:\Program Files\Kodi\system\python\Lib\urllib\request.py", line 531, in open
                                                       response = meth(req, response)
                                                     File "C:\Program Files\Kodi\system\python\Lib\urllib\request.py", line 640, in http_response
                                                       response = self.parent.error(
                                                     File "C:\Program Files\Kodi\system\python\Lib\urllib\request.py", line 569, in error
                                                       return self._call_chain(*args)
                                                     File "C:\Program Files\Kodi\system\python\Lib\urllib\request.py", line 502, in _call_chain
                                                       result = func(*args)
                                                     File "C:\Program Files\Kodi\system\python\Lib\urllib\request.py", line 649, in http_error_default
                                                       raise HTTPError(req.full_url, code, msg, hdrs, fp)
                                                   urllib.error.HTTPError: HTTP Error 404: Not Found
                                                   -->End of Python script error report<--
                                                   
2023-03-23 02:22:04.096 T:28156    INFO <general>: Python interpreter stopped
2023-03-23 02:22:04.106 T:25164   ERROR <general>: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.program.breezz19wizard/?description=Install%20a%20build.&fanart=C%3a%5cUsers%5cAdmin%5cAppData%5cRoaming%5cKodi%5caddons%5cplugin.program.breezz19wizard%5cresources%5cfanart.jpg&icon=C%3a%5cUsers%5cAdmin%5cAppData%5cRoaming%5cKodi%5caddons%5cplugin.program.breezz19wizard%5cresources%5cicon.png&mode=1&name=Build%20Menu&name2&url&version
2023-03-23 02:22:04.156 T:24260   ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.program.breezz19wizard/?description=Install%20a%20build.&fanart=C%3a%5cUsers%5cAdmin%5cAppData%5cRoaming%5cKodi%5caddons%5cplugin.program.breezz19wizard%5cresources%5cfanart.jpg&icon=C%3a%5cUsers%5cAdmin%5cAppData%5cRoaming%5cKodi%5caddons%5cplugin.program.breezz19wizard%5cresources%5cicon.png&mode=1&name=Build%20Menu&name2&url&version) failed
2023-03-23 02:22:04.165 T:32332    INFO <general>: initializing python engine.
2023-03-23 02:22:04.258 T:32332    INFO <general>: CPythonInvoker(21, C:\Users\Admin\AppData\Roaming\Kodi\addons\plugin.program.breezz19wizard\addon.py): script successfully run
2023-03-23 02:22:04.268 T:32332    INFO <general>: Python interpreter stopped
2023-03-23 02:22:04.875 T:31908    INFO <general>: initializing python engine.
2023-03-23 02:22:05.209 T:31908   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'urllib.error.HTTPError'>
                                                   Error Contents: HTTP Error 404: Not Found
                                                   Traceback (most recent call last):
                                                     File "C:\Users\Admin\AppData\Roaming\Kodi\addons\plugin.program.breezz19wizard\addon.py", line 370, in <module>
                                                       BuildMenu()
                                                     File "C:\Users\Admin\AppData\Roaming\Kodi\addons\plugin.program.breezz19wizard\addon.py", line 49, in BuildMenu
                                                       response = urlopen(req).read()
                                                     File "C:\Program Files\Kodi\system\python\Lib\urllib\request.py", line 222, in urlopen
                                                       return opener.open(url, data, timeout)
                                                     File "C:\Program Files\Kodi\system\python\Lib\urllib\request.py", line 531, in open
                                                       response = meth(req, response)
                                                     File "C:\Program Files\Kodi\system\python\Lib\urllib\request.py", line 640, in http_response
                                                       response = self.parent.error(
                                                     File "C:\Program Files\Kodi\system\python\Lib\urllib\request.py", line 569, in error
                                                       return self._call_chain(*args)
                                                     File "C:\Program Files\Kodi\system\python\Lib\urllib\request.py", line 502, in _call_chain
                                                       result = func(*args)
                                                     File "C:\Program Files\Kodi\system\python\Lib\urllib\request.py", line 649, in http_error_default
                                                       raise HTTPError(req.full_url, code, msg, hdrs, fp)
                                                   urllib.error.HTTPError: HTTP Error 404: Not Found
                                                   -->End of Python script error report<--
                                                   
2023-03-23 02:22:05.217 T:31908    INFO <general>: Python interpreter stopped
2023-03-23 02:22:05.226 T:31876   ERROR <general>: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.program.breezz19wizard/?description=Install%20a%20build.&fanart=C%3a%5cUsers%5cAdmin%5cAppData%5cRoaming%5cKodi%5caddons%5cplugin.program.breezz19wizard%5cresources%5cfanart.jpg&icon=C%3a%5cUsers%5cAdmin%5cAppData%5cRoaming%5cKodi%5caddons%5cplugin.program.breezz19wizard%5cresources%5cicon.png&mode=1&name=Build%20Menu&name2&url&version
2023-03-23 02:22:05.242 T:24260   ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.program.breezz19wizard/?description=Install%20a%20build.&fanart=C%3a%5cUsers%5cAdmin%5cAppData%5cRoaming%5cKodi%5caddons%5cplugin.program.breezz19wizard%5cresources%5cfanart.jpg&icon=C%3a%5cUsers%5cAdmin%5cAppData%5cRoaming%5cKodi%5caddons%5cplugin.program.breezz19wizard%5cresources%5cicon.png&mode=1&name=Build%20Menu&name2&url&version) failed
2023-03-23 02:22:05.252 T:28984    INFO <general>: initializing python engine.
2023-03-23 02:22:05.345 T:28984    INFO <general>: CPythonInvoker(23, C:\Users\Admin\AppData\Roaming\Kodi\addons\plugin.program.breezz19wizard\addon.py): script successfully run
2023-03-23 02:22:05.353 T:28984    INFO <general>: Python interpreter stopped
2023-03-23 02:22:05.805 T:24260 WARNING <general>: Repository add-on repository.chainsrepo uses plain HTTP for add-on downloads in path http://thechains24.com/_zips/ - this is insecure and will make your Kodi installation vulnerable to attacks if enabled!

**Comment by fuzzard** [comment]
This isnt a bug in kodi. For support queries you can go to the forums.

With that said, names of addons in that log sound like they are piracy/build related. If thats the case, you wont get any support from Team kodi on here, or on our forums.
