### ISSUE TITLE
Kodi crashes/exits while playing video stream

### ISSUE THREAD

**Issue by sryze** [xbmc/xbmc#23355]
### Describe the bug
Here is a clear and concise description of what the problem is:

After playing a YouTube video stream for a couple of hours or so, the stream begins stuttering and Kodi unexpectedly exits. It appears to be caused by these events:
```
info <general>: Process - eof reading from demuxer
info <general>: CVideoPlayer::OnExit()
info <general>: VideoPlayer: eof, waiting for queues to empty
```

Please see the attached log file below.
[kodi.log](https://github.com/xbmc/xbmc/files/11628391/kodi.log)

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Continue playing stream

## Actual Behavior

Kodi exited by itself / crashed

### To Reproduce

1. Open Kodi
2. Go to the YouTube Channels addon and play some live stream
3. Wait for 1-3 hours

### Debuglog

The debuglog can be found here:

[kodi.log](https://github.com/xbmc/xbmc/files/11628391/kodi.log)

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [X] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Armbian 23.02.2
 - Kodi version: 20.1 with patch https://github.com/xbmc/xbmc/commit/10af3020ae0c1e2aafbf18cd448c845923602566

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by lrusak** [comment]
If Kodi is crashing please post a stack trace.

Otherwise I'm not sure where the EOF comes from but maybe it's a big in inputstream.adaptive

**Comment by sryze** [comment]
@lrusak 

```
#0  __libc_do_syscall () at ../sysdeps/unix/sysv/linux/arm/libc-do-syscall.S:47
#1  0xb3fdd2ca in __pthread_kill_implementation (threadid=1872846976, signo=6, no_tid=<optimized out>)
    at pthread_kill.c:43
#2  0xb3fac840 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#3  0xb3f9d5e4 in __GI_abort () at abort.c:79
#4  0xb3e71672 in __gnu_cxx::__verbose_terminate_handler() () at /lib/arm-linux-gnueabihf/libstdc++.so.6
#5  0xb3e6fcc8 in  () at /lib/arm-linux-gnueabihf/libstdc++.so.6
#6  0xb3e6fd2a in  () at /lib/arm-linux-gnueabihf/libstdc++.so.6
#7  0xb3e6ff58 in __cxa_rethrow () at /lib/arm-linux-gnueabihf/libstdc++.so.6
#8  0xb3e703ae in operator new(unsigned int) () at /lib/arm-linux-gnueabihf/libstdc++.so.6
#9  0x00c04770 in CVideoBufferPoolSysMem::Get() ()
#10 0x00c04472 in CVideoBufferManager::Get(AVPixelFormat, int, IVideoBufferPool**) ()
#11 0x00bf27ee in CDVDVideoCodecDRMPRIME::GetBuffer(AVCodecContext*, AVFrame*, int) ()
#12 0xb575f634 in  () at /lib/arm-linux-gnueabihf/libavcodec.so.58
```

**Comment by lrusak** [comment]
> @lrusak 
> 
> 
> 
> ```
> 
> #0  __libc_do_syscall () at ../sysdeps/unix/sysv/linux/arm/libc-do-syscall.S:47
> 
> #1  0xb3fdd2ca in __pthread_kill_implementation (threadid=1872846976, signo=6, no_tid=<optimized out>)
> 
>     at pthread_kill.c:43
> 
> #2  0xb3fac840 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
> 
> #3  0xb3f9d5e4 in __GI_abort () at abort.c:79
> 
> #4  0xb3e71672 in __gnu_cxx::__verbose_terminate_handler() () at /lib/arm-linux-gnueabihf/libstdc++.so.6
> 
> #5  0xb3e6fcc8 in  () at /lib/arm-linux-gnueabihf/libstdc++.so.6
> 
> #6  0xb3e6fd2a in  () at /lib/arm-linux-gnueabihf/libstdc++.so.6
> 
> #7  0xb3e6ff58 in __cxa_rethrow () at /lib/arm-linux-gnueabihf/libstdc++.so.6
> 
> #8  0xb3e703ae in operator new(unsigned int) () at /lib/arm-linux-gnueabihf/libstdc++.so.6
> 
> #9  0x00c04770 in CVideoBufferPoolSysMem::Get() ()
> 
> #10 0x00c04472 in CVideoBufferManager::Get(AVPixelFormat, int, IVideoBufferPool**) ()
> 
> #11 0x00bf27ee in CDVDVideoCodecDRMPRIME::GetBuffer(AVCodecContext*, AVFrame*, int) ()
> 
> #12 0xb575f634 in  () at /lib/arm-linux-gnueabihf/libavcodec.so.58
> 
> ```

OOM?

Im not really sure why it's using the system memory pool. Do you not have any DMA methods available? Do you not allocate any CMA either?

**Comment by sryze** [comment]
I'm not sure about the DMA/CMA stuff, I will look into that. I'm running Kodi on an Orange PI PC+ board. 

Right now I'm trying to reproduce it again but in a debug build this time (so far no luck). The video stream freezes sometimes but no crashes so far.
