### ISSUE TITLE
Crash on system with only 1920x1200 mode availiable

### ISSUE THREAD

**Issue by mittorn** [xbmc/xbmc#23403]
### Describe the bug
Here is a clear and concise description of what the problem is:

Trying to run LibreELEC+kodi with 1920x1200 display.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Kodi runs and shows current drm mode

## Actual Behavior
Kodi crashes

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:
```
Thread 1 (Thread 0xf38e9240 (LWP 1063)):
#0  0x00f82894 in KODI::WINDOWING::GBM::CDRMUtils::SetMode(RESOLUTION_INFO const&) ()
#1  0xf534f42c in strtol () from /usr/lib/libc.so.6
#2  0x02b86a58 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
```
```
2023-06-14 20:49:42.921 T:1063     info <general>: CDRMUtils::FindConnector - using connector: HDMI-A-1
2023-06-14 20:49:42.921 T:1063     info <general>: Skipped 1 duplicate messages..
2023-06-14 20:49:42.921 T:1063     info <general>: CDRMUtils::FindEncoder - using encoder: 63
2023-06-14 20:49:42.922 T:1063     info <general>: CDRMUtils::FindPlanes - using crtc: 62
2023-06-14 20:49:42.922 T:1063     info <general>: [display-info] make: 'Transtream Inc' model: 'TST000'
2023-06-14 20:49:42.938 T:1063  warning <general>: CWinSystemGbm::UpdateResolutions - Failed to get resolutions
2023-06-14 20:49:42.940 T:1063     info <general>: EGL_VERSION = 1.4
2023-06-14 20:49:42.940 T:1063     info <general>: EGL_VENDOR = Mesa Project
2023-06-14 20:49:42.940 T:1063     info <general>: EGL_EXTENSIONS = EGL_ANDROID_blob_cache EGL_ANDROID_native_fence_sync EGL_EXT_buffer_age EGL_EXT_image_dma_buf_import EGL_EXT_image_dma_buf_import_modifiers EGL_KHR_cl_event2 EGL_KHR_config_attribs EGL_KHR_context_flush_control EGL_KHR_create_context EGL_KHR_create_context_no_error EGL_KHR_fence_sync EGL_KHR_get_all_proc_addresses EGL_KHR_gl_colorspace EGL_KHR_gl_renderbuffer_image EGL_KHR_gl_texture_2D_image EGL_KHR_gl_texture_3D_image EGL_KHR_gl_texture_cubemap_image EGL_KHR_image EGL_KHR_image_base EGL_KHR_image_pixmap EGL_KHR_no_config_context EGL_KHR_partial_update EGL_KHR_reusable_sync EGL_KHR_surfaceless_context EGL_EXT_pixel_format_float EGL_KHR_wait_sync EGL_MESA_configless_context EGL_MESA_drm_image EGL_MESA_image_dma_buf_export EGL_MESA_query_driver
2023-06-14 20:49:42.940 T:1063     info <general>: EGL_CLIENT_EXTENSIONS = EGL_EXT_client_extensions EGL_EXT_device_base EGL_EXT_device_enumeration EGL_EXT_device_query EGL_EXT_platform_base EGL_KHR_client_get_all_proc_addresses EGL_KHR_debug EGL_EXT_platform_device EGL_MESA_platform_gbm EGL_KHR_platform_gbm EGL_MESA_platform_surfaceless
2023-06-14 20:49:42.943 T:1063     info <general>: CApplication::CreateGUI - using the gbm windowing system
2023-06-14 20:49:42.943 T:1063     info <general>: Checking resolution 16

############### END LOG FILE ################
```

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ *] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: LibreELEC
 - Kodi version:
```
2023-06-14 20:49:42.722 T:1063     info <general>: Starting Kodi (21.0-ALPHA1 (20.90.101) Git:1a04aa12cb4e5457867451f41ab4dcdcd201b1a9). Platform: Linux ARM 32-bit
2023-06-14 20:49:42.722 T:1063     info <general>: Using Release Kodi x32
2023-06-14 20:49:42.722 T:1063     info <general>: Kodi compiled 2023-06-14 by GCC 13.1.0 for Linux ARM 32-bit version 6.3.4 (393988)
```

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by youtehub** [comment]
This is indeed a strange problem, my display resolution is 2K, how to switch to 1080P kodi will crash, but after switching the display resolution to 2k, kodi can be used, this is an old problem, it is kodi Can only run at the resolution the monitor is set to when it is installed
