### ISSUE TITLE
Ubuntu 3.10 - Add-on Python script error report

### ISSUE THREAD

**Issue by marradomenico** [xbmc/xbmc#23984]
### Describe the bug
I recently installed Ubuntu version 3.10, and now thegroove360 plug-in no longer works, it installs but no longer updates the channel list.

## Actual Behavior
Following is what the log file reports.

```
2023-10-23 09:45:47.347 T:16432    info <general>: CAddonMgr::FindAddon: plugin.video.thegroove360 v0.4.5 installed
2023-10-23 09:45:47.368 T:16432 warning <general>: Repository add-on One.repo uses plain HTTP for add-on downloads in path http://raw.githubusercontent.com/OnePlayHD/OneRepo/master - this is insecure and will make your Kodi installation vulnerable to attacks if enabled!
2023-10-23 09:45:47.368 T:16432   error <general>: Repository add-on repository.gaia uses old schema definition for the repository extension point! This is no longer supported, please update your addon to use <dir> definitions.
2023-10-23 09:45:47.368 T:16432   error <general>: Repository add-on repository.universalscrapers uses old schema definition for the repository extension point! This is no longer supported, please update your addon to use <dir> definitions.
2023-10-23 09:45:47.368 T:16432   error <general>: Repository add-on repository.universalscrapers does not have any directory and won't be able to update/serve addons! Please fix the addon.xml definition
2023-10-23 09:45:47.384 T:16432   error <general>: Repository add-on repository.ocean uses old schema definition for the repository extension point! This is no longer supported, please update your addon to use <dir> definitions.
2023-10-23 09:45:47.384 T:16432   error <general>: Repository add-on repository.ocean does not have any directory and won't be able to update/serve addons! Please fix the addon.xml definition
2023-10-23 09:45:47.386 T:16432   error <general>: Repository add-on repository.ocean uses old schema definition for the repository extension point! This is no longer supported, please update your addon to use <dir> definitions.
2023-10-23 09:45:47.386 T:16432   error <general>: Repository add-on repository.ocean does not have any directory and won't be able to update/serve addons! Please fix the addon.xml definition
2023-10-23 09:45:57.196 T:16387    info <general>: Loading skin file: DialogAddonSettings.xml, load type: KEEP_IN_MEMORY
2023-10-23 09:45:59.497 T:16387    info <general>: Loading skin file: MyVideoNav.xml, load type: KEEP_IN_MEMORY
2023-10-23 09:46:00.229 T:16387    info <general>: Loading skin file: DialogConfirm.xml, load type: KEEP_IN_MEMORY
2023-10-23 09:46:00.381 T:16474   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'ModuleNotFoundError'>
                                                   Error Contents: No module named 'urllib2'
                                                   Traceback (most recent call last):
                                                     File "/home/domenico/.kodi/addons/plugin.video.thegroove360/resources/modules/thegroove/updater.py", line 275, in install_zip
                                                       with zipfile.ZipFile(zipped_file, 'r') as zfile:
                                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/usr/lib/python3.11/zipfile.py", line 1302, in __init__
                                                       self._RealGetContents()
                                                     File "/usr/lib/python3.11/zipfile.py", line 1369, in _RealGetContents
                                                       raise BadZipFile("File is not a zip file")
                                                   zipfile.BadZipFile: File is not a zip file
                                                   
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   Traceback (most recent call last):
                                                     File "/home/domenico/.kodi/addons/plugin.video.thegroove360/main.py", line 13, in <module>
                                                       plugin.run()
                                                     File "/home/domenico/.kodi/addons/plugin.video.thegroove360/resources/lib/plugin.py", line 656, in run
                                                       plugin.run()
                                                     File "/home/domenico/.kodi/addons/script.module.routing/lib/routing.py", line 130, in run
                                                       self._dispatch(self.path)
                                                     File "/home/domenico/.kodi/addons/script.module.routing/lib/routing.py", line 141, in _dispatch
                                                       view_func(**kwargs)
                                                     File "/home/domenico/.kodi/addons/plugin.video.thegroove360/resources/lib/plugin.py", line 628, in addon_update
                                                       updater.check_update()
                                                     File "/home/domenico/.kodi/addons/plugin.video.thegroove360/resources/modules/thegroove/updater.py", line 185, in check_update
                                                       download_new_release(rv)
                                                     File "/home/domenico/.kodi/addons/plugin.video.thegroove360/resources/modules/thegroove/updater.py", line 258, in download_new_release
                                                       install_zip(out_temp, target_folder, dDialog, tag_name)
                                                     File "/home/domenico/.kodi/addons/plugin.video.thegroove360/resources/modules/thegroove/updater.py", line 281, in install_zip
                                                       from urllib2 import Request, urlopen
                                                   ModuleNotFoundError: No module named 'urllib2'
                                                   --> End of Python script error report <--
                                                   
2023-10-23 09:46:00.396 T:16421    info <general>: CActiveAESink::OpenSink - initialize sink
2023-10-23 09:46:00.402 T:16473   error <general>: GetDirectory - Error getting plugin://plugin.video.thegroove360/update
2023-10-23 09:46:00.405 T:16421    info <general>: PulseAudio: Opened device Default in pcm mode with Buffersize 150 ms Periodsize 50 ms
2023-10-23 09:46:00.411 T:16387   error <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.thegroove360/update) failed
```

### Your Environment
Used Operating system:

 - Operating system version/name: Ubuntu 3.10 (Python 3.11.4)
 - Kodi version: Kodi from Debian Media Center 20.0 Debian package version: 2:20.0+dfsg-2

**Comment by fuzzard** [comment]
This repo is only used for core bug reports. You'll need to raise this with whoever creates that addon.
