### ISSUE TITLE
Estuary: Kodi hangs on any TV Channel group opening 

### ISSUE THREAD

**Issue by boot2k3** [xbmc/xbmc#24086]
### Describe the bug
Here is a clear and concise description of what the problem is:
On the main screen if I try to open any TV channel group in TV section then Kodi hangs.
Error in kodi.log:
```
2023-11-11 19:43:34.361 T:978      info <general>: Loading skin file: MyPVRGuide.xml, load type: KEEP_IN_MEMORY
2023-11-11 19:43:34.496 T:978     error <general>: GetItem: EPG tag (0, 290) not found!
2023-11-11 19:43:34.496 T:978     error <general>: GetGridItemPtr: Got no EPG tag (0, 290)!
```
The same issue if I try to open Guide

## Expected Behavior
Here is a clear and concise description of what was expected to happen:
Kodi should open channel group section

## Actual Behavior

Kodi hangs and crash

### To Reproduce

1. Go to TV section on Estuary default skin
2. Go to TV Channel Groups section
3. Open any Group section

2nd way to reproduce:
1. Go to TV section on Estuary default skin
2. Open Guide

### Debuglog

The crashlog can be found here:
https://paste.kodi.tv/huferehanu.kodi
```
Thread 1 (Thread 0x7f8887b040 (LWP 12780)):
#0  0x000000000102c90c in PVR::CGUIEPGGridContainerModel::GetGridItemEndTime(int, int) const ()
#1  0x000000000102cabc in PVR::CGUIEPGGridContainer::GoToDate(CDateTime const&) ()
#2  0x000000000102d530 in PVR::CGUIEPGGridContainer::UpdateItems() ()
#3  0x000000000102da78 in PVR::CGUIEPGGridContainer::OnMessage(CGUIMessage&) ()
#4  0x0000000000cf4460 in CGUIControlGroup::SendControlMessage(CGUIMessage&) ()
#5  0x0000000000ba8118 in CGUIViewControl::UpdateContents(CGUIControl const*, int) const ()
#6  0x0000000000b90c18 in CGUIMediaWindow::OnFilterItems(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
#7  0x0000000000b91630 in CGUIMediaWindow::Update(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool) ()
#8  0x0000000000fdd928 in PVR::CGUIWindowPVRBase::Update(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool) ()
#9  0x0000000000fdedf4 in PVR::CGUIWindowPVRGuideBase::Update(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool) ()
#10 0x0000000000b84ec8 in CGUIMediaWindow::Refresh(bool) ()
#11 0x0000000000b93854 in CGUIMediaWindow::OnInitWindow() ()
#12 0x0000000000fe8aa8 in PVR::CGUIWindowPVRBase::OnInitWindow() ()
#13 0x0000000000d676fc in CGUIWindow::OnMessage(CGUIMessage&) ()
#14 0x0000000000d6d29c in CGUIWindowManager::ActivateWindow_Internal(int, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, bool, bool) ()
#15 0x0000000000d6c6c0 in CGUIWindowManager::ActivateWindow(int, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, bool, bool) ()
#16 0x000000000125b0c8 in ?? ()
#17 0x0000000001261e44 in CBuiltins::Execute(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
#18 0x0000000000df39a8 in CApplication::ExecuteXBMCAction(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::shared_ptr<CGUIListItem> const&) ()
#19 0x0000000000df8e08 in CApplication::OnMessage(CGUIMessage&) ()
#20 0x0000000000d5af40 in CGUIWindowManager::SendMessage(CGUIMessage&) ()
#21 0x0000000000cab758 in FAVOURITES_UTILS::ExecuteAction(CExecString const&) ()
#22 0x0000000000cab9c0 in CDirectoryProvider::OnClick(std::shared_ptr<CGUIListItem> const&) ()
#23 0x0000000000ceeb78 in CGUIBaseContainer::OnClick(int) ()
#24 0x0000000000d66ab4 in CGUIWindow::OnAction(CAction const&) ()
#25 0x0000000000d5b7d0 in CGUIWindowManager::HandleAction(CAction const&) const ()
#26 0x0000000000d5b948 in CGUIWindowManager::OnAction(CAction const&) const ()
#27 0x0000000000de09c0 in CApplication::OnAction(CAction const&) ()
#28 0x0000000000cc3904 in CInputManager::HandleKey(CKey const&) ()
#29 0x0000000000cc4ab8 in CInputManager::OnKeyUp(CKey const&) ()
#30 0x0000000000cc4b30 in CInputManager::OnEvent(XBMC_Event&) ()
#31 0x0000000000de1c04 in CApplication::HandlePortEvents() ()
#32 0x0000000000de21a0 in CApplication::FrameMove(bool, bool) ()
#33 0x0000000000dda494 in CApplication::Run() ()
#34 0x000000000078fe44 in main ()
```

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [X] Android
 - [ ] iOS
 - [ ] tvOS
 - [X] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: CoreELEC 21.0-Omega_devel_20231108095739
 - Kodi version: latest Kodi Omega nightly based on 08.11.2023 source

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by ksooo** [comment]
For unknown reasons (we cannot determine post mortem, sorry) your epg database (and at least also your addon database) is corrupted. Please cleanup your installation, especially your kodi userdata folder and the issue will be solved.

**Comment by boot2k3** [comment]
In this case it doesn't work correctly with EPG in MYSQL via epgdatabase settings.
