### ISSUE TITLE
UPnP Explodes with Omega Beta 1/2/master.

### ISSUE THREAD

**Issue by KyleSanderson** [xbmc/xbmc#24213]
### Describe the bug
Add a UPnP share to try and continue to work around the trivial performance issues present in vfs.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:
Listing of the network resource.

## Actual Behavior
```
12-10 15:44:33.387 10600 10629 E libsigchain: exiting due to SIG_DFL handler for signal 11
12-10 15:44:33.388 10600 10629 F libc    : Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 10629 (Thread-3), pid 10600 (.kodi.quietvoid)
12-10 15:44:33.470 10873 10873 I crash_dump32: obtaining output fd from tombstoned, type: kDebuggerdTombstone
12-10 15:44:33.471   472   472 I /system/bin/tombstoned: received crash request for pid 10629
12-10 15:44:33.471 10873 10873 I crash_dump32: performing dump of process 10600 (target tid = 10629)
12-10 15:44:33.495 10873 10873 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
12-10 15:44:33.496 10873 10873 F DEBUG   : Build fingerprint: 'Amazon/kara/kara:9/amz-p,release-keys'
12-10 15:44:33.496 10873 10873 F DEBUG   : Revision: '0'
12-10 15:44:33.496 10873 10873 F DEBUG   : ABI: 'arm'
12-10 15:44:33.496 10873 10873 F DEBUG   : pid: 10600, tid: 10629, oom: 0, name: Thread-3  >>> org.xbmc.kodi.quietvoid <<<
12-10 15:44:33.496 10873 10873 F DEBUG   : signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
12-10 15:44:33.496 10873 10873 F DEBUG   :     r0  00000000  r1  00002985  r2  00000006  r3  00000008
12-10 15:44:33.496 10873 10873 F DEBUG   :     r4  00002968  r5  00002985  r6  ab9bfc34  r7  0000010c
12-10 15:44:33.496 10873 10873 F DEBUG   :     r8  0000004d  r9  ab9bfc90  r10 0000000b  r11 00000000
12-10 15:44:33.496 10873 10873 F DEBUG   :     ip  ab9bfbd0  sp  ab9bfc20  lr  acc30051  pc  acc27e9e
12-10 15:44:33.566 10873 10873 F DEBUG   :
12-10 15:44:33.566 10873 10873 F DEBUG   : backtrace:
12-10 15:44:33.566 10873 10873 F DEBUG   :     #00 pc 0001ce9e  /system/lib/libc.so (abort+58)
12-10 15:44:33.567 10873 10873 F DEBUG   :     #01 pc 0000228b  /system/bin/app_process32 (art::SignalChain::Handler(int, siginfo*, void*)+742)
12-10 15:44:33.567 10873 10873 F DEBUG   :     #02 pc 000199d4  /system/lib/libc.so
12-10 15:44:33.567 10873 10873 F DEBUG   :     #03 pc 0001adc8  /system/lib/libc.so (strlen+68)
12-10 15:44:33.567 10873 10873 F DEBUG   :     #04 pc 0119b9cc  /data/app/org.xbmc.kodi.quietvoid-sKnH-oE_WpkmhVQ8oXGGFQ==/lib/arm/libkodi.so (CUtil::GetTitleFromPath(CURL const&, bool)+116)
12-10 15:44:33.567 10873 10873 F DEBUG   :     #05 pc 0119b91c  /data/app/org.xbmc.kodi.quietvoid-sKnH-oE_WpkmhVQ8oXGGFQ==/lib/arm/libkodi.so (CUtil::GetTitleFromPath(std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char>> const&, bool)+60)
12-10 15:44:33.567 10873 10873 F DEBUG   :     #06 pc 00fdec18  /data/app/org.xbmc.kodi.quietvoid-sKnH-oE_WpkmhVQ8oXGGFQ==/lib/arm/libkodi.so (CGUIDialogMediaSource::OnPathBrowse(int)+3452)
12-10 15:44:33.567 10873 10873 F DEBUG   :     #07 pc 00fdd82c  /data/app/org.xbmc.kodi.quietvoid-sKnH-oE_WpkmhVQ8oXGGFQ==/lib/arm/libkodi.so (CGUIDialogMediaSource::OnMessage(CGUIMessage&)+288)
12-10 15:44:33.567 10873 10873 F DEBUG   :     #08 pc 00f347ac  /data/app/org.xbmc.kodi.quietvoid-sKnH-oE_WpkmhVQ8oXGGFQ==/lib/arm/libkodi.so (CGUIButtonControl::OnClick()+124)
12-10 15:44:33.567 10873 10873 F DEBUG   :     #09 pc 00f33eac  /data/app/org.xbmc.kodi.quietvoid-sKnH-oE_WpkmhVQ8oXGGFQ==/lib/arm/libkodi.so (CGUIButtonControl::OnAction(CAction const&)+28)
12-10 15:44:33.567 10873 10873 F DEBUG   :     #10 pc 00f91abc  /data/app/org.xbmc.kodi.quietvoid-sKnH-oE_WpkmhVQ8oXGGFQ==/lib/arm/libkodi.so (CGUIWindow::OnAction(CAction const&)+164)
12-10 15:44:33.567 10873 10873 F DEBUG   :     #11 pc 00f99b10  /data/app/org.xbmc.kodi.quietvoid-sKnH-oE_WpkmhVQ8oXGGFQ==/lib/arm/libkodi.so (CGUIWindowManager::HandleAction(CAction const&) const+452)
12-10 15:44:33.567 10873 10873 F DEBUG   :     #12 pc 00f998ec  /data/app/org.xbmc.kodi.quietvoid-sKnH-oE_WpkmhVQ8oXGGFQ==/lib/arm/libkodi.so (CGUIWindowManager::OnAction(CAction const&) const+268)
12-10 15:44:33.567 10873 10873 F DEBUG   :     #13 pc 0100f8b4  /data/app/org.xbmc.kodi.quietvoid-sKnH-oE_WpkmhVQ8oXGGFQ==/lib/arm/libkodi.so (CApplication::OnAction(CAction const&)+508)
12-10 15:44:33.567 10873 10873 F DEBUG   :     #14 pc 00efb758  /data/app/org.xbmc.kodi.quietvoid-sKnH-oE_WpkmhVQ8oXGGFQ==/lib/arm/libkodi.so (CInputManager::HandleKey(CKey const&)+588)
12-10 15:44:33.567 10873 10873 F DEBUG   :     #15 pc 00efb4ac  /data/app/org.xbmc.kodi.quietvoid-sKnH-oE_WpkmhVQ8oXGGFQ==/lib/arm/libkodi.so (CInputManager::OnKeyUp(CKey const&)+136)
12-10 15:44:33.567 10873 10873 F DEBUG   :     #16 pc 00efae24  /data/app/org.xbmc.kodi.quietvoid-sKnH-oE_WpkmhVQ8oXGGFQ==/lib/arm/libkodi.so (CInputManager::OnEvent(XBMC_Event&)+492)
12-10 15:44:33.567 10873 10873 F DEBUG   :     #17 pc 0100f2a0  /data/app/org.xbmc.kodi.quietvoid-sKnH-oE_WpkmhVQ8oXGGFQ==/lib/arm/libkodi.so (CApplication::HandlePortEvents()+1276)
12-10 15:44:33.567 10873 10873 F DEBUG   :     #18 pc 0101c8cc  /data/app/org.xbmc.kodi.quietvoid-sKnH-oE_WpkmhVQ8oXGGFQ==/lib/arm/libkodi.so (CApplication::FrameMove(bool, bool)+400)
12-10 15:44:33.567 10873 10873 F DEBUG   :     #19 pc 00f9ad20  /data/app/org.xbmc.kodi.quietvoid-sKnH-oE_WpkmhVQ8oXGGFQ==/lib/arm/libkodi.so (CGUIWindowManager::ProcessRenderLoop(bool)+224)
12-10 15:44:33.567 10873 10873 F DEBUG   :     #20 pc 00f4ba68  /data/app/org.xbmc.kodi.quietvoid-sKnH-oE_WpkmhVQ8oXGGFQ==/lib/arm/libkodi.so (CGUIDialog::Open_Internal(bool, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char>> const&)+272)
12-10 15:44:33.567 10873 10873 F DEBUG   :     #21 pc 00f4bb54  /data/app/org.xbmc.kodi.quietvoid-sKnH-oE_WpkmhVQ8oXGGFQ==/lib/arm/libkodi.so (CGUIDialog::Open(bool, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char>> const&)+164)
12-10 15:44:33.567 10873 10873 F DEBUG   :     #22 pc 00fdffb0  /data/app/org.xbmc.kodi.quietvoid-sKnH-oE_WpkmhVQ8oXGGFQ==/lib/arm/libkodi.so (CGUIDialogMediaSource::ShowAndAddMediaSource(std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char>> const&)+152)
12-10 15:44:33.567 10873 10873 F DEBUG   :     #23 pc 00ca19ec  /data/app/org.xbmc.kodi.quietvoid-sKnH-oE_WpkmhVQ8oXGGFQ==/lib/arm/libkodi.so (CGUIWindowVideoNav::OnAddMediaSource()+44)
12-10 15:44:33.567 10873 10873 F DEBUG   :     #24 pc 00d9b1a0  /data/app/org.xbmc.kodi.quietvoid-sKnH-oE_WpkmhVQ8oXGGFQ==/lib/arm/libkodi.so (CGUIMediaWindow::OnClick(int, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char>> const&)+628)
12-10 15:44:33.567 10873 10873 F DEBUG   :     #25 pc 00ca1b24  /data/app/org.xbmc.kodi.quietvoid-sKnH-oE_WpkmhVQ8oXGGFQ==/lib/arm/libkodi.so (CGUIWindowVideoNav::OnClick(int, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char>> const&)+216)
12-10 15:44:33.567 10873 10873 F DEBUG   :     #26 pc 00d9c580  /data/app/org.xbmc.kodi.quietvoid-sKnH-oE_WpkmhVQ8oXGGFQ==/lib/arm/libkodi.so (CGUIMediaWindow::OnSelect(int)+76)
12-10 15:44:33.567 10873 10873 F DEBUG   :     #27 pc 00c92bd4  /data/app/org.xbmc.kodi.quietvoid-sKnH-oE_WpkmhVQ8oXGGFQ==/lib/arm/libkodi.so (CGUIWindowVideoBase::OnSelect(int)+120)
12-10 15:44:33.567 10873 10873 F DEBUG   :     #28 pc 00d953fc  /data/app/org.xbmc.kodi.quietvoid-sKnH-oE_WpkmhVQ8oXGGFQ==/lib/arm/libkodi.so (CGUIMediaWindow::OnMessage(CGUIMessage&)+2000)
12-10 15:44:33.567 10873 10873 F DEBUG   :     #29 pc 00c903ac  /data/app/org.xbmc.kodi.quietvoid-sKnH-oE_WpkmhVQ8oXGGFQ==/lib/arm/libkodi.so (CGUIWindowVideoBase::OnMessage(CGUIMessage&)+1020)
12-10 15:44:33.568 10873 10873 F DEBUG   :     #30 pc 00c99fb4  /data/app/org.xbmc.kodi.quietvoid-sKnH-oE_WpkmhVQ8oXGGFQ==/lib/arm/libkodi.so (CGUIWindowVideoNav::OnMessage(CGUIMessage&)+296)
12-10 15:44:33.568 10873 10873 F DEBUG   :     #31 pc 00f2ed30  /data/app/org.xbmc.kodi.quietvoid-sKnH-oE_WpkmhVQ8oXGGFQ==/lib/arm/libkodi.so (CGUIBaseContainer::OnClick(int)+296)
12-10 15:44:33.568 10873 10873 F DEBUG   :     #32 pc 00f2e594  /data/app/org.xbmc.kodi.quietvoid-sKnH-oE_WpkmhVQ8oXGGFQ==/lib/arm/libkodi.so (CGUIBaseContainer::OnAction(CAction const&)+1192)
12-10 15:44:33.568 10873 10873 F DEBUG   :     #33 pc 00f91abc  /data/app/org.xbmc.kodi.quietvoid-sKnH-oE_WpkmhVQ8oXGGFQ==/lib/arm/libkodi.so (CGUIWindow::OnAction(CAction const&)+164)
12-10 15:44:33.568 10873 10873 F DEBUG   :     #34 pc 00d946c8  /data/app/org.xbmc.kodi.quietvoid-sKnH-oE_WpkmhVQ8oXGGFQ==/lib/arm/libkodi.so (CGUIMediaWindow::OnAction(CAction const&)+76)
12-10 15:44:33.568 10873 10873 F DEBUG   :     #35 pc 00c99e0c  /data/app/org.xbmc.kodi.quietvoid-sKnH-oE_WpkmhVQ8oXGGFQ==/lib/arm/libkodi.so (CGUIWindowVideoNav::OnAction(CAction const&)+284)
12-10 15:44:33.568 10873 10873 F DEBUG   :     #36 pc 00f99b8c  /data/app/org.xbmc.kodi.quietvoid-sKnH-oE_WpkmhVQ8oXGGFQ==/lib/arm/libkodi.so (CGUIWindowManager::HandleAction(CAction const&) const+576)
12-10 15:44:33.568 10873 10873 F DEBUG   :     #37 pc 00f998ec  /data/app/org.xbmc.kodi.quietvoid-sKnH-oE_WpkmhVQ8oXGGFQ==/lib/arm/libkodi.so (CGUIWindowManager::OnAction(CAction const&) const+268)
12-10 15:44:33.568 10873 10873 F DEBUG   :     #38 pc 0100f8b4  /data/app/org.xbmc.kodi.quietvoid-sKnH-oE_WpkmhVQ8oXGGFQ==/lib/arm/libkodi.so (CApplication::OnAction(CAction const&)+508)
12-10 15:44:33.568 10873 10873 F DEBUG   :     #39 pc 00efb758  /data/app/org.xbmc.kodi.quietvoid-sKnH-oE_WpkmhVQ8oXGGFQ==/lib/arm/libkodi.so (CInputManager::HandleKey(CKey const&)+588)
12-10 15:44:33.568 10873 10873 F DEBUG   :     #40 pc 00efb4ac  /data/app/org.xbmc.kodi.quietvoid-sKnH-oE_WpkmhVQ8oXGGFQ==/lib/arm/libkodi.so (CInputManager::OnKeyUp(CKey const&)+136)
12-10 15:44:33.568 10873 10873 F DEBUG   :     #41 pc 00efae24  /data/app/org.xbmc.kodi.quietvoid-sKnH-oE_WpkmhVQ8oXGGFQ==/lib/arm/libkodi.so (CInputManager::OnEvent(XBMC_Event&)+492)
12-10 15:44:33.568 10873 10873 F DEBUG   :     #42 pc 0100f2a0  /data/app/org.xbmc.kodi.quietvoid-sKnH-oE_WpkmhVQ8oXGGFQ==/lib/arm/libkodi.so (CApplication::HandlePortEvents()+1276)
12-10 15:44:33.568 10873 10873 F DEBUG   :     #43 pc 0101c8cc  /data/app/org.xbmc.kodi.quietvoid-sKnH-oE_WpkmhVQ8oXGGFQ==/lib/arm/libkodi.so (CApplication::FrameMove(bool, bool)+400)
12-10 15:44:33.568 10873 10873 F DEBUG   :     #44 pc 0101d080  /data/app/org.xbmc.kodi.quietvoid-sKnH-oE_WpkmhVQ8oXGGFQ==/lib/arm/libkodi.so (CApplication::Run()+504)
12-10 15:44:33.568 10873 10873 F DEBUG   :     #45 pc 00eb6770  /data/app/org.xbmc.kodi.quietvoid-sKnH-oE_WpkmhVQ8oXGGFQ==/lib/arm/libkodi.so (XBMC_Run+244)
12-10 15:44:33.568 10873 10873 F DEBUG   :     #46 pc 009b02dc  /data/app/org.xbmc.kodi.quietvoid-sKnH-oE_WpkmhVQ8oXGGFQ==/lib/arm/libkodi.so (CXBMCApp::run()+288)
12-10 15:44:33.568 10873 10873 F DEBUG   :     #47 pc 009be608  /data/app/org.xbmc.kodi.quietvoid-sKnH-oE_WpkmhVQ8oXGGFQ==/lib/arm/libkodi.so (_ZNSt6__ndk114__thread_proxyINS_5tupleIJNS_10unique_ptrINS_15__thread_structENS_14default_deleteIS3_EEEEM8CXBMCAppFvvEPS7_EEEEEPvSC_+60)
12-10 15:44:33.568 10873 10873 F DEBUG   :     #48 pc 00063775  /system/lib/libc.so (__pthread_start(void*)+22)
12-10 15:44:33.568 10873 10873 F DEBUG   :     #49 pc 0001e061  /system/lib/libc.so (__start_thread+24)
12-10 15:44:34.323   472   472 E /system/bin/tombstoned: Tombstone written to: /data/tombstones/tombstone_07
12-10 15:44:34.325   531 10876 I CrashReporterActivityManagerCallback: CPU cores online info: 1111
```

## Possible Fix
Check your pointers.

### To Reproduce

1. `go install github.com/anacrolix/dms@latest`
2. `dms`
3. Add the UPnP host.
4. Click ok, then browse into the share again and watch Kodi not check for null.
5. Back to the Android homescreen.

### Your Environment
Used Operating system:

 - [x] Android
 - [x] iOS
 - [x] tvOS
 - [x] Linux
 - [x] macOS
 - [x] Windows
 - [x] Windows UWP

 - Operating system version/name:
 - Kodi version: Kodi 21.0 "Omega" Beta 1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### Describe the bug
Here is a clear and concise description of what the problem is:

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by enen92** [comment]
Is this vanilla Kodi? By the org.xbmc.kodi.quietvoid app id it doesn't seem like it is...
Anyway will try to reproduce tomorrow.

**Comment by neo1973** [comment]
Can reproduce with current master:

<details>
<summary>stack trace</summary>

```
lib/libUPnP/Neptune/Source/Core/NptXml.cpp:634:32: runtime error: null pointer passed as argument 2, which is declared to never be null
/usr/include/string.h:44:28: note: nonnull attribute specified here
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior lib/libUPnP/Neptune/Source/Core/NptXml.cpp:634:32 in 
AddressSanitizer:DEADLYSIGNAL
=================================================================
==836804==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x7f0d63778edd bp 0x7ffe34b29460 sp 0x7ffe34b28c08 T0)
==836804==The signal is caused by a READ memory access.
==836804==Hint: address points to the zero page.
    #0 0x7f0d63778edd  (/usr/lib/libc.so.6+0x15aedd) (BuildId: 8bfe03f6bf9b6a6e2591babd0bbc266837d8f658)
    #1 0x555d1d9810dc in __interceptor_strlen.part.0 (/home/mark/Coding/Repos/kodi-git/build_clang_debug_sanitizer/kodi.bin+0xb3d30dc) (BuildId: 2cb8b2b139bb484efe33ec446311d8fe17e38544)
    #2 0x555d1da73cdc in std::char_traits<char>::length(char const*) /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../include/c++/13.2.1/bits/char_traits.h:409:9
    #3 0x555d1da89571 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>::assign(char const*) /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../include/c++/13.2.1/bits/basic_string.h:1673:6
    #4 0x555d1da82ee0 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>::operator=(char const*) /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../include/c++/13.2.1/bits/basic_string.h:812:22
    #5 0x555d22f5bda6 in CUtil::GetTitleFromPath[abi:cxx11](CURL const&, bool) xbmc/Util.cpp:315:17
    #6 0x555d22f5b699 in CUtil::GetTitleFromPath(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const&, bool) xbmc/Util.cpp:302:10
    #7 0x555d21cd0eda in CGUIDialogMediaSource::OnPathBrowse(int) xbmc/dialogs/GUIDialogMediaSource.cpp:412:16
    #8 0x555d21cca4ad in CGUIDialogMediaSource::OnMessage(CGUIMessage&) xbmc/dialogs/GUIDialogMediaSource.cpp:85:7
    #9 0x555d2145ed56 in CGUIControl::SendWindowMessage(CGUIMessage&) const xbmc/guilib/GUIControl.cpp:313:21
    #10 0x555d21422771 in CGUIButtonControl::OnClick() xbmc/guilib/GUIButtonControl.cpp:387:3
    #11 0x555d2141ada6 in CGUIButtonControl::OnAction(CAction const&) xbmc/guilib/GUIButtonControl.cpp:208:5
    #12 0x555d21933af1 in CGUIWindow::OnAction(CAction const&) xbmc/guilib/GUIWindow.cpp:425:27
    #13 0x555d21551ed4 in CGUIDialog::OnAction(CAction const&) xbmc/guilib/GUIDialog.cpp:72:22
    #14 0x555d21990a5b in CGUIWindowManager::HandleAction(CAction const&) const xbmc/guilib/GUIWindowManager.cpp:1169:21
    #15 0x555d2198fae3 in CGUIWindowManager::OnAction(CAction const&) const xbmc/guilib/GUIWindowManager.cpp:1138:11
    #16 0x555d21e9ca52 in CApplication::OnAction(CAction const&) xbmc/application/Application.cpp:977:54
    #17 0x555d21150e21 in CInputManager::ExecuteInputAction(CAction const&) xbmc/input/InputManager.cpp:744:29
    #18 0x555d2115d882 in CInputManager::HandleKey(CKey const&) xbmc/input/InputManager.cpp:678:10
    #19 0x555d2115832c in CInputManager::OnKeyUp(CKey const&) xbmc/input/InputManager.cpp:691:5
    #20 0x555d21153777 in CInputManager::OnEvent(XBMC_Event&) xbmc/input/InputManager.cpp:359:7
    #21 0x555d21e9a488 in CApplication::HandlePortEvents() xbmc/application/Application.cpp:306:43
    #22 0x555d21eecae2 in CApplication::FrameMove(bool, bool) xbmc/application/Application.cpp:1799:5
    #23 0x555d2199aaf7 in CGUIWindowManager::ProcessRenderLoop(bool) xbmc/guilib/GUIWindowManager.cpp:1416:18
    #24 0x555d21555c6b in CGUIDialog::Open_Internal(bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const&) xbmc/guilib/GUIDialog.cpp:179:57
    #25 0x555d215565d1 in CGUIDialog::Open(bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const&) xbmc/guilib/GUIDialog.cpp:201:5
    #26 0x555d2155499d in CGUIDialog::Open(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const&) xbmc/guilib/GUIDialog.cpp:187:15
    #27 0x555d21cd8ac7 in CGUIDialogMediaSource::ShowAndAddMediaSource(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const&) xbmc/dialogs/GUIDialogMediaSource.cpp:132:11
    #28 0x555d1f7a0bc1 in CGUIWindowVideoNav::OnAddMediaSource() xbmc/video/windows/GUIWindowVideoNav.cpp:987:10
    #29 0x555d20158143 in CGUIMediaWindow::OnClick(int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const&) xbmc/windows/GUIMediaWindow.cpp:1035:9
    #30 0x555d1f7a4d30 in CGUIWindowVideoNav::OnClick(int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const&) xbmc/video/windows/GUIWindowVideoNav.cpp:1079:31
    #31 0x555d20161621 in CGUIMediaWindow::OnSelect(int) xbmc/windows/GUIMediaWindow.cpp:1188:10
    #32 0x555d1f7123bc in CGUIWindowVideoBase::OnSelect(int) xbmc/video/windows/GUIWindowVideoBase.cpp:536:27
    #33 0x555d20123650 in CGUIMediaWindow::OnMessage(CGUIMessage&) xbmc/windows/GUIMediaWindow.cpp:312:11
    #34 0x555d1f6fd0fe in CGUIWindowVideoBase::OnMessage(CGUIMessage&) xbmc/video/windows/GUIWindowVideoBase.cpp:205:27
    #35 0x555d1f76aa2b in CGUIWindowVideoNav::OnMessage(CGUIMessage&) xbmc/video/windows/GUIWindowVideoNav.cpp:240:31
    #36 0x555d2145ed56 in CGUIControl::SendWindowMessage(CGUIMessage&) const xbmc/guilib/GUIControl.cpp:313:21
    #37 0x555d213d1991 in CGUIBaseContainer::OnClick(int) xbmc/guilib/GUIBaseContainer.cpp:887:10
    #38 0x555d213ce4fc in CGUIBaseContainer::OnAction(CAction const&) xbmc/guilib/GUIBaseContainer.cpp:464:28
    #39 0x555d215a5945 in CGUIFixedListContainer::OnAction(CAction const&) xbmc/guilib/GUIFixedListContainer.cpp:70:29
    #40 0x555d21933af1 in CGUIWindow::OnAction(CAction const&) xbmc/guilib/GUIWindow.cpp:425:27
    #41 0x555d2011deb9 in CGUIMediaWindow::OnAction(CAction const&) xbmc/windows/GUIMediaWindow.cpp:191:19
    #42 0x555d1f6fa36f in CGUIWindowVideoBase::OnAction(CAction const&) xbmc/video/windows/GUIWindowVideoBase.cpp:108:27
    #43 0x555d1f76320d in CGUIWindowVideoNav::OnAction(CAction const&) xbmc/video/windows/GUIWindowVideoNav.cpp:92:31
    #44 0x555d2199117c in CGUIWindowManager::HandleAction(CAction const&) const xbmc/guilib/GUIWindowManager.cpp:1193:20
    #45 0x555d2198fae3 in CGUIWindowManager::OnAction(CAction const&) const xbmc/guilib/GUIWindowManager.cpp:1138:11
    #46 0x555d21e9ca52 in CApplication::OnAction(CAction const&) xbmc/application/Application.cpp:977:54
    #47 0x555d21150e21 in CInputManager::ExecuteInputAction(CAction const&) xbmc/input/InputManager.cpp:744:29
    #48 0x555d2115d882 in CInputManager::HandleKey(CKey const&) xbmc/input/InputManager.cpp:678:10
    #49 0x555d2115832c in CInputManager::OnKeyUp(CKey const&) xbmc/input/InputManager.cpp:691:5
    #50 0x555d21153777 in CInputManager::OnEvent(XBMC_Event&) xbmc/input/InputManager.cpp:359:7
    #51 0x555d21e9a488 in CApplication::HandlePortEvents() xbmc/application/Application.cpp:306:43
    #52 0x555d21eecae2 in CApplication::FrameMove(bool, bool) xbmc/application/Application.cpp:1799:5
    #53 0x555d21ef0af0 in CApplication::Run() xbmc/application/Application.cpp:1903:7
    #54 0x555d20d2b2c3 in XBMC_Run xbmc/platform/xbmc.cpp:61:26
    #55 0x555d1da6bd79 in main xbmc/platform/posix/main.cpp:70:16
    #56 0x7f0d63645ccf  (/usr/lib/libc.so.6+0x27ccf) (BuildId: 8bfe03f6bf9b6a6e2591babd0bbc266837d8f658)
    #57 0x7f0d63645d89 in __libc_start_main (/usr/lib/libc.so.6+0x27d89) (BuildId: 8bfe03f6bf9b6a6e2591babd0bbc266837d8f658)
    #58 0x555d1d932474 in _start (/home/mark/Coding/Repos/kodi-git/build_clang_debug_sanitizer/kodi.bin+0xb384474) (BuildId: 2cb8b2b139bb484efe33ec446311d8fe17e38544)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (/usr/lib/libc.so.6+0x15aedd) (BuildId: 8bfe03f6bf9b6a6e2591babd0bbc266837d8f658) 
==836804==ABORTING
```
</details>

**Comment by KyleSanderson** [comment]
Enabling the UPnP Service on Kodi seems to work around it as well. Outside of the bug the setup seems very odd - there's no scraper integration at all??

**Comment by neo1973** [comment]
#24215 should fix the crash.

**Comment by KyleSanderson** [comment]
Thank you
