### ISSUE TITLE
Attempting to play video plugin content via .strm file scanned to library crashes Kodi

### ISSUE THREAD

**Issue by jurialmunkey** [xbmc/xbmc#24311]
### Describe the bug
Here is a clear and concise description of what the problem is:

When attempting to play an episode of tvshow using a .strm file linked to a video plugin Kodi will crash (Windows latest nightly).

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Kodi doesn't crash and instead plays the plugin path

## Actual Behavior

Kodi crashes after clicking a .strm file with a plugin path.

### To Reproduce

Create a .strm file for a tvshow episode (in my test I used Ahsoka S01E01 as I already had strm files for it in my library).

To test I put the path for the first result from Youtube plugin into the .strm file but any playable/resolvable plugin path will do
`plugin://plugin.video.youtube/play/?video_id=d6Pcp944sRI`

Scan it to library then navigate to that tvshow and attempt to play that episode.

### Debuglog

The debuglog can be found here:

[kodi.log](https://github.com/xbmc/xbmc/files/13760602/kodi.log)

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 11 23H2
 - Kodi version: Omega 21.0-BETA2 (20.90.821) Git:20231222-d9bc400862

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by graysky2** [comment]
I can confirm this bug on Linux build from HEAD.  My `.strm` files contain a rtsp line like `rtsp://username:password@10.1.0.105`.  If I add that to my library, then navigate to play it, kodi crashes.  If I navigate to the file on the file system, it plays without crashing.  Definitely related to library function.  If I downgrade to the latest commit from the Nexus branch, the bug is not present.

**Comment by neo1973** [comment]
Can confirm the problem. Here is the stack trace:
<details>
<summary>Stack trace</summary>

```
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at pthread_kill.c:44
#1  0x00007feb05aac8a3 in __pthread_kill_internal (signo=6, threadid=<optimized out>) at pthread_kill.c:78
#2  0x00007feb05a5c668 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#3  0x00007feb05a444b8 in __GI_abort () at abort.c:79
#4  0x00007feb05cdd3b2 in std::__glibcxx_assert_fail(char const*, int, char const*, char const*) (file=<optimized out>, line=<optimized out>, function=<optimized out>, condition=<optimized out>) at /usr/src/debug/gcc/gcc/libstdc++-v3/src/c++11/debug.cc:61
#5  0x000055f45ca26058 in std::unique_ptr<PLAYLIST::CPlayList, std::default_delete<PLAYLIST::CPlayList> >::operator*() const (this=0x7feaffe90420) at /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../include/c++/13.2.1/bits/unique_ptr.h:453
#6  0x000055f45db5ccc9 in CGUIWindowVideoBase::LoadPlayList(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int) (this=0x61d00005be80, strPlayList="videodb://movies/titles/50", playlistId=1) at xbmc/video/windows/GUIWindowVideoBase.cpp:1049
#7  0x000055f45db5e536 in CGUIWindowVideoBase::PlayItem(std::shared_ptr<CFileItem> const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (this=0x61d00005be80, pItem=std::shared_ptr<CFileItem> (use count 9, weak count 0) = {...}, player="") at xbmc/video/windows/GUIWindowVideoBase.cpp:1083
#8  0x000055f45db72cf6 in (anonymous namespace)::CVideoSelectActionProcessor::OnPlaySelected() (this=0x7feaffd65b40) at xbmc/video/windows/GUIWindowVideoBase.cpp:573
#9  0x000055f45dc74144 in VIDEO::GUILIB::CVideoPlayActionProcessorBase::Process(VIDEO::GUILIB::Action) (this=0x7feaffd65b40, action=VIDEO::GUILIB::ACTION_PLAY_FROM_BEGINNING) at xbmc/video/guilib/VideoPlayActionProcessor.cpp:70
#10 0x000055f45dc75411 in VIDEO::GUILIB::CVideoSelectActionProcessorBase::Process(VIDEO::GUILIB::Action) (this=0x7feaffd65b40, action=VIDEO::GUILIB::ACTION_PLAY_FROM_BEGINNING) at xbmc/video/guilib/VideoSelectActionProcessor.cpp:41
#11 0x000055f45dc73f59 in VIDEO::GUILIB::CVideoPlayActionProcessorBase::Process(VIDEO::GUILIB::Action) (this=0x7feaffd65b40, action=VIDEO::GUILIB::ACTION_PLAY_OR_RESUME) at xbmc/video/guilib/VideoPlayActionProcessor.cpp:63
#12 0x000055f45dc75411 in VIDEO::GUILIB::CVideoSelectActionProcessorBase::Process(VIDEO::GUILIB::Action) (this=0x7feaffd65b40, action=VIDEO::GUILIB::ACTION_PLAY_OR_RESUME) at xbmc/video/guilib/VideoSelectActionProcessor.cpp:41
#13 0x000055f45dc739ff in VIDEO::GUILIB::CVideoPlayActionProcessorBase::ProcessAction(VIDEO::GUILIB::Action) (this=0x7feaffd65b40, action=VIDEO::GUILIB::ACTION_PLAY_OR_RESUME) at xbmc/video/guilib/VideoPlayActionProcessor.cpp:47
#14 0x000055f45db47624 in CGUIWindowVideoBase::OnFileAction(int, VIDEO::GUILIB::Action, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (this=0x61d00005be80, iItem=25, action=VIDEO::GUILIB::ACTION_PLAY_OR_RESUME, player="") at xbmc/video/windows/GUIWindowVideoBase.cpp:604
#15 0x000055f45db46d43 in CGUIWindowVideoBase::OnSelect(int) (this=0x61d00005be80, iItem=25) at xbmc/video/windows/GUIWindowVideoBase.cpp:537
#16 0x000055f45e552789 in CGUIMediaWindow::OnMessage(CGUIMessage&) (this=0x61d00005be80, message=...) at xbmc/windows/GUIMediaWindow.cpp:312
#17 0x000055f45db31b3f in CGUIWindowVideoBase::OnMessage(CGUIMessage&) (this=0x61d00005be80, message=...) at xbmc/video/windows/GUIWindowVideoBase.cpp:206
#18 0x000055f45db9ebb4 in CGUIWindowVideoNav::OnMessage(CGUIMessage&) (this=0x61d00005be80, message=...) at xbmc/video/windows/GUIWindowVideoNav.cpp:240
#19 0x000055f45f894187 in CGUIControl::SendWindowMessage(CGUIMessage&) const (this=0x619001707f80, message=...) at xbmc/guilib/GUIControl.cpp:313
#20 0x000055f45f806d84 in CGUIBaseContainer::OnClick(int) (this=0x619001707f80, actionID=7) at xbmc/guilib/GUIBaseContainer.cpp:887
#21 0x000055f45f8038ed in CGUIBaseContainer::OnAction(CAction const&) (this=0x619001707f80, action=...) at xbmc/guilib/GUIBaseContainer.cpp:464
#22 0x000055f45f9db006 in CGUIFixedListContainer::OnAction(CAction const&) (this=0x619001707f80, action=...) at xbmc/guilib/GUIFixedListContainer.cpp:70
#23 0x000055f45fd692e2 in CGUIWindow::OnAction(CAction const&) (this=0x61d00005be80, action=...) at xbmc/guilib/GUIWindow.cpp:425
#24 0x000055f45e54cfda in CGUIMediaWindow::OnAction(CAction const&) (this=0x61d00005be80, action=...) at xbmc/windows/GUIMediaWindow.cpp:191
#25 0x000055f45db2edb0 in CGUIWindowVideoBase::OnAction(CAction const&) (this=0x61d00005be80, action=...) at xbmc/video/windows/GUIWindowVideoBase.cpp:109
#26 0x000055f45db9737e in CGUIWindowVideoNav::OnAction(CAction const&) (this=0x61d00005be80, action=...) at xbmc/video/windows/GUIWindowVideoNav.cpp:92
#27 0x000055f45fdc6dbd in CGUIWindowManager::HandleAction(CAction const&) const (this=0x614000088a40, action=...) at xbmc/guilib/GUIWindowManager.cpp:1199
#28 0x000055f45fdc5724 in CGUIWindowManager::OnAction(CAction const&) const (this=0x614000088a40, action=...) at xbmc/guilib/GUIWindowManager.cpp:1144
#29 0x000055f4602d1050 in CApplication::OnAction(CAction const&) (this=0x618000000080, action=...) at xbmc/application/Application.cpp:979
#30 0x000055f45f586502 in CInputManager::ExecuteInputAction(CAction const&) (this=0x617000038080, action=...) at xbmc/input/InputManager.cpp:744
#31 0x000055f45f592f63 in CInputManager::HandleKey(CKey const&) (this=0x617000038080, key=...) at xbmc/input/InputManager.cpp:678
#32 0x000055f45f58da0d in CInputManager::OnKeyUp(CKey const&) (this=0x617000038080, key=...) at xbmc/input/InputManager.cpp:691
#33 0x000055f45f588e58 in CInputManager::OnEvent(XBMC_Event&) (this=0x617000038080, newEvent=...) at xbmc/input/InputManager.cpp:359
#34 0x000055f4602ceba9 in CApplication::HandlePortEvents() (this=0x618000000080) at xbmc/application/Application.cpp:309
#35 0x000055f4603202d3 in CApplication::FrameMove(bool, bool) (this=0x618000000080, processEvents=true, processGUI=true) at xbmc/application/Application.cpp:1799
#36 0x000055f4603242a1 in CApplication::Run() (this=0x618000000080) at xbmc/application/Application.cpp:1903
#37 0x000055f45f15c384 in XBMC_Run(bool) (renderGUI=true) at xbmc/platform/xbmc.cpp:61
#38 0x000055f45be986ca in main(int, char**) (argc=1, argv=0x7ffed73b16d8) at xbmc/platform/posix/main.cpp:70
```
</details>

The problem is that `pPlayList` here is a nullptr:

https://github.com/xbmc/xbmc/blob/80653dc05ff9af0a6fb96f530f6d3be0cd3fc308/xbmc/video/windows/GUIWindowVideoBase.cpp#L1049

According to git bisect the problem was introduced in 6be19d0f16375e9334eb30004f9cc8695b138899 which is part of #24224.
