### ISSUE TITLE
Retrospect cause kodi to crash during exit in PyObject_GC_UnTrack 

### ISSUE THREAD

**Issue by obaterspok** [xbmc/xbmc#24440]
### Describe the bug
Here is a clear and concise description of what the problem is:

Starting with an empty .kodi and just adding retrospect causes a crash kodi to crash during exit. 
I don't even have to open retrospect which means the retrospect log file is not created. That's why I didn't create the issue in the retrospect repository. (the retrospect plugin work just fine)
I tried using other plugins such as YouTube (without installing retrospekt) and there I don't get a crash. 

Please note that I'm using Fedora 39 which has Python **3.12**

#0  0x00007f91fd3e92b1 in PyObject_GC_UnTrack () at /lib64/libpython3.12.so.1.0
#1  0x00007f91fd4be140 in module_dealloc () at /lib64/libpython3.12.so.1.0
#2  0x00007f91fd3f9b87 in meth_dealloc () at /lib64/libpython3.12.so.1.0
#3  0x00007f91fd3ec157 in insertdict () at /lib64/libpython3.12.so.1.0
#4  0x00007f91fd44fe60 in _PyModule_ClearDict () at /lib64/libpython3.12.so.1.0
#5  0x00007f91fd4bde94 in finalize_modules () at /lib64/libpython3.12.so.1.0
#6  0x00007f91fd4cb494 in Py_EndInterpreter () at /lib64/libpython3.12.so.1.0
#7  0x0000000001bdb613 in CPythonInvoker::onExecutionDone() ()
#8  0x0000000002ce925b in CLanguageInvokerThread::OnExit() ()

...
2024-01-06 15:18:52.617 T:24491   debug <general>: Thread EventServer 140049538602688 terminating
2024-01-06 15:18:52.696 T:24492   debug <general>: Thread WSDiscoveryListenerUDP 140049530209984 terminating
2024-01-06 15:18:52.697 T:24385    info <general>: CWSDiscoveryListenerUDP::Stop - Stopped
2024-01-06 15:18:52.697 T:24385   debug <general>: NetworkMessage - Waiting for network services to stop
2024-01-06 15:18:52.697 T:24385    info <general>: stopping zeroconf publishing
2024-01-06 15:18:52.698 T:24385   debug <general>: CServiceAddonManager: stopping plugin.video.retrospect.
2024-01-06 15:18:52.698 T:24385    info <general>: CServiceAddonManager: failed to stop plugin.video.retrospect (may have ended)
2024-01-06 15:18:52.698 T:24385   debug <general>: CServiceAddonManager: stopping plugin.video.youtube.
2024-01-06 15:18:52.698 T:24385   debug <general>: CPythonInvoker(1, /home/kodi/.kodi/addons/plugin.video.youtube/resources/lib/startup.py): trigger Monitor abort request
2024-01-06 15:18:52.698 T:24488   debug <general>: [plugin.video.youtube] PlaybackMonitor active threads: ||
2024-01-06 15:18:52.699 T:24488   debug <general>: CPythonInvoker(1, /home/kodi/.kodi/addons/plugin.video.youtube/resources/lib/startup.py): script successfully run
2024-01-06 15:18:52.699 T:24488   debug <general>: onExecutionDone(1, /home/kodi/.kodi/addons/plugin.video.youtube/resources/lib/startup.py)
202

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

No crash at exit

## Actual Behavior

Well, it crashes during exit

### To Reproduce

1. Use kodi master (or Nexus I believe) with a python 3.12 distro
2. Install retrospect addon
3. Open plugin (might need to do it first time if you dont get a crash)
4. exit

### Debuglog

The debuglog can be found here:
https://paste.centos.org/view/f51b3960
crashlog:
https://paste.centos.org/view/c8be7559

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Fedora 39 with Python 3.12
- Kodi version: Kodi master as of 2024-01-05 (also tried with Nexus)
- Retrospect version: 5.7.4

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by mooninite** [comment]
This isn't isolated to one add-on. The YouTube and MLB.tv addons also cause the same crash after they are installed. Other add-ons such as Speedtester do not cause a crash.

**Comment by obaterspok** [comment]
I just checked this again with Omega and same problem. One thing I noticed was that it's indeeded caused by YouTube-addon as Kodi didn't crash if I disabled YT-addon (Retrospekt has a dependency to YT-addon)

Another thing I noticed was that if I enabled YT after a restart then it would exit without crash.
Doesn't this sound like its the same "multi phase init" as described in #19961

**Comment by neo1973** [comment]
If the order of plugins started/stopped matters it could potentially be this Python bug: https://github.com/python/cpython/issues/116510

But I'm on Arch and they aren't on Python 3.12 yet so I can't confirm.

**Comment by neo1973** [comment]
Now that Arch switched to 3.12 I'm also seeing this issue, even with Retrospect disabled. This very much looks like an upstream Python problem and I left a comment in the Python issue I mentioned before.

**Comment by obaterspok** [comment]
@neo1973, I have verified the python PR in 116510 that you linked to fixes the crash. Thanks a lot!

**Comment by mooninite** [comment]
I verified the backport to 3.12 also fixes my Kodi crashing issue, too. Yay.

**Comment by obaterspok** [comment]
I'm closing this as I've patched Python locally and the fix will not be backported from the upcoming 3.13 release of Python.
