### ISSUE TITLE
script.module.urllib3 2.1.0 - IncompleteRead error (same code works fine in urllib3 1.*)

### ISSUE THREAD

**Issue by henryjfry** [xbmc/xbmc#24489]
### Describe the bug
Here is a clear and concise description of what the problem is:

This has been raised as an issue on Urllib3:

https://github.com/urllib3/urllib3/issues/3277

However the current version of script.module.urllib3-2.1.0.zip exhibits this error and I didnt know if I should post an issue for Kodi as its a fairly core python module:

````
https://mirrors.kodi.tv/addons/matrix/script.module.urllib3/
````
https://mirrors.kodi.tv/addons/matrix/script.module.urllib3/script.module.urllib3-2.1.0.zip

I built a remote url hashing function for Opensubs as per the wiki:

https://trac.opensubtitles.org/projects/opensubtitles/wiki/HashSourceCodes#Python

And Kodi will throw the error "IncompleteRead(65536 bytes read, 1 more expected)" when requesting the Last64kb of a video stream url? (The code worked perfectly with the test link "https://static.opensubtitles.org/addons/avi/breakdance.avi")

I have made a patch to the file:

````
.kodi/addons/script.module.urllib3/lib/urllib3/response.py
````
And the line:

````
raise IncompleteRead(self._fp_bytes_read, self.length_remaining)  
````

However this is not a solution I am sure.

Therefore Kodi may want to use the old version of Urllib3 prior to v2 until the error is resolved?

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

urllib3 1.26.5
Will request the last64kb of the file (ie 65536 bytes) without indicating there is 1 extra byte that it is incorrectly waiting for.

## Actual Behavior

Whereas urllib3 2.1.0 throws the error when requesting the last 65536 bytes of a stream URL:
````
IncompleteRead(65536 bytes read, 1 more expected)
````

## Possible Fix

I have made a patch to the file:

````
.kodi/addons/script.module.urllib3/lib/urllib3/response.py
````
And the line:

````
raise IncompleteRead(self._fp_bytes_read, self.length_remaining)  
````

However this is not a solution I am sure.

Therefore Kodi may want to use the old version of Urllib3 prior to v2 until the error is resolved?

### To Reproduce

If you run the function:

````
hashFile_url
````
From here:

https://trac.opensubtitles.org/projects/opensubtitles/wiki/HashSourceCodes#Python

Against a video stream URL it will return:

'IOError'

When it runs:

````
                        request.install_opener(opener)
                        request.urlretrieve(url, last_64kb)
````

### Debuglog

The debuglog can be found here:

````
2024-01-11 22:05:10.683 T:4549    error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'requests.exceptions.ChunkedEncodingError'>
                                                   Error Contents: ('Connection broken: IncompleteRead(65536 bytes read, 1 more expected)', IncompleteRead(65536 bytes read, 1 more expected))
                                                   Traceback (most recent call last):
                                                     File "/home/osmc/.kodi/addons/script.module.urllib3/lib/urllib3/response.py", line 712, in _error_catcher
                                                       yield
                                                     File "/home/osmc/.kodi/addons/script.module.urllib3/lib/urllib3/response.py", line 833, in _raw_read
                                                       raise IncompleteRead(self._fp_bytes_read, self.length_remaining) ## PATCH
                                                   urllib3.exceptions.IncompleteRead: IncompleteRead(65536 bytes read, 1 more expected)

                                                   The above exception was the direct cause of the following exception:

                                                   Traceback (most recent call last):
                                                     File "/home/osmc/.kodi/addons/script.module.requests/lib/requests/models.py", line 816, in generate
                                                       yield from self.raw.stream(chunk_size, decode_content=True)
                                                     File "/home/osmc/.kodi/addons/script.module.urllib3/lib/urllib3/response.py", line 934, in stream
                                                       data = self.read(amt=amt, decode_content=decode_content)
                                                     File "/home/osmc/.kodi/addons/script.module.urllib3/lib/urllib3/response.py", line 877, in read
                                                       data = self._raw_read(amt)
                                                     File "/home/osmc/.kodi/addons/script.module.urllib3/lib/urllib3/response.py", line 833, in _raw_read
                                                       raise IncompleteRead(self._fp_bytes_read, self.length_remaining) ## PATCH
                                                     File "/usr/lib/python3.9/contextlib.py", line 135, in __exit__
                                                       self.gen.throw(type, value, traceback)
                                                     File "/home/osmc/.kodi/addons/script.module.urllib3/lib/urllib3/response.py", line 729, in _error_catcher
                                                       raise ProtocolError(f"Connection broken: {e!r}", e) from e
                                                   urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(65536 bytes read, 1 more expected)', IncompleteRead(65536 bytes read, 1 more expected))

                                                   During handling of the above exception, another exception occurred:

                                                   Traceback (most recent call last):
                                                     File "/home/osmc/.kodi/addons/script.extendedinfo/script.py", line 35, in <module>
                                                       Main()
                                                     File "/home/osmc/.kodi/addons/script.extendedinfo/script.py", line 14, in __init__
                                                       process.start_info_actions(self.infos, self.params)
                                                     File "/home/osmc/.kodi/addons/script.extendedinfo/resources/lib/process.py", line 1079, in start_info_actions
                                                       next_ep_play(show_title, show_season, show_episode, tmdb)
                                                     File "/home/osmc/.kodi/addons/script.extendedinfo/a4kwrapper_player.py", line 519, in next_ep_play
                                                       subs_list = subs.get_subtitles_list(meta_info, PTN_download)
                                                     File "/home/osmc/.kodi/addons/script.extendedinfo/a4kscrapers_wrapper/subs.py", line 289, in get_subtitles_list
                                                       meta = get_subtitles_meta(VIDEO_META, file_path)
                                                     File "/home/osmc/.kodi/addons/script.extendedinfo/a4kscrapers_wrapper/subs.py", line 214, in get_subtitles_meta
                                                       VIDEO_META2 = set_size_and_hash_url(meta=VIDEO_META, filepath=file_path)
                                                     File "/home/osmc/.kodi/addons/script.extendedinfo/a4kscrapers_wrapper/subs.py", line 167, in set_size_and_hash_url
                                                       returnedhash, filesize = hashFile_url(filepath)
                                                     File "/home/osmc/.kodi/addons/script.extendedinfo/a4kscrapers_wrapper/subs.py", line 91, in hashFile_url
                                                       for chunk in r.iter_content(chunk_size=1024):
                                                     File "/home/osmc/.kodi/addons/script.module.requests/lib/requests/models.py", line 818, in generate
                                                       raise ChunkedEncodingError(e)
                                                   requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(65536 bytes read, 1 more expected)', IncompleteRead(65536 bytes read, 1 more expected))
                                                   -->End of Python script error report<--

````

### Screenshots 
Here are some links or screenshots to help explain the problem:

N/A

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

N/A

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ x ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

Kodi V20 

But thats not relevant to this issue as its caused by the dependancy:

https://mirrors.kodi.tv/addons/matrix/script.module.urllib3/script.module.urllib3-2.1.0.zip

````
2024-01-12 10:23:15.357 T:6114     info <general>: OS Linux-4.9.269-44-osmc-armv7-with-glibc2.31 
2024-01-12 10:23:15.358 T:6114     info <general>: Python 3.9.2 
2024-01-12 10:23:15.358 T:6114     info <general>: OpenSSL 1.1.1w  11 Sep 2023 
2024-01-12 10:23:15.358 T:6114     info <general>: urllib3 2.1.0 
````

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

https://github.com/urllib3/urllib3/issues/3277

**Comment by henryjfry** [comment]
Issue updated to follow template. However the template is not really relevant as its a kodi dependency issue, but I couldn't figure out where the "script.module.urllib3" developer github was so please redirect accordingly.
