### ISSUE TITLE
[Kodi 21] Cryptodome broken on Android since 2023-12-28 nightly

### ISSUE THREAD

**Issue by macearl** [xbmc/xbmc#24550]
### Describe the bug
Here is a clear and concise description of what the problem is:

Since the 2023-12-28 nightly addons which rely on cryptodome don't work on Android (in my case on a Nvidia Shield Pro 2019, Android 9.1.1)

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

The addon should start and in case of sendtokodi play the shared link 

## Actual Behavior

An error message is shown, prompting to check the logfiles

## Possible Fix

wasn't able to debug/bisect this yet but my first guess is that 
https://github.com/xbmc/xbmc/commit/fc02e80d33a225544b6c0a3bf62a95bbc912e860#diff-76a74f2c8b91720136b4b9bbae81370b2cd9224a4b564a9518b7cf099703aadeL91

is the problematic change since this seems to be directly related to the Cryptodome so 

If I downgrade to the 2023-12-26 nightly everything works again. 

### To Reproduce

1. install the  sendtokodi addon (or probably any other addon which uses cryptodome) 
2. start the addon, in the case of sendtokodi for example by sharing a link to kodi, e.g. https://www.youtube.com/watch?v=aqz-KE-bpKQ

### Debuglog

The debuglog can be found here:
```
2024-01-20 23:13:38.761 T:8099    error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: not enough arguments for format string
                                                   Traceback (most recent call last):
                                                     File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.11/lib/python3.11/site-packages/Cryptodome/Util/_raw_api.py", line 184, in load_lib
                                                       raise OSError("Cannot load library '%s'" % name)
                                                   OSError: Cannot load library 'gmp'

                                                   During handling of the above exception, another exception occurred:

                                                   Traceback (most recent call last):
                                                     File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.11/lib/python3.11/site-packages/Cryptodome/Math/Numbers.py", line 34, in <module>
                                                       from Cryptodome.Math._IntegerGMP import IntegerGMP as Integer
                                                     File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.11/lib/python3.11/site-packages/Cryptodome/Math/_IntegerGMP.py", line 98, in <module>
                                                       lib = load_lib("gmp", gmp_defs)
                                                             ^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.11/lib/python3.11/site-packages/Cryptodome/Util/_raw_api.py", line 187, in load_lib
                                                       raise OSError("Cannot load library '%s'" % name)
                                                   OSError: Cannot load library 'gmp'

                                                   During handling of the above exception, another exception occurred:

                                                   Traceback (most recent call last):
                                                     File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.11/lib/python3.11/site-packages/Cryptodome/Util/_raw_api.py", line 289, in load_pycryptodome_raw_lib
                                                       return load_lib("lib" + name.replace(".", "_") + ".so", cdecl)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.11/lib/python3.11/site-packages/Cryptodome/Util/_raw_api.py", line 188, in load_lib
                                                       return CDLL(name)
                                                              ^^^^^^^^^^
                                                     File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.11/lib/python3.11/ctypes/__init__.py", line 376, in __init__
                                                       self._handle = _dlopen(self._name, mode)
                                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^
                                                   OSError: dlopen failed: library "libCryptodome_Math__modexp.so" not found

                                                   During handling of the above exception, another exception occurred:

                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.sendtokodi/service.py", line 249, in <module>
                                                       from lib.yt_dlp import YoutubeDL
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.sendtokodi/lib/yt_dlp/__init__.py", line 18, in <module>
                                                       from .cookies import SUPPORTED_BROWSERS, SUPPORTED_KEYRINGS
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.sendtokodi/lib/yt_dlp/cookies.py", line 21, in <module>
                                                       from .aes import (
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.sendtokodi/lib/yt_dlp/aes.py", line 5, in <module>
                                                       from .dependencies import Cryptodome
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.sendtokodi/lib/yt_dlp/dependencies/__init__.py", line 80, in <module>
                                                       from . import Cryptodome
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.sendtokodi/lib/yt_dlp/dependencies/Cryptodome.py", line 21, in <module>
                                                       from Cryptodome.PublicKey import RSA
                                                     File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.11/lib/python3.11/site-packages/Cryptodome/PublicKey/RSA.py", line 42, in <module>
                                                       from Cryptodome.Math.Numbers import Integer
                                                     File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.11/lib/python3.11/site-packages/Cryptodome/Math/Numbers.py", line 38, in <module>
                                                       from Cryptodome.Math._IntegerCustom import IntegerCustom as Integer
                                                     File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.11/lib/python3.11/site-packages/Cryptodome/Math/_IntegerCustom.py", line 53, in <module>
                                                       _raw_montgomery = load_pycryptodome_raw_lib("Cryptodome.Math._modexp", c_defs)
                                                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.11/lib/python3.11/site-packages/Cryptodome/Util/_raw_api.py", line 291, in load_pycryptodome_raw_lib
                                                       raise OSError("Cannot load '%s': %s" % ("lib" + name.replace(".", "_") + ".so"))
                                                                     ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                   TypeError: not enough arguments for format string
                                                   -->End of Python script error report<--
```

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Android TV 9.1.1 / Nvidia Shield
 - Kodi version: 21.0-BETA2 (20.90.821) / Git 20231228-c394355b63

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by fuzzard** [comment]
That commit doesnt look to be the cause.

That line only renames. If you extract a nightly apk (eg kodi-20240118-65630714-master-arm64-v8a) and the one you have highlighted as working (kodi-20231225-80653dc0-master-arm64-v8a) look in the lib/arm64-v8a/ folder, the cryptodome libs are there, and named the same.

The cryptodome libraries are currently "loading" for my test import addon, so you are probably going to have to bisect a bit to try and find out whats causing the issue.

We dont have gmp as a build requirement for pycryptodome currently, so maybe its a race condition with lib building, and some build order has changed and auto detection is finding gmp lib when pycryptodome module is built. Not sure offhand.

**Comment by macearl** [comment]
Thanks for the quick fix. 
The abi3 files were the only ones I found while diffing the contents of the two apks yesterday. I probably should have been a bit clearer in my first message and included that little detail... even though I wasn't sure if the additional `abi3` would be a problem at all. 

Just tried it again with [kodi-20240121-26900a31-PR24551-arm64-v8a.apk](https://jenkins.kodi.tv/job/android-arm64-docker/5109/artifact/kodi-20240121-26900a31-PR24551-arm64-v8a.apk) and everything seems to work again.
