### ISSUE TITLE
Android aarch64 build fails during make apk

### ISSUE THREAD

**Issue by spdfrk** [xbmc/xbmc#24612]
### Describe the bug

Dear all,

I'm trying to build Android aarch64 but it fails during "make apk".

I followed the official Android building guide on a fresh Ubuntu 22.04 server setup. Only deviation was to install openjdk-21-jdk-headless as default-jdk is to old. All is ok without errors but unable to create the apk due to an error.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

No errors during make apk

## Actual Behavior

Execution failed for task ':xbmc:dexBuilderDebug'

## Possible Fix

No idea so far!

### To Reproduce

1. Follow guide on github
2. install openjdk-21-jdk-headless
3. (after configuration) cd build, make, make apk

### Debuglog

The debuglog can be found here:
....snip
        Caused by: com.android.tools.r8.internal.xk: java.lang.NullPointerException: Cannot invoke "String.length()" because "<parameter1>" is null
                at com.android.tools.r8.internal.xk.a(R8_4.0.48_320a4fe2564c68ad8fe4492fea65872bc8f51e21c4d46e3dbac43afcc38d90de:6)
                at com.android.tools.r8.internal.vk.a(R8_4.0.48_320a4fe2564c68ad8fe4492fea65872bc8f51e21c4d46e3dbac43afcc38d90de:104)
                at com.android.tools.r8.internal.vk.a(R8_4.0.48_320a4fe2564c68ad8fe4492fea65872bc8f51e21c4d46e3dbac43afcc38d90de:100)
                at com.android.tools.r8.graph.y2.b(R8_4.0.48_320a4fe2564c68ad8fe4492fea65872bc8f51e21c4d46e3dbac43afcc38d90de:2)
                at com.android.tools.r8.dex.a.a(R8_4.0.48_320a4fe2564c68ad8fe4492fea65872bc8f51e21c4d46e3dbac43afcc38d90de:27)
                at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
                at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:69)
                at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
                at com.google.common.util.concurrent.MoreExecutors$DirectExecutorService.execute(MoreExecutors.java:321)
                at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:145)
                at com.google.common.util.concurrent.AbstractListeningExecutorService.submit(AbstractListeningExecutorService.java:66)
                at com.google.common.util.concurrent.AbstractListeningExecutorService.submit(AbstractListeningExecutorService.java:36)
                at com.android.tools.r8.dex.a.a(R8_4.0.48_320a4fe2564c68ad8fe4492fea65872bc8f51e21c4d46e3dbac43afcc38d90de:24)
                at com.android.tools.r8.dex.a.b(R8_4.0.48_320a4fe2564c68ad8fe4492fea65872bc8f51e21c4d46e3dbac43afcc38d90de:38)
                at com.android.tools.r8.dex.b.a(R8_4.0.48_320a4fe2564c68ad8fe4492fea65872bc8f51e21c4d46e3dbac43afcc38d90de:66)
                ... 49 more
        Caused by: [CIRCULAR REFERENCE: java.lang.NullPointerException: Cannot invoke "String.length()" because "<parameter1>" is null]

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':xbmc:dexBuilderDebug'.
> There were multiple failures while executing work items
   > A failure occurred while executing com.android.build.gradle.internal.dexing.DexWorkAction
      > Failed to process: /home/user/kodi/build/tools/android/packaging/xbmc/build/intermediates/javac/debug/classes
   > A failure occurred while executing com.android.build.gradle.internal.dexing.DexWorkAction
      > Failed to process: /home/user/kodi/build/tools/android/packaging/xbmc/build/intermediates/javac/debug/classes
   > A failure occurred while executing com.android.build.gradle.internal.dexing.DexWorkAction
      > Failed to process: /home/user/kodi/build/tools/android/packaging/xbmc/build/intermediates/javac/debug/classes
   > A failure occurred while executing com.android.build.gradle.internal.dexing.DexWorkAction
      > Failed to process: /home/user/kodi/build/tools/android/packaging/xbmc/build/intermediates/javac/debug/classes
   > A failure occurred while executing com.android.build.gradle.internal.dexing.DexWorkAction
      > Failed to process: /home/user/kodi/build/tools/android/packaging/xbmc/build/intermediates/javac/debug/classes

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.3/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.

BUILD FAILED in 11s
22 actionable tasks: 1 executed, 21 up-to-date
gmake[4]: *** [Makefile:98: package] Error 1
make[3]: *** [CMakeFiles/apk.dir/build.make:70: CMakeFiles/apk] Error 2
make[2]: *** [CMakeFiles/Makefile2:5840: CMakeFiles/apk.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:5847: CMakeFiles/apk.dir/rule] Error 2
make: *** [Makefile:475: apk] Error 2

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Android aarch64
 - Kodi version: Master

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by spdfrk** [comment]
Sorry I was mistaken by an earlier issue where it appeared I would need Java major version 65. 
With OpenJDK 11 the build completes successfully.
