### ISSUE TITLE
[XBOX UWP] Cannot import AES from Cryptodome.Cipher

### ISSUE THREAD

**Issue by thepasto** [xbmc/xbmc#24746]
### Describe the bug
Here is a clear and concise description of what the problem is:

Hello guys, i need some help.
I'm trying to import AES in a test addon i made, but i am not able to get it run on XBOX platform.
In any other platform, that code is running as well.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

### To Reproduce

1. Just add `from Cryptodome.Cipher import AES` in addon main
2.
3.

### Debuglog

The debuglog can be found here:

```
error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
		- NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
		Error Type: <class 'FileNotFoundError'>
		Error Contents: Could not find module 'kernel32' (or one of its dependencies). Try using the full path with constructor syntax.
		Traceback (most recent call last):
		 File "S:\Program Files\WindowsApps\XBMCFoundation.Kodi_20.3.0.70_x64__4n2hpmxwrvr6p\system\python\Lib\site-packages\Cryptodome\Util\_raw_api.py", line 84, in <module>
		   from cffi import FFI
		ModuleNotFoundError: No module named 'cffi'

		During handling of the above exception, another exception occurred:

		Traceback (most recent call last):
		 File "Q:\Users\UserMgr0\AppData\Local\Packages\XBMCFoundation.Kodi_4n2hpmxwrvr6p\LocalState\addons\plugin.video.testaddon\main.py", line 13, in <module>
		   plugin.run()
		 File "Q:\Users\UserMgr0\AppData\Local\Packages\XBMCFoundation.Kodi_4n2hpmxwrvr6p\LocalState\addons\plugin.video.testaddon\resources\lib\plugin.py", line 646, in run
		   plugin.run()
		 File "Q:\Users\UserMgr0\AppData\Local\Packages\XBMCFoundation.Kodi_4n2hpmxwrvr6p\LocalState\addons\script.module.routing\lib\routing.py", line 130, in run
		   self._dispatch(self.path)
		 File "Q:\Users\UserMgr0\AppData\Local\Packages\XBMCFoundation.Kodi_4n2hpmxwrvr6p\LocalState\addons\script.module.routing\lib\routing.py", line 141, in _dispatch
		   view_func(**kwargs)
		 File "Q:\Users\UserMgr0\AppData\Local\Packages\XBMCFoundation.Kodi_4n2hpmxwrvr6p\LocalState\addons\plugin.video.testaddon\resources\lib\plugin.py", line 67, in index
		   set_router('/')
		 File "Q:\Users\UserMgr0\AppData\Local\Packages\XBMCFoundation.Kodi_4n2hpmxwrvr6p\LocalState\addons\plugin.video.testaddon\resources\lib\plugin.py", line 429, in set_router
		   res = client.get_request(page)
		 File "<string>", line 1, in <module>
		 File "Q:\Users\UserMgr0\AppData\Local\Packages\XBMCFoundation.Kodi_4n2hpmxwrvr6p\LocalState\addons\plugin.video.testaddon\Token.py", line 21, in <module>
		   from Cryptodome.Cipher import AES
		 File "S:\Program Files\WindowsApps\XBMCFoundation.Kodi_20.3.0.70_x64__4n2hpmxwrvr6p\system\python\Lib\site-packages\Cryptodome\Cipher\__init__.py", line 27, in <module>
		   from Cryptodome.Cipher._mode_ecb import _create_ecb_cipher
		 File "S:\Program Files\WindowsApps\XBMCFoundation.Kodi_20.3.0.70_x64__4n2hpmxwrvr6p\system\python\Lib\site-packages\Cryptodome\Cipher\_mode_ecb.py", line 29, in <module>
		   from Cryptodome.Util._raw_api import (load_pycryptodome_raw_lib,
		 File "S:\Program Files\WindowsApps\XBMCFoundation.Kodi_20.3.0.70_x64__4n2hpmxwrvr6p\system\python\Lib\site-packages\Cryptodome\Util\_raw_api.py", line 165, in <module>
		   import ctypes
		 File "S:\Program Files\WindowsApps\XBMCFoundation.Kodi_20.3.0.70_x64__4n2hpmxwrvr6p\system\python\Lib\ctypes\__init__.py", line 468, in <module>
		   GetLastError = windll.kernel32.GetLastError
		 File "S:\Program Files\WindowsApps\XBMCFoundation.Kodi_20.3.0.70_x64__4n2hpmxwrvr6p\system\python\Lib\ctypes\__init__.py", line 443, in __getattr__
		   dll = self._dlltype(name)
		 File "S:\Program Files\WindowsApps\XBMCFoundation.Kodi_20.3.0.70_x64__4n2hpmxwrvr6p\system\python\Lib\ctypes\__init__.py", line 373, in __init__
		   self._handle = _dlopen(self._name, mode)
		FileNotFoundError: Could not find module 'kernel32' (or one of its dependencies). Try using the full path with constructor syntax.
		-->End of Python script error report<--

```

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

Similar issue #22539 

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [x] Windows UWP

 - Operating system version/name: XBOX X series
 - Kodi version: 20.03

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by Gujal00** [comment]
`Error Contents: Could not find module 'kernel32' (or one of its dependencies). Try using the full path with constructor syntax.`
This has always been the case on the XBOX One, not specifically related to 20.3

**Comment by thexai** [comment]
Tested and reproduced installing UWP version (.msix) on Windows 11 23H2 

And with this test/modified add-on (contains `from Cryptodome.Cipher import AES`):
[script.kodi.loguploader-1.0.5.zip](https://github.com/xbmc/xbmc/files/14800821/script.kodi.loguploader-1.0.5.zip)

**Comment by Gujal00** [comment]
Any chance of a fix on the upcoming 21.1 release?

**Comment by jopsis** [comment]
> I'm still experiencing this issue with Xbox UWP 21.1 Git:20240817-183eb85f10.

Me too

**Comment by jopsis** [comment]
> @jopsis We may need to wait for the development team to fix the issue in Kodi 22, for now I use PyAES to circumvent the issue.

Have you the “How to” to fix it?
