### ISSUE TITLE
Python packages installed into wrong folder

### ISSUE THREAD

**Issue by vpeter4** [xbmc/xbmc#25275]
### Describe the bug
Here is a clear and concise description of what the problem is:

With [PR 25211](https://github.com/xbmc/xbmc/pull/25211) kodi python packages are installed into wrong folder and kodi-send script doesn't work anymore.

```
$ kodi-send --action="TakeScreenshot"
Traceback (most recent call last):
  File "/usr/bin/kodi-send", line 27, in <module>
    from kodi.xbmcclient import *
ModuleNotFoundError: No module named 'kodi'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/kodi-send", line 30, in <module>
    from xbmcclient import *
ModuleNotFoundError: No module named 'xbmcclient'
```

Python function get_path from sysconfig returns full path like this
`/data/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/toolchain/x86_64-libreelec-linux-gnu/sysroot/usr/lib/python3.11/site-packages`
instead of short one like this using get_python_lib from distutils
`lib/python3.11/site-packages`
and then python files like xbmcclient.pyc are installed into wrong path

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Install python packages into same folder as before and having kodi-send working.

```
kodi-21.0-Omega
build.LibreELEC-Generic.x86_64-13.0-devel/build/kodi-21.0-Omega/tools/EventClients/lib/python/xbmcclient.py
build.LibreELEC-Generic.x86_64-13.0-devel/image/system/usr/lib/python3.11/site-packages/kodi/xbmcclient.pyc
build.LibreELEC-Generic.x86_64-13.0-devel/toolchain/x86_64-libreelec-linux-gnu/sysroot/usr/lib/python3.11/site-packages/kodi/xbmcclient.py
build.LibreELEC-Generic.x86_64-13.0-devel/install_pkg/kodi-21.0-Omega/usr/lib/python3.11/site-packages/kodi/xbmcclient.pyc
```

notice
`/usr/lib/python3.11/site-packages/kodi/xbmcclient.pyc`

## Actual Behavior

```
kodi-42120bb9047912b9379dadffdbdef9968062cf70
build.LibreELEC-Generic.x86_64-13.0-devel/build/kodi-42120bb9047912b9379dadffdbdef9968062cf70/tools/EventClients/lib/python/xbmcclient.py
build.LibreELEC-Generic.x86_64-13.0-devel/image/system/data/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/toolchain/x86_64-libreelec-linux-gnu/sysroot/usr/lib/python3.11/site-packages/kodi/xbmcclient.py
build.LibreELEC-Generic.x86_64-13.0-devel/toolchain/x86_64-libreelec-linux-gnu/sysroot/data/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/toolchain/x86_64-libreelec-linux-gnu/sysroot/usr/lib/python3.11/site-packages/kodi/xbmcclient.py
build.LibreELEC-Generic.x86_64-13.0-devel/install_pkg/kodi-42120bb9047912b9379dadffdbdef9968062cf70/data/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/toolchain/x86_64-libreelec-linux-gnu/sysroot/usr/lib/python3.11/site-packages/kodi/xbmcclient.py
```

notice
`/data/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/toolchain/x86_64-libreelec-linux-gnu/sysroot/usr/lib/python3.11/site-packages/kodi/xbmcclient.py`

## Possible Fix

Some prefix needs to be stripped
`execute_process(COMMAND ${PYTHON_EXECUTABLE} -c "from sysconfig import get_path; print(get_path('platlib', scheme='posix_prefix', vars={'platbase': '${CMAKE_INSTALL_PREFIX}'}))"
`

Two references:
https://github.com/rdkit/rdkit/blob/master/CMakeLists.txt#L352-L355
https://github.com/rpm-software-management/libdnf/commit/f1cffbfb9f338da827e233c2d8ac3a25a6a59a69

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP
 - [x] LibreELEC
 
 - Operating system version/name: LibreELEC 13
 - Kodi version: kodi-42120bb9047912b9379dadffdbdef9968062cf70 

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by hbiyik** [comment]
My understanding is that those python libraries should be installed to the user library folder of the python interpreter used in the compilation.

So using CMAKE PREFIX as platbase may not always give the correct answer, because python interpreters base and kodi's instaĺl prefix might be different.

Reference:
https://wiki.python.org/moin/Distutils/DiscussionOverview/FilePrefixes

I am more thinking about why your python is pointing to a staging buid dir as platbase, could it be something realted python compilation process of LE?

**Comment by vpeter4** [comment]
> could it be something realted python compilation process of LE?

It could be. But I don't know what to look for. Only that behaviour changed.

**Comment by jernejsk** [comment]
> My understanding is that those python libraries should be installed to the user library folder of the python interpreter used in the compilation.

That is not true when cross-compiling. Can you test @vpeter4 suggested solution for your case?

**Comment by vpeter4** [comment]
No fix but instead backport and affect Omega too. Not nice.

**Comment by neo1973** [comment]
I'll take care of this.
