### ISSUE TITLE
[Windows] test executable crashes and fails to run

### ISSUE THREAD

**Issue by fuzzard** [xbmc/xbmc#25396]
### Describe the bug
Here is a clear and concise description of what the problem is:
Test executable falls to run for windows.
Git bisect found the following PR to cause

```
 c:\Users\brent\source\repos\xbmc>git bisect bad
 a0aa7baea73198e63463e7f931969c8e849a0ffa is the first bad commit
 commit a0aa7baea73198e63463e7f931969c8e849a0ffa
 Author: Arne Morten Kvarving <spiff@kodi.tv>
 Date:   Sun Feb 11 00:44:13 2024 +0100
 
     add video/VideoFileItemClassify.cpp
 
     start by moving CFileItem::IsVideo
```

However I believe newer test cases that have been introduced also are possibly causing crashes of the test executable on windows.

Jenkins was not correctly detecting a failure in the even of no output (ie a crash) from the test executable.

The following PR was made to correctly have Jenkins report such a failure case. https://github.com/xbmc/xbmc/pull/25390

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Tests to run on windows

## Actual Behavior

Test executable has no output and crashes.

Confirmed test TestVideoFileItemClassify was initial test that started crash, but I believe other tests using unix paths may also be causing crashes, as disabling the Fileitemclassify test source file still has the test executable still fail on tip of master currently.
I used a checkout of a0aa7baea73198e63463e7f931969c8e849a0ffa specifically to locate the specific test mentioned in this issue causing the crash

## Possible Fix

Definitely path related. https://github.com/xbmc/xbmc/blob/501ec1fae0fb86760548018f02702a9caf8ba997/xbmc/video/test/TestVideoFileItemClassify.cpp#L113
```
 const auto video_tests = std::array{
 //    VideoClassifyTest{"/home/user/video.avi", true, "video/avi"},
 //    VideoClassifyTest{"/home/user/video.avi", true, "", 1},
 //    VideoClassifyTest{"/home/user/video.avi", false, "", 2},
 //    VideoClassifyTest{"/home/user/video.avi", false, "", 3},
 //    VideoClassifyTest{"/home/user/video.avi", false, "", 4},
     VideoClassifyTest{"pvr://recordings/tv/1", true},
     VideoClassifyTest{"pvr://123", false},
 //    VideoClassifyTest{"dvd://VIDEO_TS/video_ts.ifo", true},
     VideoClassifyTest{"dvd://1", true},
 //    VideoClassifyTest{"/home/user/video.not", true, "application/ogg"},
 //    VideoClassifyTest{"/home/user/video.not", true, "application/mp4"},
 //    VideoClassifyTest{"/home/user/video.not", true, "application/mxf"},
 };
```
 The only ones that dont cause it to crash are the uncommented ones.

Confirmed Mimetype is not causing a failure, as well as tag and res.

### To Reproduce
1. Build kodi-test on windows. 
2. Execute kodi-test
3.no output

### Debuglog
The debuglog can be found here:
Kodi-test has no debug log. Crash is specifically caused by test case

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 22 master 501ec1fae0fb86760548018f02702a9caf8ba997

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by fuzzard** [comment]
Stack trace for the failure
```
 	kodi-test.exe!std::_Tree<std::_Tmap_traits<std::string,std::string,std::less<std::string>,std::allocator<std::pair<std::string const ,std::string>>,0>>::_Find_lower_bound<std::string>(const std::string & _Keyval) Line 1597	C++
 	kodi-test.exe!std::_Tree<std::_Tmap_traits<std::string,std::string,std::less<std::string>,std::allocator<std::pair<std::string const ,std::string>>,0>>::_Find<std::string>(const std::string & _Keyval) Line 1354	C++
 	kodi-test.exe!std::_Tree<std::_Tmap_traits<std::string,std::string,std::less<std::string>,std::allocator<std::pair<std::string const ,std::string>>,0>>::find(const std::string & _Keyval) Line 1367	C++
>	kodi-test.exe!CMime::GetMimeType(const std::string & extension) Line 528	C++
 	kodi-test.exe!CMime::GetMimeType(const CFileItem & item) Line 543	C++
 	kodi-test.exe!CFileItem::FillInMimeType(bool lookup) Line 1584	C++
 	kodi-test.exe!CFileItem::CFileItem(const std::string & strPath, bool bIsFolder) Line 392	C++
 	kodi-test.exe!VideoClassifyTest::VideoClassifyTest(const std::string & path, bool res, const std::string & mime, int tag_type) Line 30	C++
 	kodi-test.exe!`dynamic initializer for 'video_tests''() Line 66	C++ 	kodi-test.exe!std::_Tree<std::_Tmap_traits<std::string,std::string,std::less<std::string>,std::allocator<std::pair<std::string const ,std::string>>,0>>::_Find_lower_bound<std::string>(const std::string & _Keyval) Line 1597	C++
 	kodi-test.exe!std::_Tree<std::_Tmap_traits<std::string,std::string,std::less<std::string>,std::allocator<std::pair<std::string const ,std::string>>,0>>::_Find<std::string>(const std::string & _Keyval) Line 1354	C++
 	kodi-test.exe!std::_Tree<std::_Tmap_traits<std::string,std::string,std::less<std::string>,std::allocator<std::pair<std::string const ,std::string>>,0>>::find(const std::string & _Keyval) Line 1367	C++
>	kodi-test.exe!CMime::GetMimeType(const std::string & extension) Line 528	C++
 	kodi-test.exe!CMime::GetMimeType(const CFileItem & item) Line 543	C++
 	kodi-test.exe!CFileItem::FillInMimeType(bool lookup) Line 1584	C++
 	kodi-test.exe!CFileItem::CFileItem(const std::string & strPath, bool bIsFolder) Line 392	C++
 	kodi-test.exe!VideoClassifyTest::VideoClassifyTest(const std::string & path, bool res, const std::string & mime, int tag_type) Line 30	C++
 	kodi-test.exe!`dynamic initializer for 'video_tests''() Line 66	C++
```
m_mimetype is empty.

Error with the test and initialising mimetype?

Following patch is a possible solution. Not sure whether its the appropriate solution or not.

```
diff --git a/xbmc/utils/Mime.cpp b/xbmc/utils/Mime.cpp
index 2a3acd5c97..485100faea 100644
--- a/xbmc/utils/Mime.cpp
+++ b/xbmc/utils/Mime.cpp
@@ -525,6 +525,9 @@ std::string CMime::GetMimeType(const std::string &extension)
     ext = extension.substr(posNotPoint);
   transform(ext.begin(), ext.end(), ext.begin(), ::tolower);

+  if (m_mimetypes.size() == 0)
+    return "";
+
   std::map<std::string, std::string>::const_iterator it = m_mimetypes.find(ext);
   if (it != m_mimetypes.end())
     return it->second;
```

**Comment by thexai** [comment]
Just now I came here to post the same thing:

![kodi-test](https://github.com/xbmc/xbmc/assets/58434170/63d74a09-f1d8-4bd8-bb6d-420b3a4a7fb6)

**Comment by thexai** [comment]
It may not solve the root cause but that check will not hurt and at least prevents the crash.

**Comment by fuzzard** [comment]
Speaking to @notspiff , i thought m_mimetypes would be full of data, but it isnt. He said maybe its some stomped stack, or some odd CMime instantiation. I'm hoping one of you windows guys can work out the root cause

**Comment by thexai** [comment]
But the problem is that the longer the test is disabled for Windows, the more things would break as unchecked commits are merged... even after fixing this, more things fail.

![tests](https://github.com/xbmc/xbmc/assets/58434170/10fcfe13-62a9-452e-a8f6-b276172a4d1c)

**Comment by fuzzard** [comment]
They haven't failed for me on a win64 master. There's a fix to the playlistwpl failure already prd, and that's the only other test failure I've had

**Comment by thexai** [comment]
Correct: it seems that this does not fail on Release mode

**Comment by neo1973** [comment]
The root cause is the initialization order of global objects.

https://github.com/xbmc/xbmc/blob/5810c325422055dc29219c7ec4df5551cf592c57/xbmc/video/test/TestVideoFileItemClassify.cpp#L113-L126

These tests are global static and so is the `std::map` containing the mime types. The initialization order is undefined and here the tests are instantiated first and so `CFileItem::FillInMimeType()` doesn't work. ASAN also flags this when using the right flags:

<details>
<summary>ASAN output</summary>

```
==26868==ERROR: AddressSanitizer: initialization-order-fiasco on address 0x6504a6c4ded0 at pc 0x650498440da0 bp 0x7ffe01da1370 sp 0x7ffe01da1368
READ of size 8 at 0x6504a6c4ded0 thread T0
    #0 0x650498440d9f in std::_Rb_tree<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>>, std::_Select1st<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>>>, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>>, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>>>>::_M_begin() const /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/14.1.1/../../../../include/c++/14.1.1/bits/stl_tree.h:743:29
    #1 0x650498440579 in std::_Rb_tree<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>>, std::_Select1st<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>>>, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>>, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>>>>::find(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const&) const /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/14.1.1/../../../../include/c++/14.1.1/bits/stl_tree.h:2541:43
    #2 0x65049842a582 in std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>>, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>>>>::find(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const&) const /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/14.1.1/../../../../include/c++/14.1.1/bits/stl_map.h:1244:21
    #3 0x65049aa1cd10 in CMime::GetMimeType(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const&) xbmc/utils/Mime.cpp:528:71
    #4 0x65049aa1de99 in CMime::GetMimeType[abi:cxx11](CFileItem const&) xbmc/utils/Mime.cpp:543:10
    #5 0x65049ca3e6a4 in CFileItem::FillInMimeType(bool) xbmc/FileItem.cpp:1408:20
    #6 0x65049ca5da08 in CFileItem::CFileItem(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const&, bool) xbmc/FileItem.cpp:391:3
    #7 0x6504976443e6 in StubDefinition::StubDefinition(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const&, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const&, bool) xbmc/video/test/TestVideoFileItemClassify.cpp:35:7
    #8 0x65049763b298 in __cxx_global_var_init.7 xbmc/video/test/TestVideoFileItemClassify.cpp:60:5
    #9 0x650497643378 in _GLOBAL__sub_I_TestVideoFileItemClassify.cpp xbmc/video/test/TestVideoFileItemClassify.cpp
    #10 0x7b6177a39dc3 in __libc_start_main (/usr/lib/libc.so.6+0x25dc3) (BuildId: 32a656aa5562eece8c59a585f5eacd6cf5e2307b)
    #11 0x650497468524 in _start (/home/mark/Coding/Repos/kodi-git/build_clang_debug_sanitizer/kodi-test+0x9a49524) (BuildId: c47edc4b59155ad9d101bdae497968c6d1eef052)

0x6504a6c4ded0 is located 16 bytes inside of global variable 'CMime::m_mimetypes[abi:cxx11]' defined in 'xbmc/utils/Mime.cpp' (0x6504a6c4dec0) of size 48
  registered at:
    #0 0x650497483339 in __asan_register_globals.part.0 (/home/mark/Coding/Repos/kodi-git/build_clang_debug_sanitizer/kodi-test+0x9a64339) (BuildId: c47edc4b59155ad9d101bdae497968c6d1eef052)
    #1 0x6504974839de in __asan_register_elf_globals (/home/mark/Coding/Repos/kodi-git/build_clang_debug_sanitizer/kodi-test+0x9a649de) (BuildId: c47edc4b59155ad9d101bdae497968c6d1eef052)
    #2 0x7b6177a39dc3 in __libc_start_main (/usr/lib/libc.so.6+0x25dc3) (BuildId: 32a656aa5562eece8c59a585f5eacd6cf5e2307b)
    #3 0x650497468524 in _start (/home/mark/Coding/Repos/kodi-git/build_clang_debug_sanitizer/kodi-test+0x9a49524) (BuildId: c47edc4b59155ad9d101bdae497968c6d1eef052)

SUMMARY: AddressSanitizer: initialization-order-fiasco /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/14.1.1/../../../../include/c++/14.1.1/bits/stl_tree.h:743:29 in std::_Rb_tree<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>>, std::_Select1st<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>>>, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>>, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>>>>::_M_begin() const
Shadow bytes around the buggy address:
  0x6504a6c4dc00: f6 f6 f6 f6 f6 f6 f6 f6 f6 f6 f6 f6 f6 f6 f6 f6
  0x6504a6c4dc80: 00 00 00 00 f6 f6 f6 f6 f6 f6 f6 f6 f6 f6 f6 f6
  0x6504a6c4dd00: f6 f6 f6 f6 f6 f6 f6 f6 f6 f6 f6 f6 00 00 00 00
  0x6504a6c4dd80: f6 f6 f6 f6 f6 f6 f6 f6 f6 f6 f6 f6 f6 f6 f6 f6
  0x6504a6c4de00: f6 f6 f6 f6 00 00 00 00 f6 f6 f6 f6 f6 f6 f6 f6
=>0x6504a6c4de80: f6 f6 f6 f6 f6 f6 f6 f6 f6 f6[f6]f6 f6 f6 f6 f6
  0x6504a6c4df00: f6 f6 f6 f6 00 00 00 00 f6 f6 f6 f6 f6 f6 f6 f6
  0x6504a6c4df80: f6 f6 f6 f6 f6 f6 f6 f6 f6 f6 f6 f6 00 00 00 00
  0x6504a6c4e000: f6 f6 f6 f6 00 00 00 00 00 00 00 00 00 00 00 00
  0x6504a6c4e080: 00 00 00 00 00 00 f9 f9 f9 f9 f9 f9 00 f9 f9 f9
  0x6504a6c4e100: 00 00 00 00 f6 f6 f6 f6 f6 f6 f6 f6 f6 f6 f6 f6
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==26868==ABORTING
```
</details>

A [Meyer’s Singleton](https://laristra.github.io/flecsi/src/developer-guide/patterns/meyers_singleton.html) can be used to resolve that.
