### ISSUE TITLE
[BUG] Kodi crashes when launched in kids profile on Google TV

### ISSUE THREAD

**Issue by laceesz** [xbmc/xbmc#25397]
### Describe the bug
The Google Chromecast TV, which has the latest software, has Google 21 Omega installed. Kodi works fine on the normal profile, but it continuously crashes after startup on the Child profile. I read about this issue on the Kodi forum, but I realized that even if I install any log addon, I won't be able to extract the log files from Kodi under the child profile.

https://forum.kodi.tv/showthread.php?tid=374374

## Expected Behavior
Continuous crashing after startup under Google TV child profile.

## Actual Behavior
Continuous crashing after startup under Google TV child profile.

## Possible Fix
It should somehow work together with the Google child profile for proper functioning.

### To Reproduce
We install Kodi 21 Omega on a freshly installed Google Chromecast TV. After starting it, we enable the use of Kodi in the Google child profile. We launch Kodi under the child profile. It will ask for permission to access the microphone and data, and we grant these permissions. Then it completely crashes. After restarting, it no longer asks for permissions in the child profile, but Kodi crashes immediately after launching.

### Debuglog
Unfortunately, it is not possible to extract any debug log files under the Google TV child profile.

### Screenshots 
There is no point in taking screenshots because Kodi doesn't do anything; it just crashes.

### Your Environment
Used Operating system:
 - [ x] Android TV 12

 - Operating system version/name:
 - Kodi version: 21 Omega

**Comment by sarbes** [comment]
To clarify, you can get a crash log via adb.

**Comment by sarbes** [comment]
No response.

**Comment by Silencer80** [comment]
Hello everyone, 

We have the same problem with a new Xiaomi A55 Pro 2025. I have set up the device with my parent account and added the profile of one of my children so that it is monitored via Family-Link. 

I have also set the usage time and parental control settings, for example. I have allowed the child to use the Kodi app. 
Kodi starts, then starts the first-start process, but then cannot display the UI and is terminated at this point. 

Everything works fine in my parent account. 

I have searched for many settings to not restrict Kodi in any way. But I have not been able to find anything useful. 

It would be great if Kodi could work in the child profile as we use it for live TV (VDR/MLD) in the house. 

Best regards!
-Boris

**Comment by joseluismarti** [comment]
Hi, I've found the cause, now we need to find a solution:

When Kodi starts for the first time it asks to enable a special permission "Allow access to manage all files".

When you start with the **normal profile** there is no problem, as there is a system activity to handle this request. In contrast, with the **Kids profile** (limited), the system (Google TV) does not provide an activity to manage system permissions. The permission is denied and the app exits.

This is the error message in the log:
```
D Kodi    : Exception asking for permissions: No Activity found to handle Intent { act=android.settings.MANAGE_APP_ALL_FILES_ACCESS_PERMISSION dat=package: }
```

**Comment by graffixnyc** [comment]
> Hi, I've found the cause, now we need to find a solution:
> 
> 
> 
> When Kodi starts for the first time it asks to enable a special permission "Allow access to manage all files".
> 
> 
> 
> When you start with the **normal profile** there is no problem, as there is a system activity to handle this request. In contrast, with the **Kids profile** (limited), the system (Google TV) does not provide an activity to manage system permissions. The permission is denied and the app exits.
> 
> 
> 
> This is the error message in the log:
> 
> ```
> 
> D Kodi    : Exception asking for permissions: No Activity found to handle Intent { act=android.settings.MANAGE_APP_ALL_FILES_ACCESS_PERMISSION dat=package: }
> 
> ```
> 
> 

I have the same issue with the kids profile. This seems to actually be an issue with Google TV and not Kodi. It doesn't seem like Google allows kids profiles to enable the special permissions an app can have (like storage permissions or mic permissions). I see no way this can be done even through the parent profile. It would be better to contact Google about this issue.

**Comment by stixpunk** [comment]
In kids profile, you can only allow already installed apps. You can't install new or change permissions. Based on this, I think the app in the kids profile have same permissions as granted on parent profile. So maybe, you can detect the app running under kids profile and don't ask for permission (which can't be opened and cause crash)

**Comment by graffixnyc** [comment]
> In kids profile, you can only allow already installed apps. You can't install new or change permissions. Based on this, I think the app in the kids profile have same permissions as granted on parent profile. So maybe, you can detect the app running under kids profile and don't ask for permission (which can't be opened and cause crash)

I actually found the way to enable the permission through the Google Parental controls. However, even enabling it, when the app is launched it still asks for permissions then a pop up says "permission denied" and the app closes.

Image showing that Kodi should have permissions to storage in the Google Parental controls for my kids account. 

![Image](https://github.com/user-attachments/assets/a8a074af-8d94-4f98-853f-26d89fc216ea)


When launching kodi on the child account that I already gave the permissions to it says it needs permissions:

![Image](https://github.com/user-attachments/assets/b9b38846-b15a-4895-8b7d-ac77d6f53033)

When you click "Continue" another dialog pops up saying"permission denied" and the app just closes. 

![Image](https://github.com/user-attachments/assets/6bfa670f-1105-44d2-b447-c3cf234322e6)

So even though, I gave Kodi storage permissions through the Google Parental controls, it's not actually being granted and Kodi is still trying to ask for them. Kodi is working fine on the device when I switch to my adult profile. Granting the permissions on a parent account does not grant the same permissions on the child account.

**Comment by Seirix** [comment]
Please, reopen this, I have the same problem. The problem starts after upgrading to Google TV with Android 12, before this upgrade it was fine (Android <= 10).

**Comment by Septic1974** [comment]
Same problem, I wanted to install it for my son today, what a shame. Is there a solution yet?

**Comment by MhmdAlshater** [comment]
after investigating it with the help of AI
This is NOT a permissions issue at all. The crash is a Kodi bug — when Kodi starts, it calls getLauncherName() which queries the system for launcher info. On the Kids profile, the launcher returns a null activityInfo (because the Kids profile uses a restricted launcher), and Kodi doesn't handle that null case — it just crashes.

It needs to be reported/fixed in Kodi's source code at Main.java line 348

FATAL EXCEPTION: main
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.xbmc.kodi/org.xbmc.kodi.Main}
java.lang.NullPointerException: Attempt to read from field 
android.content.pm.ActivityInfo android.content.pm.ResolveInfo.activityInfo 
on a null object reference
at org.xbmc.kodi.Main.getLauncherName(Main.java:348)
at org.xbmc.kodi.Main.onCreate(Main.java:143)

**Comment by ifelipetv** [comment]
Same problem.
Tested on 2 TV.... Google TV 14. Kodi 21.2
Sony Bravia 65XR8A
Xiaomi A55 Pro

While starting Kodi on kid profile, it asks for microphone permission... no matter whatever you answer (When it is in use, Only this time or never)... It alway exits showing a pop up... Permission Denied!!! Exiting.....

**Comment by Zlika** [comment]
Same very annoying problem. Why is this big closed?

**Comment by garbear** [comment]
A debug log, and ideally a crash report, is required. Will reopen if this is provided.
