### ISSUE TITLE
Omega spams pipewire 1.2.4 logs with 2x10 "spa.audioadapter: 0x55679102b8: can't send command 10: Operation not supported" per second

### ISSUE THREAD

**Issue by sebastianwagner** [xbmc/xbmc#26122]
### Describe the bug
Here is a clear and concise description of what the problem is:

**AudioEngine calls pw_stream_trigger_process in an incompatible way**

When using Kodi21 below RaspberryPi-OS to play Audio from GUI sounds or DVB-T2 it keeps spamming the pipewire processes logs with messages like:
`pipewire[767] spa.audioadapter: 0x55679102b8: can't send command 10: Operation not supported`
The log entry seems to occur 20 times per second.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Kodi uses Pipewire in a way that doesn't lead to log spam.

## Actual Behavior

while audio just seems to play just fine it looks like

https://github.com/xbmc/xbmc/blob/Omega/xbmc/cores/AudioEngine/Sinks/pipewire/PipewireStream.cpp#L78 seems to call
the method `pw_stream_trigger_process`
from https://gitlab.freedesktop.org/pipewire/pipewire/-/blob/1.2.4/src/pipewire/stream.c#L2537

https://gitlab.freedesktop.org/pipewire/pipewire/-/blob/1.2.4/spa/plugins/audioconvert/audioadapter.c#L987 shows that the invalid [command 10](https://gitlab.freedesktop.org/pipewire/pipewire/-/blob/8f7acb717cda83f78fc128112e30d9b68337b2bd/spa/include/spa/node/type-info.h#L47) maybe unsupported by either the triggerer device would cause the same log message to be produced.

## Possible Fix

Pipewire seems to have two modes of using streams, (self)"driving" or by being triggered.

Kodi should use this method (existing since pw 0.3.4 and thus [allowed](https://github.com/xbmc/xbmc/blob/Omega/CMakeLists.txt#L243) by kodi) `pw_stream_is_driving` to check weather the stream is "driving" and should be triggered explicitly.
https://gitlab.freedesktop.org/pipewire/pipewire/-/blob/1.2.4/src/pipewire/stream.h#L566

It could still be that this is just a bug in pw, since I could have messed up my understanding of driving and triggered pw usage.

### To Reproduce

1. install kodi21 on a recent raspberryPi OS with pipewire 1.2.4
2. play audio e.g. by navigating menues or watching a video
3. watch `journalctl -b -0 -f` for some seconds

### Debuglog

The debuglog can be found here:
debug log https://paste.kodi.tv/ciqaveyuca.kodi
journalctl pw debug log https://paste.kodi.tv/feniwijade created with `PIPEWIRE_DEBUG=E,spa.audioadapter:D`

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Screenshots
Here are some links or screenshots to help explain the problem:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
/etc/rpi-issue 
Raspberry Pi reference 2024-11-19
Generated using pi-gen, https://github.com/RPi-Distro/pi-gen, 891df1e21ed2b6099a2e6a13e26c91dea44b34d4, stage4
/etc/debian_version
12.8
 - Kodi version:
   Kodi Media Center 21.1 (21.1.0) Git:20241025-f41df4d7da / package 3:21.1-5~bookworm

- pipewire 1.2.4-1~bpo12+1+rpt1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by dankamongmen** [comment]
i also see this behavior, on a full-fledged amd64 workstation. pipewire 1.2.7 on debian. kodi 21.1+dfsg-5+b1.

**Comment by fritsch** [comment]
Sure - upstream issue, see the documentation:  https://docs.pipewire.org/group__pw__stream.html#gab93fa91d8ea80e562bb5e8f6b5bafe21 and file a bug upstream. Citation:

Streams that are **not** drivers according to [pw_stream_is_driving()](https://docs.pipewire.org/group__pw__stream.html#ga3ddd332c45aa95250d3d1d26cf01452a) can also call this method. The result is that a RequestProcess event is sent to the driver. If the graph is lazy scheduling according to [pw_stream_is_lazy()](https://docs.pipewire.org/group__pw__stream.html#gac987fb3ab601efd721dbd912e21b9136), this might result in a graph cycle by the driver. If the graph is not lazy scheduling **and the stream is not a driver, this method will have no effect.**

**Comment by sebastianwagner** [comment]
Don't we actually set the flag `PW_STREAM_FLAG_DRIVER` right here?
https://github.com/xbmc/xbmc/blob/Omega/xbmc/cores/AudioEngine/Sinks/pipewire/AESinkPipewire.cpp#L463
https://gitlab.freedesktop.org/pipewire/pipewire/-/blob/1.2.4/src/pipewire/stream.h#L566 states that in this case we should explicitly call `pw_stream_trigger_process` as we do.
But according to PW logs we can determine that this only leads to errors getting logged.
Since audio gets played despite those messages it looks like we are missing something :)
Also the description of stephans MR promises that using the check, both still plays audio AND silences the logs thus indicating the flag wasn't set for the stream after all.

I for my part were able to at least [silence the logs](https://docs.pipewire.org/page_daemon.html#:~:text=Logging) with
`.config/systemd/user/pipewire.service.d/debug.conf`:
```INI
[Service]
Environment="PIPEWIRE_DEBUG=W,pw.*:I,spa.audioadapter:X"
```

**Comment by fritsch** [comment]
Yes - that's the case - you understand why I am hessitant to just merge it ... as we do totally fine according to documentation and even for setting the driver flag, right?

**Comment by tomachinz** [comment]
I'm also seeing this `spa.audioadapter` at high rates in my journal when Kodi is running. I'm on Parch Linux, Kodi can play audio but spams logs, and I recently installed pulseaudio-dlna (all I can think of). I will try updating kodi. 

```
Jan 13 20:57:37 putin systemd[1499]: pulseaudio-dlna.service: Scheduled restart job, restart counter is at 90.
Jan 13 20:57:37 putin systemd[1499]: Started PulseAudio/PipeWire DLNA Service.
Jan 13 20:57:38 putin pa-dlna[5664]: Traceback (most recent call last):
Jan 13 20:57:38 putin pa-dlna[5664]:   File "/usr/bin/pa-dlna", line 5, in <module>
Jan 13 20:57:38 putin pa-dlna[5664]:     from pa_dlna.pa_dlna import main
Jan 13 20:57:38 putin pa-dlna[5664]:   File "/usr/lib/python3.13/site-packages/pa_dlna/pa_dlna.py", line 14, in <module>
Jan 13 20:57:38 putin pa-dlna[5664]:     from .init import padlna_main, UPnPApplication, ControlPointAbortError
Jan 13 20:57:38 putin pa-dlna[5664]:   File "/usr/lib/python3.13/site-packages/pa_dlna/init.py", line 26, in <module>
Jan 13 20:57:38 putin pa-dlna[5664]:     from .pulseaudio import APPS_TITLE, APPS_HEADER
Jan 13 20:57:38 putin pa-dlna[5664]:   File "/usr/lib/python3.13/site-packages/pa_dlna/pulseaudio.py", line 7, in <module>
Jan 13 20:57:38 putin pa-dlna[5664]:     from libpulse.libpulse import (LibPulse, PA_SUBSCRIPTION_MASK_SINK_INPUT,
Jan 13 20:57:38 putin pa-dlna[5664]:                                    LibPulseStateError)
Jan 13 20:57:38 putin pa-dlna[5664]: ModuleNotFoundError: No module named 'libpulse'
Jan 13 20:57:38 putin systemd[1499]: pulseaudio-dlna.service: Main process exited, code=exited, status=1/FAILURE
Jan 13 20:57:38 putin systemd[1499]: pulseaudio-dlna.service: Failed with result 'exit-code'.
Jan 13 20:57:43 putin systemd[1499]: pulseaudio-dlna.service: Scheduled restart job, restart counter is at 91.
Jan 13 20:57:43 putin systemd[1499]: Started PulseAudio/PipeWire DLNA Service.
```

I might also try uninstalling pulseaudio_dlna.

**Comment by mooninite** [comment]
@fritsch could you take a look at the PR again? I asked the creator of pipewire to look at it and he left his comment on the PR. Thanks!
