### ISSUE TITLE
Changing language in Isengard causes a crash

### ISSUE THREAD

**Issue by samnazarko** [xbmc/xbmc#7670]
Selecting another language in Isengard causes a SEGFAULT if it has to be installed. I can replicate this on a Raspberry Pi as well as on my laptop.

```
root@sam-laptop:~/Code/Git/xbmc-isengard# gdb kodi.bin

Program received signal SIGSEGV, Segmentation fault.
CGUIWindow::Close_Internal (this=this@entry=0x0, forceClose=forceClose@entry=false, nextWindowID=nextWindowID@entry=0, 
    enableSound=<optimised out>) at GUIWindow.cpp:375
375	  if (!m_active)
(gdb) bt
#0  CGUIWindow::Close_Internal (this=this@entry=0x0, forceClose=forceClose@entry=false, nextWindowID=nextWindowID@entry=0, 
    enableSound=<optimised out>) at GUIWindow.cpp:375
#1  0x00000000008b16ec in CGUIWindow::Close (this=0x0, forceClose=forceClose@entry=false, nextWindowID=nextWindowID@entry=0, 
    enableSound=enableSound@entry=true, bWait=bWait@entry=true) at GUIWindow.cpp:407
#2  0x00000000010a711c in CProgressJob::DoModal (this=this@entry=0x42ef470) at ProgressJob.cpp:86
#3  0x0000000000a324c4 in CAddonInstaller::DoInstall (this=this@entry=0x25547c0 <CAddonInstaller::Get()::addonInstaller>, addon=
    std::shared_ptr (count 2, weak 1) 0x42ab160, hash="7a32cee06873921b8515536585aa33f1", update=<optimised out>, referer="", 
    background=background@entry=false, modal=true) at AddonInstaller.cpp:235
#4  0x0000000000a3298d in CAddonInstaller::Install (this=this@entry=0x25547c0 <CAddonInstaller::Get()::addonInstaller>, 
    addonID="resource.language.en_au", force=force@entry=true, referer="", background=background@entry=false, modal=modal@entry=true)
    at AddonInstaller.cpp:212
#5  0x0000000000a32b3d in CAddonInstaller::InstallModal (this=0x25547c0 <CAddonInstaller::Get()::addonInstaller>, 
    addonID="resource.language.en_au", addon=std::shared_ptr (count 1, weak 1) 0x3f0c690, 
    promptForInstall=promptForInstall@entry=false) at AddonInstaller.cpp:188
#6  0x00000000009e18c5 in CGUIWindowAddonBrowser::SelectAddonID (types=std::vector of length 1, capacity 1 = {...}, 
    addonIDs=std::vector of length 0, capacity 1, showNone=<optimised out>, showNone@entry=false, 
    showDetails=showDetails@entry=false, multipleSelection=multipleSelection@entry=false, showInstalled=showInstalled@entry=true, 
    showInstallable=true, showMore=<optimised out>) at GUIWindowAddonBrowser.cpp:630
#7  0x00000000009e244a in CGUIWindowAddonBrowser::SelectAddonID (types=std::vector of length 1, capacity 1 = {...}, 
    addonID="resource.language.en_gb", showNone=showNone@entry=false, showDetails=showDetails@entry=false, 
    showInstalled=showInstalled@entry=true, showInstallable=showInstallable@entry=true, showMore=false)
    at GUIWindowAddonBrowser.cpp:444
#8  0x00000000009e2633 in CGUIWindowAddonBrowser::SelectAddonID (type=ADDON::ADDON_RESOURCE_LANGUAGE, 
    addonID="resource.language.en_gb", showNone=<optimised out>, showDetails=showDetails@entry=false, 
    showInstalled=showInstalled@entry=true, showInstallable=showInstallable@entry=true, showMore=false)
    at GUIWindowAddonBrowser.cpp:429
#9  0x0000000000df1338 in CGUIControlButtonSetting::OnClick (this=0x33e5fa0) at GUIControlSettings.cpp:542
#10 0x0000000000dc13fa in CGUIDialogSettingsBase::OnClick (this=0x34bd2c0, 
    pSettingControl=std::shared_ptr (count 3, weak 0) 0x33e5fa0) at GUIDialogSettingsBase.cpp:800
#11 0x0000000000dc5a32 in CGUIDialogSettingsBase::OnMessage (this=this@entry=0x34bd2c0, message=...) at GUIDialogSettingsBase.cpp:208
#12 0x0000000000df1f13 in CGUIWindowSettingsCategory::OnMessage (this=0x34bd2c0, message=...) at GUIWindowSettingsCategory.cpp:125
#13 0x0000000000945aca in CGUIButtonControl::OnClick (this=0x47b0620) at GUIButtonControl.cpp:318
#14 0x000000000094473d in CGUIButtonControl::OnAction (this=<optimised out>, action=...) at GUIButtonControl.cpp:150
#15 0x00000000008b182e in CGUIWindow::OnAction (this=0x34bd2c0, action=...) at GUIWindow.cpp:418
#16 0x00000000008ecdeb in CGUIDialog::OnAction (this=<optimised out>, action=...) at GUIDialog.cpp:77
#17 0x0000000000dc60fd in CGUIDialogSettingsBase::OnAction (this=<optimised out>, action=...) at GUIDialogSettingsBase.cpp:276
#18 0x0000000000df20b5 in CGUIWindowSettingsCategory::OnAction (this=0x34bd2c0, action=...) at GUIWindowSettingsCategory.cpp:172
#19 0x00000000008b594d in CGUIWindowManager::OnAction (this=0x2c41f00, action=...) at GUIWindowManager.cpp:875
#20 0x0000000000e6d7f7 in CApplication::OnAction (this=0x2c3cf40, action=...) at Application.cpp:2141
#21 0x0000000000be814d in CInputManager::OnKey (this=this@entry=0x25595c0 <CInputManager::Get()::inputManager>, key=...)
```

This fixes it temporarily:

```
--- a/xbmc/guilib/GUIWindow.cpp
+++ b/xbmc/guilib/GUIWindow.cpp
@@ -372,8 +372,8 @@ void CGUIWindow::Close_Internal(bool forceClose /*= false*/, int nextWindowID /*
 {
   CSingleLock lock(g_graphicsContext);
 
-  if (!m_active)
-    return;
+  //if (!m_active)
+  //  return;
```

So I suspect m_active is not initialised, although it does appear to be in the CTR. I have looked at CGUIDialogBoxBase but I am not sure of the best way to solve this.

**Comment by ulion** [comment]
Team Kodi uses github for development only, i.e. for pull requests and the discussion of code.

So we use a hook script to automatically close this new issue here.

If you can, we encourage you to investigate the issue yourself and create a Pull Request for us to review.
You may want to check the contributing guide: https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md

For bug reports, feature requests and all other support, please go to
http://forum.kodi.tv.

Thanks,
Team Kodi
